services:
  app:
    build: .
    ports:
      - '5500:5500'
    restart: on-failure:5
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - REDIS_URL=redis://localhost:6379
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - '6379:6379'
        # command: redis-server --loglevel verbose
    volumes:
      - redis-data:/data
        # logging:
        #   driver: 'json-file'
        #   options:
        #     max-size: '200m'
        #     max-file: '10'

volumes:
  redis-data:
