import { ListOption } from '../../../components/ListOption'

export const skills: ListOption[] = [
  '.NET',
  'AB Testing',
  'API Development',
  'AR/VR Design',
  'ASP.NET',
  'AWS',
  'Academic Writing',
  'Account Management',
  'Adobe XD',
  'Affiliate Marketing',
  'Agile Methodologies',
  'Android Development',
  'AngularJS',
  'Animation',
  'B2B Sales',
  'B2C Sales',
  'Bash/Shell',
  'Blogging',
  'Bootstrap',
  'Brand Management',
  'Budgeting',
  'Business Development',
  'Business Strategy',
  'C',
  'C#',
  'C++',
  'CRM',
  'CSS',
  'CSS3',
  'Change Management',
  'Channel Sales',
  'Cold Calling',
  'Color Theory',
  'Conflict Resolution',
  'Content Marketing',
  'Content Writing',
  'Conversion Rate Optimization',
  'Copywriting',
  'Creative Writing',
  'Data Analysis',
  'Data-driven Decision Making',
  'Direct Sales',
  'Django',
  'Docker',
  'Drupal',
  'Editing',
  'Email Marketing',
  'Emotional Intelligence',
  'Enterprise Sales',
  'Facebook Ads',
  'Figma',
  'Flutter',
  'Frontend Development',
  'Go',
  'Google Adwords',
  'Google Analytics',
  'Google Tag Manager',
  'Grant Writing',
  'Graphic Design',
  'HTML',
  'HTML5',
  'ITIL',
  'Illustrator',
  'InDesign',
  'Inbound Sales',
  'Interaction Design',
  'Java',
  'JavaScript',
  'Kanban',
  'Kotlin',
  'Laravel',
  'Leadership',
  'Lean',
  'Market Research',
  'Marketing Automation',
  'Marketing Strategy',
  'Medical Writing',
  'Mobile Advertising',
  'MongoDB',
  'Motion Graphics',
  'MySQL',
  'Negotiation',
  'Newsletters',
  'Node.js',
  'Objective-C',
  'Outbound Sales',
  'PHP',
  'PPC',
  'Performance Management',
  'Perl',
  'Photoshop',
  'Press Releases',
  'Prince2',
  'Project Management',
  'Proofreading',
  'Prototyping',
  'Public Relations',
  'Python',
  'React.js',
  'Resource Management',
  'Responsive Design',
  'Risk Management',
  'Ruby on Rails',
  'Ruby',
  'Rust',
  'SEM',
  'SEO Writing',
  'SEO',
  'SQL',
  'SaaS Sales',
  'Sales Analytics',
  'Sales Closing',
  'Sales Enablement',
  'Sales Forecasting',
  'Sales Management',
  'Sales Operations',
  'Sales Process',
  'Sales Strategy',
  'Salesforce',
  'Scala',
  'Scrum',
  'Sketch',
  'Social Media Marketing',
  'Strategic Planning',
  'Swift',
  'Team Building',
  'Technical Writing',
  'Telesales',
  'TypeScript',
  'Typography',
  'UI Design',
  'UX Design',
  'UX Research',
  'Video Marketing',
  'Viral Marketing',
  'Vue.js',
  'Waterfall',
  'Web Analytics',
  'Web Content Writing',
  'Web Design',
  'Web Development',
  'Whitepapers',
  'Wireframing',
  'WordPress',
  'YouTube Marketing',
  'iOS Development',
].map((skill) => ({ label: skill, value: skill }))
