version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    env_file: .env
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 5672
      - 15672

  mongo:
    image: mongo:latest
    env_file: .env
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local