import { saveOpenings } from 'db'
import { Topics } from 'shared'
import { Opening } from 'shared/src/email/openings-email/Opening'

const localOpenings: Opening[] = [
  {
    company: 'DBC Company',
    title: 'Análise de Qualidade',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Tests', 'Git', 'SQL'],
    headerInfo: 'Júnior',
    url: 'https://vagas.dbccompany.com.br/vagas/302274',
  },
  {
    company: 'DBC Company',
    title: 'Engenheiro de Dados',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Data Analysis', 'Python', 'SQL'],
    headerInfo: 'Júnior',
    url: 'https://vagas.dbccompany.com.br/vagas/302239',
  },
  {
    company: 'DBC Company',
    title: 'Analise de Testes',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Microservices Architecture', 'SQL', 'Microsoft Azure'],
    headerInfo: 'Júnior',
    url: 'https://vagas.dbccompany.com.br/vagas/302258',
  },
  {
    title: 'Senior Salesforce Software Engineer',
    company: 'Gympass',
    location: 'Brasil',
    headerInfo: 'Sênior',
    currency: 'R$',
    language: 'Português',
    url: 'https://boards.greenhouse.io/gympass/jobs/6966144002',
    skills: ['JavaScript', 'Apex', 'SOAP', 'Agile Methodologies'],
  },
  {
    title: 'Cientista de Dados (Forecasting)',
    company: 'Ambev',
    location: 'Brasil',
    currency: 'R$',
    language: 'Português e Inglês',
    headerInfo: 'Sênior',
    skills: [
      'Data Analysis',
      'Machine Learning',
      'Python',
      'Microsoft Azure',
      'SQL',
    ],
    url: 'https://vagas.byintera.com/home/ambev-tech-carreiras/',
  },
  {
    title: 'Pessoa Especialista em Arquitetura de Soluções AWS',
    company: 'Zup Innovation',
    location: 'Brasil',
    currency: 'R$',
    language: 'Português',
    headerInfo: 'Sênior',
    skills: [
      'AWS',
      'Microservices Architecture',
      'Docker',
      'Kubernetes',
      'Spring Framework',
    ],
    url: 'https://boards.greenhouse.io/zupinnovation/jobs/5746812003',
  },
  {
    title: 'Remote Mobile Developer',
    location: 'Brasil',
    language: 'Inglês',
    currency: 'R$',
    headerInfo: 'Mínimo de 3 anos de XP',
    skills: ['iOS', 'React Native', 'Swift', 'Objective-C', 'Web'],
    company: 'Scopic Software',
    url: 'https://scopicsoftware.hire.trakstar.com/jobs/fk0v62f',
  },
  {
    title: 'Remote Senior Web Engineer',
    location: 'Brasil',
    language: 'Inglês',
    company: 'Scopic Software',
    currency: 'R$',
    headerInfo: 'Mínimo de 6 anos de XP',
    skills: ['PHP', 'Node', 'Python', 'C#', 'Go'],
    url: 'https://scopicsoftware.hire.trakstar.com/jobs/fk0shc8',
  },
  {
    title: 'Angular Developer Senior',
    location: 'Brasil',
    language: 'Portuguese',
    currency: 'R$',
    company:
      'https://ciandt.com/br/pt-br/carreiras/oportunidades/candidate-se?opportunity=c3a5de3b-53d4-4134-8e00-e9bac057a8e7',
    headerInfo: 'Sênior',
    skills: ['.NET', 'C#', 'ASP.NET', 'CI', 'Angular'],
    url: 'https://ciandt.com/br/pt-br/carreiras/oportunidades/candidate-se?opportunity=c3a5de3b-53d4-4134-8e00-e9bac057a8e7',
  },
  {
    title: 'Desenvolvedor(a) .Net/Angular Pleno',
    company: 'Confitec',
    location: 'Brasil',
    language: 'Portuguese',
    currency: 'R$',
    headerInfo: 'Pleno',
    skills: ['.NET', 'Angular', 'Entity Framework', 'SQL', 'Docker'],
    url: 'https://trampos.co/oportunidades/755543-desenvolvedor-a-net-angular-pleno',
  },
  {
    title: 'Senior FullStack Developer (Python, React, JavaScript)',
    company: 'CI&T',
    location: 'Brasil',
    language: 'Portuguese',
    headerInfo: 'Sênior',
    skills: ['JavaScript', 'React', 'Python', 'Angular', 'Go'],
    currency: 'R$',
    url: 'https://ciandt.com/br/pt-br/carreiras/oportunidades/candidate-se?opportunity=ff93cb93-4675-4e47-b4da-8993a49c1d88',
  },
  {
    title: 'Desenvolvedor(a) .Net/Angular',
    company: 'Confitec',
    location: 'Brasil',
    currency: 'R$',
    language: 'Português',
    headerInfo: 'Pleno',
    url: 'https://trampos.co/oportunidades/755543-desenvolvedor-a-net-angular-pleno',
    skills: [
      '.NET',
      'Angular',
      'Entity Framework',
      'Microsoft Azure',
      'Docker',
    ],
  },
  {
    title: 'Tech Lead Fullstack SWE',
    company: 'Gympass',
    location: 'Brasil',
    headerInfo: 'Sênior',
    skills: ['TypeScript', 'Java', 'Go', 'AWS', 'Google Cloud Platform (GCP)'],
    url: 'https://boards.greenhouse.io/gympass/jobs/6821199002',
    language: 'Inglês',
    currency: 'R$',
  },
  {
    title: 'UX/UI Designer',
    company: 'Intra',
    skills: ['UX', 'UI', 'Design', 'Prototipação', 'Figma'],
    currency: 'R$',
    language: 'Português',
    location: 'Brasil',
    headerInfo: 'Pleno',
    url: 'https://vagas.byintera.com/3443-confidencial-n-ux-ui/',
  },
]

const globalOpenings: Opening[] = []

;(async () => {
  await Promise.all([
    await saveOpenings(globalOpenings, Topics.INTERNATIONAL_VACANCIES),
    await saveOpenings(localOpenings, Topics.NATIONAL_VACANCIES),
  ])
})()
