version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 5672
      - 15672
    environment:
      RABBITMQ_DEFAULT_USER: trampar
      RABBITMQ_DEFAULT_PASS: trampar-de-casa
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    networks:
      - mongo-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-data:/data/db
  roles-validator:
    build:
      context: .
      dockerfile: apps/auto-email-sender/roles-validator/Dockerfile
    env_file:
      - apps/auto-email-sender/roles-validator/.env
    depends_on:
      - mongo
  roles-renderer:
    environment:
      - MONGO_ADDRESS=mongodb://root:root@mongo:27017
    build:
      context: .
      dockerfile: apps/auto-email-sender/roles-renderer/Dockerfile
    env_file:
      - apps/auto-email-sender/roles-renderer/.env
    depends_on:
      - mongo
  roles-assigner:
    environment:
      - MONGO_ADDRESS=mongodb://root:root@mongo:27017
    build:
      context: .
      dockerfile: apps/auto-email-sender/roles-assigner/Dockerfile
    env_file:
      - apps/auto-email-sender/roles-assigner/.env
    depends_on:
      - mongo
      - rabbitmq
  email-pre-renderer:
    build:
      context: .
      dockerfile: apps/auto-email-sender/email-pre-renderer/Dockerfile
    env_file:
      - apps/auto-email-sender/email-pre-renderer/.env
    environment:
      RABBITMQ_ADDRESS: amqp://trampar:trampar-de-casa@rabbitmq
    depends_on:
      - mongo
      - rabbitmq
  email-composer:
    build:
      context: .
      dockerfile: apps/auto-email-sender/email-composer/Dockerfile
    env_file:
      - apps/auto-email-sender/email-composer/.env
    depends_on:
      - mongo
      - rabbitmq
  email-sender:
    build:
      context: .
      dockerfile: apps/auto-email-sender/email-sender/Dockerfile
    env_file:
      - apps/auto-email-sender/email-sender/.env
    environment:
      RABBITMQ_ADDRESS: amqp://trampar:trampar-de-casa@rabbitmq
    depends_on:
      - rabbitmq
networks:
  mongo-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
