services:
  rabbitmq:
    image: rabbitmq:3-management
    env_file: apps/auto-email-sender/.env
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 5672
      - 15672
  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'

  mongo:
    image: mongo:latest
    env_file: apps/auto-email-sender/.env
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  auto-email-sender:
    build:
      context: .
      dockerfile: Dockerfile.auto
    env_file:
      - apps/auto-email-sender/.env
    depends_on:
      - rabbitmq
      - mongo

volumes:
  redis-data:
  mongo-data:
    driver: local
