version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    env_file: apps/auto-email-sender-new/.env
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 5672
      - 15672

  mongo:
    image: mongo:latest
    env_file: apps/auto-email-sender-new/.env
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  auto-email-sender-new:
    image: gru.ocir.io/gricbxnlp2kb/auto-email-sender:latest
    env_file:
      - apps/auto-email-sender-new/.env
    depends_on:
      - rabbitmq
      - mongo

volumes:
  mongo-data:
    driver: local