version: '3'
services:
  rabbitmq:
    build: 
      dockerfile: ./Dockerfile_rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 5672
      - 15672
    environment:
      RABBITMQ_DEFAULT_USER: trampar
      RABBITMQ_DEFAULT_PASS: trampar-de-casa
  redis:
    image: redislabs/redismod
    ports:
      - '6379:6379'
    expose:
      - 6379
  roles-validator:
    build: 
      dockerfile: ./roles-validator-image
    env_file:
      - apps/workers/roles-validator/.env
    depends_on:
      - redis
  roles-renderer:
    build: 
      dockerfile: ./roles-renderer-image
    env_file:
      - apps/workers/roles-renderer/.env
    depends_on:
      - redis
  roles-assigner:
    build: 
      dockerfile: ./roles-assigner-image
    env_file:
      - apps/workers/roles-assigner/.env
    depends_on:
      - redis
      - rabbitmq
  email-pre-renderer:
    build: 
      dockerfile: ./email-pre-renderer-image
    env_file:
      - apps/workers/email-pre-renderer/.env
    depends_on:
      - redis
      - rabbitmq
  email-composer:
    build: 
      dockerfile: ./email-composer-image
    env_file:
      - apps/workers/email-composer/.env
    depends_on:
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
      roles-validator:
        condition: service_completed_successfully
  email-sender:
    build: 
      dockerfile: ./email-sender-image
    env_file:
      - apps/workers/email-sender/.env
    depends_on:
      - rabbitmq
