import { Opening } from 'shared/src/email/openings-email/Opening'
import { Openings } from '../Openings'

const localOpenings: Opening[] = []

const globalOpenings: Opening[] = [
  {
    company: 'Meteor Software',
    title: 'DevOps Engineer',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: [
      'AWS',
      'Kubernetes',
      'Terraform',
      'Observability',
      'ShellScripting',
    ],
    headerInfo: 'Pleno (até $3,500)',
    url: 'https://public.app.shortcut.com/62/meteor-software/docs/33M0mvrlVcqjX85UO74Hdl/devops-engineer',
  },
  {
    company: 'Strider',
    title: 'Mid-level Full-Stack Engineer - Angular.js',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Angular.js', 'OOP', 'TypeScript', 'JavaScript'],
    headerInfo: 'Mínimo de 3 anos de XP',
    url: 'app.onstrider.com/r/trampar_de_casa?job=bWlkLXNlbmlvci1mdWxsLXN0YWNrLWVuZ2luZWVyLWFuZ3VsYXItcHl0aG9uLTg3NjYzOWU0P3JlZmVycmFsPXRyYW1wYXJfZGVfY2FzYQ==',
  },
  {
    company: 'Strider',
    title: 'Database Administrator - MSSQL / Azure SQL',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['SQLServer', 'ETL', 'DataAnalytics'],
    headerInfo: 'Mínimo de 4 anos de experiência em desenvolvimento',
    url: 'app.onstrider.com/r/trampar_de_casa?job=c2VuaW9yLWRiYS1tc3NxbC04NjM3MThkMz9yZWZlcnJhbD10cmFtcGFyX2RlX2Nhc2E=',
  },
  {
    company: 'Strider',
    title: 'Full-stack Engineer - Node.js, Vue.js',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Node.js', 'Vue.js'],
    headerInfo: 'Mínimo de 4 anos de XP',
    url: 'app.onstrider.com/r/trampar_de_casa?job=ZnVsbC1zdGFjay1lbmdpbmVlci1ub2RlLmpzLXZ1ZS5qcy0wOGJlYWI3MT9yZWZlcnJhbD10cmFtcGFyX2RlX2Nhc2E=',
  },
  {
    company: 'Strider',
    title: 'Mid-Senior Full-stack Engineer - Spring Boot, React.js',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Java', 'SpringBoot', 'React.js'],
    headerInfo: 'Mínimo de 4 anos de XP',
    url: 'app.onstrider.com/r/trampar_de_casa?job=bWlkLXNlbmlvci1mdWxsLXN0YWNrLWVuZ2luZWVyLXNwcmluZy1ib290LXJlYWN0LmpzLWIxYWJmMTM3P3JlZmVycmFsPXRyYW1wYXJfZGVfY2FzYQ==',
  },
  {
    company: 'Strider',
    title: 'Software Developer, Áudio',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['C++', 'Juce'],
    headerInfo: 'Mínimo de 5 anos de XP',
    url: 'app.onstrider.com/r/trampar_de_casa?job=c29mdHdhcmUtZGV2ZWxvcGVyLWF1ZGlvLTFiOGMzM2U3P3JlZmVycmFsPXRyYW1wYXJfZGVfY2FzYQ==',
  },
  {
    company: 'Strider',
    title: 'Senior Data Engineer',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['AWS', 'Azure', 'GCP', 'Java', 'Scala'],
    headerInfo: 'Mínimo de 5 anos de XP',
    url: 'app.onstrider.com/r/trampar_de_casa?job=c2VuaW9yLWRhdGEtZW5naW5lZXItNWM0YzQ2YjQ/cmVmZXJyYWw9dHJhbXBhcl9kZV9jYXNh',
  },
  {
    company: 'Flylance',
    title: 'Sr. Full Stack Engineer',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Vue', 'React', 'Angular2', 'C#'],
    headerInfo: 'Mínimo de 5 anos de XP',
    url: 'https://www.flylance.com/role?id=rec8xi6wP4LwEW2A8',
  },
  {
    company: 'moveBuddha.com',
    title: 'Frontend Developer',
    location: 'Global',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Git', 'Heroku', 'JavaScript', 'React.js', 'RubyOnRails'],
    headerInfo: 'Pleno',
    url: 'https://dynamitejobs.com/company/movebuddhacom/remote-job/frontend-developer',
  },
  {
    company: 'Moovx',
    title: 'Sr Technical BSA (Oracle)',
    location: 'Uruguai',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Oracle', 'AR', 'GL', 'AP', 'INV'],
    headerInfo: 'Sênior',
    url: 'https://boards.greenhouse.io/moovx/jobs/4006578005',
  },
  {
    company: 'Moovx',
    title: 'Senior Python Software Engineer',
    location: 'Uruguai',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Python', 'AWS', 'Cognito', 'DynamoDB', 'Test'],
    headerInfo: 'Mínimo de 5 anos de XP',
    url: 'https://boards.greenhouse.io/moovx/jobs/4232093005',
  },
  {
    company: 'Flylance',
    title: 'Sr. Frontend Engineer (Vue.js)',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Vue.js', 'JavaScript', 'JSON', 'REST'],
    headerInfo: 'Mínimo de 5 anos de XP',
    url: 'https://www.flylance.com/role?id=rec1agBSh1RRZSzfu',
  },
  {
    company: 'Moovx',
    title: 'Senior Full Stack Engineer',
    location: 'Uruguai',
    language: 'Inglês',
    currency: 'U$',
    skills: ['JS', 'Angular', 'React', 'TypeScript', 'CSS'],
    headerInfo: 'Mínimo de 6 anos de XP',
    url: 'https://boards.greenhouse.io/moovx/jobs/4236540005',
  },
  {
    company: 'Elevate Labs',
    title: 'Senior iOS Engineer',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Ci/CD', 'iOS', 'Swift'],
    headerInfo: 'Mínimo de 7 anos de XP',
    url: 'https://jobs.lever.co/elevatelabs/46859a0e-6bb4-407a-9ede-26359e999925',
  },
  {
    company: 'Flylance',
    title: 'Sr. Product Designer',
    location: 'Remoto',
    language: '',
    currency: 'U$',
    skills: ['UsabilityTesting', 'Prototyping', 'Figma', 'Typography'],
    headerInfo: 'Mínimo de 7 anos de XP',
    url: 'https://www.flylance.com/role?id=receY44tUh9fTv0q6',
  },
]

export const openings20230830: Openings = {
  localOpenings,
  globalOpenings,
}
