name: Build and push router app 

on:
  push:
    branches:
      - 'main'
    paths:
      - 'apps/router/**/*'
      - 'apps/router/*'
  workflow_dispatch:
    inputs:
      platform:
        description: 'Build platform (amd64 or arm64)'
        required: false
        default: 'amd64'
        type: string

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ inputs.platform || 'amd64' }}

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_HOST }}
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASS }}

      - name: Build Docker image
        run: |
          REGISTRY=${{ secrets.DOCKER_REGISTRY_HOST }}
          REPO='router-app'
          PLATFORM='linux/${{ inputs.platform || 'amd64' }}'
          
          cd apps/router
          docker buildx build . --platform $PLATFORM -t "$REGISTRY/$REPO:latest" --push
