import { Opening } from 'shared/src/email/openings-email/Opening'
import { Openings } from '../Openings'

const localOpenings: Opening[] = []

const globalOpenings: Opening[] = [
  {
    company: 'Variant Perception',
    title: 'UX Engineer',
    location: 'London',
    language: 'Inglês',
    currency: 'U$',
    skills: ['UI/UX Design', 'Firebase', 'React.js', 'GCP', 'Next.js'],
    headerInfo: '$9,166 até $12,500',
    url: 'URL do anúncio da vaga, se disponível',
  },
  {
    company: 'Fly.io',
    title: 'Infrastructure Ops Engineering',
    location: 'Global',
    language: 'Inglês',
    currency: 'U$',
    skills: [
      'Infrastructure',
      'Linux',
      'Problem Solving',
      'Software engineering',
    ],
    headerInfo: 'Pleno($7,500 até $16,666)',
    url: 'https://fly.io/jobs/infrastructure-ops-engineering/',
  },
  {
    company: 'Subspace Labs',
    title: 'Protocol Engineer (Core)',
    location: 'Global',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Rust', 'Python', 'Collaboration skills', 'TypeScript'],
    headerInfo: 'Pleno',
    url: 'https://jobs.lever.co/subspacelabs/7f6a654b-60a8-4740-aa19-36b9f7a9e624',
  },
  {
    company: 'Gnosis',
    title: 'Algorithm Engineer',
    location: 'Global',
    language: 'Inglês',
    currency: 'U$',
    skills: [
      'Data Analysis',
      'Documentation',
      'Mathematics',
      'Rust',
      'Software engineering',
    ],
    headerInfo: 'Pleno',
    url: 'https://gnosis.jobs.personio.com/job/1245798?language=en&display=en',
  },
  {
    company: 'Huddle01',
    title: 'DevOps Engineer',
    location: 'Global',
    language: 'Inglês',
    currency: 'U$',
    skills: ['AWS', 'CI/CD', 'DevOps', 'Grafana', 'Kubernetes'],
    headerInfo: 'Mínimo de 2 anos de XP',
    url: 'https://boards.greenhouse.io/huddle01/jobs/4015008007',
  },
  {
    company: 'Subspace Labs',
    title: 'Solidity Developer',
    location: 'Global',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Defi', 'GraphQL', 'Solidity', 'TypeScript'],
    headerInfo: 'Mínimo de 3 anos de XP',
    url: 'https://jobs.lever.co/subspacelabs/a943717b-0112-4158-9267-e5d86f68898d',
  },
  {
    company: 'Strider',
    title: 'Mid-Senior Full-stack Engineer - Spring Boot, React.js',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Java', 'Spring Boot', 'React.js'],
    headerInfo: 'Mínimo de 4 anos de XP',
    url: 'app.onstrider.com/r/trampar_de_casa?job=bWlkLXNlbmlvci1mdWxsLXN0YWNrLWVuZ2luZWVyLXNwcmluZy1ib290LXJlYWN0LmpzLWIxYWJmMTM3P3JlZmVycmFsPXRyYW1wYXJfZGVfY2FzYQ==',
  },
  {
    company: 'Ofri Internet GmbH',
    title: 'Full Stack RoR Developer (Mid-Level)',
    location: 'Global',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Ruby on Rails', 'MySQL', 'Docker', 'Kanban'],
    headerInfo: 'Mínimo de 5 anos de XP',
    url: 'https://join.com/companies/ofri/9066317-remote-full-stack-ror-developer-mid-level?pid=369b2d9eb02b4d98c0ad&oid=384acd85-ef63-4bd3-9bf1-0c79dd7a4745',
  },
  {
    company: 'Nimble',
    title: 'Senior Software Engineer (Full-Stack)',
    location: 'Global',
    language: 'Inglês',
    currency: 'U$',
    skills: ['React', 'Django', 'Desenvolvimento de software', 'DevOps'],
    headerInfo: 'Sênior($12,083 até $14,166)',
    url: 'https://wellfound.com/jobs/2787116-senior-software-engineer-full-stack',
  },
  {
    company: 'Fingerprint',
    title: 'Senior Full Stack Engineer',
    location: 'Global',
    language: 'Inglês',
    currency: 'U$',
    skills: ['AWS', 'React.js', 'TypeScript', 'Web Browsers', 'Cryptography'],
    headerInfo: 'Sênior($8,333 até $13,333)',
    url: 'https://fingerprint.com/careers/jobs/apply/?gh_jid=4872204004',
  },
  {
    company: 'Fingerprint',
    title: 'Senior Frontend Engineer',
    location: 'Global',
    language: 'Inglês',
    currency: 'U$',
    skills: [
      'Front-End',
      'React.js',
      'TypeScript',
      'Wireframing',
      'Collaboration Skills',
    ],
    headerInfo: 'Sênior($8,333 até $13,333)',
    url: 'https://fingerprint.com/careers/jobs/apply/?gh_jid=4927035004',
  },
  {
    company: 'Hypixel Studios',
    title: 'Senior Systems Administrator',
    location: 'Global',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Cyber Security', 'Python', 'Terraform', 'Troubleshooting'],
    headerInfo: 'Mínimo de 5 anos de XP',
    url: 'https://boards.greenhouse.io/hypixelstudios/jobs/5187436003',
  },
  {
    company: 'BizSpeed',
    title: 'Senior Software Engineer',
    location: 'Global',
    language: 'Inglês',
    currency: 'U$',
    skills: ['SQL', 'Svelte', 'Tailwind', 'TypeScript', 'UI'],
    headerInfo: 'Mínimo de 5 anos de XP',
    url: 'https://dynamitejobs.com/company/bizspeed/remote-job/senior-software-engineer',
  },
  {
    company: 'Glide',
    title: 'Senior Software Engineer - Fullstack',
    location: 'New York City, NY',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Javascript', 'Typescript', 'React', 'NextJS', 'Docker'],
    headerInfo: 'Mínimo de 5 anos de XP',
    url: 'https://careers.withglide.com/28074',
  },
  {
    company: 'Gnosis',
    title: 'Senior Security Engineer',
    location: 'Global',
    language: 'Inglês',
    currency: 'U$',
    skills: [
      'AWS',
      'Cloud Security',
      'Google Cloud',
      'Security Compliance Standards (ISO 27001, GDPR)',
      'CISSP, CISM, or CEH Certification',
    ],
    headerInfo: 'Sênior',
    url: 'https://gnosis.jobs.personio.com/job/1164861?language=en&display=en',
  },
]

export const openings20230913: Openings = {
  localOpenings,
  globalOpenings,
}
