import { Opening } from 'shared/src/email/openings-email/Opening'
import { Openings } from '../Openings'

const localOpenings: Opening[] = [
  {
    company: 'Luizalabs',
    title: 'Desenvolvedor(a) Backend Júnior',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Cloud', 'Docker', 'Linguagens de Programação'],
    headerInfo: 'Júnior (Exclusiva Para Pessoas com Deficiência)',
    url: 'https://carreiras.magazineluiza.com.br/vagas/332911-desenvolvedor-a-backend-junior-100-remoto-vaga-exclusiva-para-pessoas-com-deficiencia-pcd',
  },
  {
    company: 'Adalov',
    title: 'Pessoa Desenvolvedora - PHP',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['PHP', 'Laravel', 'MySQL', 'Git'],
    headerInfo: 'Júnior',
    url: 'https://programathor.com.br/jobs/29246-pessoa-desenvolvedora-php-junior',
  },
  {
    company: 'Acerto',
    title: 'Analista de Design Junior',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: [
      'Criação Visual',
      'Design',
      'Criação de Arte',
      'Layouts Digitais',
      'Adobe Suite',
    ],
    headerInfo: 'Júnior',
    url: 'https://acerto.vagas.solides.com.br/vaga/288388',
  },
  {
    company: 'Venturus',
    title: 'UX/UI Designer JR',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: [
      'Inglês',
      'Comunicação',
      'Criatividade',
      'Proatividade',
      'Prototipagem',
    ],
    headerInfo: 'Júnior',
    url: 'https://venturus.inhire.app/vagas/09905e1b-6b95-4b5b-95fa-79766ddf51af/uxui-designer-jr',
  },
  {
    company: 'RD Station',
    title: 'Mulher Engenheira de Software Pleno - Backend',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['RubyOnRails', 'Cloud', 'Metodologias Ágeis', 'Frontend'],
    headerInfo: 'Pleno (Vaga exclusiva para mulheres)',
    url: 'https://boards.greenhouse.io/rdstation/jobs/6715548002',
  },
  {
    company: 'RD (Resultados Digitais)',
    title: 'Mulher Engenheira de Dados Pleno - Internal Systems & Data',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Python', 'Java', 'SQL', 'BancoDeDados', 'Clouds'],
    headerInfo: 'Pleno (Vaga exclusiva para mulheres)',
    url: 'https://boards.greenhouse.io/rdstation/jobs/6908859002',
  },
  {
    company: 'Xgrow',
    title: 'Desenvolvedor(a) Full Stack - Pleno',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Vue.js', 'HTML', 'JavaScript', 'jQuery', 'PHP'],
    headerInfo: 'Pleno (Até R$8,000)',
    url: 'https://programathor.com.br/jobs/29271-desenvolvedor-a-full-stack-pleno',
  },
  {
    company: 'Gesuas',
    title: 'Desenvolvedor(a) Front-end Pleno',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['CSS', 'Docker', 'HTML', 'JavaScript', 'Vue.js'],
    headerInfo: 'Pleno (Até R$5,000)',
    url: 'https://programathor.com.br/jobs/29263-desenvolvedor-a-front-end-pleno',
  },
  {
    company: 'Venturus',
    title: 'UX/UI Designer PL',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['UX/UI', 'Frontend', 'Ferramentas de design', 'Inglês'],
    headerInfo: 'Pleno',
    url: 'https://venturus.inhire.app/vagas/55906985-754b-4456-ab4e-0fe79d1f2148/uxui-designer-pl',
  },
  {
    company: 'GP Combustíveis',
    title: 'PROGRAMADOR(A) WEB PLENO',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['.NET', 'Java', 'SQL', 'CSS', 'jQuery'],
    headerInfo: 'Pleno',
    url: 'https://programathor.com.br/jobs/29297-programador-a-web-pleno',
  },
  {
    company: 'Loja Integrada',
    title: 'Analista de Dados',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['PowerBI'],
    headerInfo: 'Pleno',
    url: 'https://boards.greenhouse.io/lojaintegrada/jobs/4967333004?t=24dd67234us',
  },
  {
    company: 'BairesDev',
    title: 'Arquiteto(a) Node',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: [
      'Node.js',
      'Bases de Dados',
      'Design',
      'Segurança',
      'Escalabilidade',
    ],
    headerInfo: 'Pleno',
    url: 'https://programathor.com.br/jobs/29282-trabalhe-de-casa-arquiteto-a-node',
  },
  {
    company: 'Adalov',
    title: 'Pessoa Desenvolvedora - PHP Pleno',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Git', 'Laravel', 'MySQL', 'PHP'],
    headerInfo: 'Pleno',
    url: 'https://programathor.com.br/jobs/29247-pessoa-desenvolvedora-php-pleno',
  },
  {
    company: 'XP Inc.',
    title: 'Data Science',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['DataScience', 'SQL', 'Python', 'MapeamentoDados', 'Estatística'],
    headerInfo: 'Pleno',
    url: 'https://boards.greenhouse.io/xpinc/jobs/5927851002',
  },
  {
    company: 'Trakstar',
    title: 'Pessoa Analista de BI',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: [
      'AnáliseDados',
      'BusinessIntelligence',
      'BigData',
      'EngenhariaDados',
      'ModelagemDados',
    ],
    headerInfo: 'Pleno',
    url: 'https://lambda3.hire.trakstar.com/jobs/fk0xkwm/',
  },
  {
    company: 'Boavista Tecnologia',
    title: 'Pessoa Desenvolvedora Java Sênior - Tech Lead',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Java', 'PostgreSql', 'MongoDB', 'Angular', 'React'],
    headerInfo: 'Sênior (até R$15,000)',
    url: 'https://programathor.com.br/jobs/29294-pessoa-desenvolvedora-java-senior-tech-lead',
  },

  {
    company: 'Acerto',
    title: 'Analista Dev Backend Sr',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['C#', 'CI/CD', 'PostgreSQL', 'C4Model', 'Datadog'],
    headerInfo: 'Sênior (Vaga para Mulheres)',
    url: 'https://acerto.vagas.solides.com.br/vaga/293341',
  },
  {
    company: 'Tetris IT',
    title: 'Desenvolvedor(a) Camunda Sênior',
    location: '100% Remoto',
    language: 'Português',
    currency: 'R$',
    skills: ['Camunda', 'BPMN 2.0', 'DMN 1.3', '.NET'],
    headerInfo: 'Sênior (Até R$15,000)',
    url: 'https://programathor.com.br/jobs/29251-desenvolvedor-a-camunda-senior',
  },
  {
    company: 'Meutudo.',
    title: 'Senior Backend Developer',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Java', 'Spring Boot', 'Hibernate', 'AWS', 'Node.js'],
    headerInfo: 'Sênior',
    url: 'https://jobs.quickin.io/meutudo/jobs/647ba51b4d756e001c750e7b',
  },
  {
    company: 'Venturus',
    title: 'Pessoa Desenvolvedora Front-end React Senior',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['ReactJS', 'Redux', 'zustand', 'Typescript', 'Jest'],
    headerInfo: 'Sênior',
    url: 'https://venturus.inhire.app/vagas/da8236c7-18fd-4d30-9739-efdc7fa5ecc3/457-pessoa-desenvolvedora-front-end-react-senior',
  },
]

const globalOpenings: Opening[] = [
  {
    company: 'Meteor Software',
    title: 'DevOps Engineer',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: [
      'AWS',
      'Kubernetes',
      'Terraform',
      'Observability',
      'ShellScripting',
    ],
    headerInfo: 'Pleno (até $3,500)',
    url: 'https://public.app.shortcut.com/62/meteor-software/docs/33M0mvrlVcqjX85UO74Hdl/devops-engineer',
  },
  {
    company: 'Strider',
    title: 'Mid-level Full-Stack Engineer - Angular.js',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Angular.js', 'OOP', 'TypeScript', 'JavaScript'],
    headerInfo: 'Mínimo de 3 anos de XP',
    url: 'app.onstrider.com/r/trampar_de_casa?job=bWlkLXNlbmlvci1mdWxsLXN0YWNrLWVuZ2luZWVyLWFuZ3VsYXItcHl0aG9uLTg3NjYzOWU0P3JlZmVycmFsPXRyYW1wYXJfZGVfY2FzYQ==',
  },
  {
    company: 'Strider',
    title: 'Mid-Senior Full-stack Engineer - Spring Boot, React.js',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Java', 'Spring Boot', 'React.js'],
    headerInfo: 'Mínimo de 4 anos de XP',
    url: 'app.onstrider.com/r/trampar_de_casa?job=bWlkLXNlbmlvci1mdWxsLXN0YWNrLWVuZ2luZWVyLXNwcmluZy1ib290LXJlYWN0LmpzLWIxYWJmMTM3P3JlZmVycmFsPXRyYW1wYXJfZGVfY2FzYQ==',
  },
  {
    company: 'Strider',
    title: 'Senior Full-stack Engineer - Django, React.js',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Django', 'React.js', 'Fullstack'],
    headerInfo: 'Mínimo de 5 anos de XP',
    url: 'app.onstrider.com/r/trampar_de_casa?job=c2VuaW9yLWZ1bGwtc3RhY2stZW5naW5lZXItZGphbmdvLXJlYWN0LmpzLTBhOTc2MjU0MmEwMj9yZWZlcnJhbD10cmFtcGFyX2RlX2Nhc2E=',
  },
  {
    company: 'Strider',
    title: 'Senior Data Engineer',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Python', 'AWS', 'Azure', 'GCP', 'Airflow'],
    headerInfo: 'Mínimo de 5 anos de XP',
    url: 'app.onstrider.com/r/trampar_de_casa?job=c2VuaW9yLWRhdGEtZW5naW5lZXItNWM0YzQ2YjQ/cmVmZXJyYWw9dHJhbXBhcl9kZV9jYXNh',
  },
  {
    company: 'Strider',
    title: 'Software Developer, Audio',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['C++', 'Juce'],
    headerInfo: 'Mínimo de 5 anos de XP',
    url: 'app.onstrider.com/r/trampar_de_casa?job=c29mdHdhcmUtZGV2ZWxvcGVyLWF1ZGlvLTFiOGMzM2U3P3JlZmVycmFsPXRyYW1wYXJfZGVfY2FzYQ==',
  },
  {
    company: 'Exodus',
    title: 'AI Engineer',
    location: 'Global',
    language: 'Inglês',
    currency: 'U$',
    skills: ['IA/ML', 'JavaScript', 'Node.js', 'React', 'ReactNative'],
    headerInfo: 'Pleno ($12,500 até $15,408)',
    url: 'https://boards.greenhouse.io/exodus54/jobs/4237402006',
  },
  {
    company: 'Bitfinex',
    title: 'Open Source Developer',
    location: 'Global',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Python', 'Android', 'Desenvolvimento iOS', 'Blockchain', 'Rust'],
    headerInfo: 'Mínimo de 4 anos de XP($3,333 até $9,166)',
    url: 'https://wellfound.com/jobs/2783889-open-source-developer-remote',
  },
  {
    company: 'Toggl',
    title: 'Data Engineer',
    location: 'Global',
    language: 'Inglês',
    currency: 'EUR',
    skills: ['Airbyte', 'Prefect', 'dbt', 'SQL', 'Git'],
    headerInfo: 'Mínimo de 2 anos de XP(€5,166)',
    url: 'https://toggl.com/jobs/toggl-data-engineer/',
  },
  {
    company: 'Product Hunt',
    title: 'Software Engineer',
    location: 'Global',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Ruby', 'Rails', 'React', 'NextJS'],
    headerInfo: 'Pleno',
    url: 'https://product-hunt.breezy.hr/p/9a4ac9c8cd6301-software-engineer',
  },
  {
    company: 'Bitquery',
    title: 'UI / Frontend Senior Developer',
    location: 'Global',
    language: 'Inglês',
    currency: 'U$',
    skills: ['React', 'GraphQL', 'SQL', 'Docker', 'Grafana'],
    headerInfo: 'Pleno',
    url: 'https://apply.workable.com/bitquery/j/BF5DAFFA08/',
  },
  {
    company: 'Bitfinex',
    title: 'Senior Backend Developer - Node (Remote) (5+ years exp)',
    location: 'Global',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Javascript', 'MySQL', 'MongoDB', 'Blockchain', 'NodeJS'],
    headerInfo: 'Sênior ($5,000 até $10,000)',
    url: 'https://wellfound.com/company-l/bitfinex/jobs/2783891-senior-backend-developer-node-remote',
  },
  {
    company: 'Flylance',
    title: 'Oracle EBS Support Specialist (AP/GL)',
    location: 'Remoto',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Oracle Cloud'],
    headerInfo: 'Sênior',
    url: 'https://www.flylance.com/role?id=reckrZzU5p1qcuo2H',
  },
  {
    company: 'Bitquery',
    title: 'ML Engineer',
    location: 'Global',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Python', 'PyTorch', 'SciPy', 'TensorFlow', 'Blockchain'],
    headerInfo: 'Sênior',
    url: 'https://apply.workable.com/bitquery/j/E09A2D7EB6/',
  },
  {
    company: 'Flylance',
    title: 'Sr. Frontend Engineer (Vue.js)',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Vue.js', 'JSON', 'REST', 'SQL', 'MongoDB'],
    headerInfo: 'Mínimo de 5 anos de XP',
    url: 'https://www.flylance.com/role?id=rec1agBSh1RRZSzfu',
  },
]

export const openings20230906: Openings = {
  localOpenings,
  globalOpenings,
}
