import { Opening } from 'shared/src/email/openings-email/Opening'
import { Openings } from '../Openings'

const localOpenings: Opening[] = [
  {
    company: 'Mandarin',
    title: 'Desenvolvedor(a) Full-Stack Estágio',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Frontend', 'Backend'],
    headerInfo: 'Estágio',
    url: 'https://programathor.com.br/jobs/29093-estagio-em-desenvolvimento-web',
  },
  {
    company: 'Ubots',
    title: 'Desenvolvedor(a) Fullstack Júnior',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Java', 'Javascript', 'Python', 'Webapps', 'DevOps'],
    headerInfo: 'Júnior (até R$3,000)',
    url: 'https://programathor.com.br/jobs/29084-desenvolvedor-a-back-end-jr',
  },
  {
    company: 'Elemento RH',
    title: 'Desenvolvedor BackEnd (Python)',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['FastAPI', 'Flask', 'Testes', 'SQL'],
    headerInfo: 'Júnior',
    url: 'https://jobs.quickin.io/grupoelementorh/jobs/649a0c9fd06205001cdbc9e4',
  },
  {
    company: 'Impulso',
    title: 'Pleno Fullstack',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['JavaScript', 'RubyOnRails', 'DevOps'],
    headerInfo: 'Pleno (até R$12,800)',
    url: 'https://impulso.team/pt/profissionais/oportunidade/1915',
  },
  {
    company: 'InfoPrice',
    title: 'Desenvolvedor(a) Pleno',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['WebScraping', 'BigData', 'DataPipeline', 'ETL', 'SQL'],
    headerInfo: 'Pleno (até R$10,000)',
    url: 'https://programathor.com.br/jobs/29078-data-engineer-pleno',
  },
  {
    company: 'Logcomex',
    title: 'Desenvolvedor(a) FullStack (PHP, Python e VueJS)',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Python', 'VueJS', 'Laravel', 'Docker', 'Postgres'],
    headerInfo: 'Pleno (até R$8,000)',
    url: 'https://programathor.com.br/jobs/29072-desenvolvedor-a-full-stack-pleno-php-python-e-vuejs',
  },
  {
    company: 'InfoPrice',
    title: 'Data Engineer',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['BigData', 'DataLake', 'DataPipeline', 'ETL', 'WebCrawling'],
    headerInfo: 'Pleno (até R$10,000)',
    url: 'https://programathor.com.br/jobs/29078-data-engineer-pleno',
  },
  {
    company: 'Elemento RH',
    title: 'Desenvolvedor BackEnd (Python)',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Python', 'FastAPI', 'Flask', 'POO', 'Testes'],
    headerInfo: 'Pleno',
    url: 'https://jobs.quickin.io/grupoelementorh/jobs/645abf2327eba1001cd9ba51',
  },
  {
    company: 'vagas.com',
    title: 'Engenheiro de Software Front End (React)',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['HTML', 'CSS', 'JavaScript', 'React', 'Responsividade'],
    headerInfo: 'Pleno',
    url: 'https://www.vagas.com.br/vagas/v2543504/pessoa-engenheira-de-software-front-end-pleno',
  },
  {
    company: 'Bosch Brasil',
    title: 'Outsystem Developer',
    location: 'Brasil',
    language: 'Inglês',
    currency: 'R$',
    skills: ['PowerAutomate', 'RPA', 'AiBuilder'],
    headerInfo: 'Pleno',
    url: 'https://vagas.byintera.com/bosch-carreiras/',
  },
  {
    company: 'Impulso',
    title: 'Consultor Funcional Oracle Fusion Cloud',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Oracle', 'DRE', 'BP'],
    headerInfo: 'Sênior (até R$27,520)',
    url: 'https://impulso.team/pt/profissionais/oportunidade/1880-senior-consultor-funcional-oracle-fusion-cloud',
  },
  {
    company: 'Impulso',
    title: 'Desenvolvedor(a) Fullstack (.NET e Angular)',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['.NET', 'Angular', 'Typescript', 'CI/CD', 'RabbitMQ'],
    headerInfo: 'Sênior (até R$16,000)',
    url: 'https://impulso.team/pt/profissionais/oportunidade/1913-senior-c-net-angular',
  },
  {
    company: 'Evah saude',
    title: 'Desenvolvedor(a) Sênior FullStack (Python)',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Django', 'PostgreSQL', 'Agile', 'Liderança', 'Mentoria'],
    headerInfo: 'Sênior (até R$15,000)',
    url: 'https://programathor.com.br/jobs/29067-desenvolvedor-a-senior-full-stack-python-django',
  },
  {
    company: 'Bosch Brasil',
    title: 'Desenvolvedor(a) Sênior (C++ e Rust)',
    location: 'Brasil',
    language: 'Inglês',
    currency: 'R$',
    skills: ['C++', 'Rust', 'WebAssembly', 'Matlab', 'CI-Process'],
    headerInfo: 'Sênior',
    url: 'https://vagas.byintera.com/bosch-carreiras/',
  },
  {
    company: 'NDD Tech Brasil',
    title: 'Analista Desenvolvedor Pleno (C#)',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['C#', '.NET', 'Angular', 'TypeScript'],
    headerInfo: 'Pleno',
    url: 'https://jobs.quickin.io/nddtech/jobs/64550a1d19e7cc00130d7b45',
  },
  {
    company: 'Picpay',
    title: 'Desenvolvedor Backend Sênior (Golang)',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['POO', 'Microsserviços', 'API', 'NoSQL', 'SQL'],
    headerInfo: 'Sênior',
    url: 'https://picpay.com/oportunidades-de-emprego-e-carreiras/central-de-vagas/4295952005',
  },
  {
    company: 'NDD Tech Brasil',
    title: 'Coordenador de Projetos',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Gestão', 'TMS', 'PMBOK', 'Ágil'],
    headerInfo: 'Coordenador', //! Sem tempo minimo, sem informacao de senioridade e sem salario
    url: 'https://jobs.quickin.io/nddtech/jobs/64636b9115cee30015912c91?',
  },
  {
    company: 'The Stagwell Group Brasil', //! Eh brasileira mesmo?
    title: 'Desenvolvedor(a) Pleno (C#)',
    location: 'Brasil',
    language: 'Inglês',
    currency: 'R$',
    skills: ['C#', 'C++', '.NET'],
    headerInfo: 'Pleno',
    url: 'https://programathor.com.br/jobs/29089-c-net-developer-mid-level',
  },
  {
    company: 'The Stagwell Group Brasil',
    title: 'Desenvovledor(a) Backend (Node.JS)',
    location: 'Brasil',
    language: 'Inglês',
    currency: 'R$',
    skills: ['Node', 'Typescript', 'Postgres'],
    headerInfo: 'Pleno',
    url: 'https://programathor.com.br/jobs/29088-back-end-developer-node-js-mid-level',
  },
  {
    company: 'The Stagwell Group Brasil',
    title: 'Desenvolvedor(a) Frontend (React)',
    location: 'Brasil',
    language: 'Inglês',
    currency: 'R$',
    skills: ['Angular', 'Next', 'React', 'Vue.js', 'JavaScript'],
    headerInfo: 'Pleno',
    url: 'https://programathor.com.br/jobs/29090-front-end-developer-mid-level',
  },
]

const globalOpenings: Opening[] = [
  {
    title: 'Mid-senior Full-Stack Engineer',
    company: 'Strider',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Angular.js', 'Python', 'TypeScript', 'JavaScript'],
    headerInfo: 'Mínimo de 3 anos de XP',
    url: 'https://app.onstrider.com/r/trampar_de_casa?job=bWlkLXNlbmlvci1mdWxsLXN0YWNrLWVuZ2luZWVyLWFuZ3VsYXItcHl0aG9uLTg3NjYzOWU0P3JlZmVycmFsPXRyYW1wYXJfZGVfY2FzYQ==',
  },
  {
    title: 'Product Designer',
    company: 'Strider',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['UI', 'UX'],
    headerInfo: 'Mínimo de 3 anos de XP',
    url: 'https://app.onstrider.com/r/trampar_de_casa?job=cHJvZHVjdC1kZXNpZ25lci1kN2VkMmJhOT9yZWZlcnJhbD10cmFtcGFyX2RlX2Nhc2E=',
  },
  {
    title: 'Mid-level Scraping Engineer',
    company: 'Strider',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Python', 'Playwright', 'HTML'],
    headerInfo: 'Mínimo de 3 anos de XP',
    url: 'https://app.onstrider.com/r/trampar_de_casa?job=bWlkLWxldmVsLXNjcmFwaW5nLWVuZ2luZWVyLXB5dGhvbi03NjhiOTdhYz9yZWZlcnJhbD10cmFtcGFyX2RlX2Nhc2E=',
  },
  {
    title: 'Senior Mobile Engineer (React Native)',
    company: 'Strider',
    location: 'Canadá',
    language: 'Inglês',
    currency: 'U$',
    skills: ['ReactNative', 'Node.js', 'Firebase', 'MongoDB'],
    headerInfo: 'Mínimo de 4 anos de XP',
    url: 'https://app.onstrider.com/r/trampar_de_casa?job=c2VuaW9yLW1vYmlsZS1lbmdpbmVlci1jOWFlMzc3MT9yZWZlcnJhbD10cmFtcGFyX2RlX2Nhc2E=',
  },
  {
    title: 'Mid-Senior Mobile Engineer (Swift)',
    company: 'Strider',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Swift'],
    headerInfo: 'Mínimo de 4 anos de XP',
    url: 'https://app.onstrider.com/r/trampar_de_casa?job=bWlkLXNlbmlvci1tb2JpbGUtZW5naW5lZXItc3dpZnQtODQ5NDhkYTU/cmVmZXJyYWw9dHJhbXBhcl9kZV9jYXNh',
  },
  {
    title: 'Lead Data Scientist',
    company: 'Strider',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['GenerativeAI', 'DataScience'],
    headerInfo: 'Mínimo de 6 anos de XP',
    url: 'https://app.onstrider.com/r/trampar_de_casa?job=bGVhZC1kYXRhLXNjaWVudGlzdC1kOGViNmJjYT9yZWZlcnJhbD10cmFtcGFyX2RlX2Nhc2E=',
  },
  {
    title: 'Frontend Developer (React)',
    company: 'Bejamas',
    location: 'Polônia',
    language: 'Inglês',
    currency: 'U$',
    skills: ['React', 'Git', 'Kanban', 'Scrum', 'TypeScript'],
    headerInfo: 'Mínimo de 2 anos de XP ',
    url: 'https://dynamitejobs.com/company/bejamas/remote-job/frontend-developer-2',
  },
  {
    title: 'Frontend Engineer (React)',
    company: 'MultiversX',
    location: 'Europa',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Frontend', 'Git', 'JavaScript', 'React'],
    headerInfo: 'Mínimo de 2 anos de XP',
    url: 'https://dynamitejobs.com/company/multiversx/remote-job/front-end-engineer-react',
  },
  {
    title: 'Senior Frontend Engineer (Angular)',
    company: 'Slate',
    location: 'Europa',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Angular', 'Bootstrap4', 'JavaScript', 'NgRx', 'TypeScript'],
    headerInfo: 'Mínimo de 5 anos de XP ($6,250 a $7,500)',
    url: 'https://dynamitejobs.com/company/slate/remote-job/senior-frontend-engineer',
  },
  {
    title: 'Frontend Developer (React)',
    company: 'Build With Assembly',
    location: 'Canadá',
    language: 'Inglês',
    currency: 'U$',
    skills: ['CSS3', 'JavaScript', 'React'],
    headerInfo: 'Mínimo de 5 anos de XP',
    url: 'https://dynamitejobs.com/company/buildwithassembly/remote-job/software-engineer-front-end-developer',
  },

  {
    title: 'DevOps Engineer',
    company: 'CloudTalk',
    location: 'Europa',
    language: 'Inglês',
    currency: 'U$',
    skills: ['AWS', 'DevOps', 'Kubernetes', 'Terraform'],
    headerInfo: 'Pleno',
    url: 'https://dynamitejobs.com/company/cloudtalk/remote-job/devops-engineer ',
  },
  {
    title: 'PHP Developer',
    company: 'CloudTalk',
    location: 'Europa',
    language: 'Inglês',
    currency: 'U$',
    skills: ['PHP', 'HTML', 'SQL', 'Github', 'CI/CD'],
    headerInfo: 'Pleno',
    url: 'https://dynamitejobs.com/company/cloudtalk/remote-job/php-developer',
  },
  {
    title: 'Full Stack Developer',
    company: 'Outcoding',
    location: 'Costa Rica',
    language: 'Inglês',
    currency: 'U$',
    skills: ['FullStack', 'Html/js/css', 'Java', 'Python'],
    headerInfo: 'Pleno',
    url: 'https://dynamitejobs.com/company/outcoding/remote-job/full-stack-developer',
  },
  {
    title: 'DevOps Engineer',
    company: 'Outcoding',
    location: 'Costa Rica',
    language: 'Inglês',
    currency: 'U$',
    skills: ['AWS', 'DevOps', 'Python', 'Ruby', 'SQL'],
    headerInfo: 'Pleno',
    url: 'https://dynamitejobs.com/company/outcoding/remote-job/devops-engineer',
  },
  {
    title: 'Full-stack Developer (React e C#)',
    company: 'Kontent.ai',
    location: 'Tchéquia',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Azure', 'C#', 'React', 'Redux'],
    headerInfo: 'Pleno',
    url: 'https://dynamitejobs.com/company/kontentai/remote-job/full-stack-developer',
  },
]

export const openings20230726: Openings = {
  localOpenings,
  globalOpenings,
}
