import { saveOpenings } from 'db'
import { Topics } from 'shared'
import { Opening } from 'shared/src/email/openings-email/Opening'
import { Openings } from '../Openings'

const localOpenings: Opening[] = [
  {
    company: 'Segarante',
    title: 'Back-end Developer Ruby on Rails Pleno',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Ruby on Rails', 'PostgreSQL', 'APIs RESTful', 'Gitlab'],
    headerInfo: 'Pleno(até R$10,000)',
    url: 'https://programathor.com.br/jobs/29491-remoto-back-end-developer-ruby-on-rails-pleno',
  },
  {
    company: 'Loopt',
    title: 'Database Engineer Pleno',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['MySQL', 'NoSQL', 'Python', 'SQL'],
    headerInfo: 'Mínimo de 3 anos de XP(até R$10,000)',
    url: 'https://programathor.com.br/jobs/29488-database-engineer-pleno',
  },
  {
    title: 'Product Manager',
    company: 'Cora',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    url: 'https://boards.greenhouse.io/cora/jobs/6832482002',
    headerInfo: 'Pleno',
    skills: ['Gestão'],
  },
  {
    company: 'People Interactive',
    title: 'Desenvolvedor(a) Full Stack C# e React Native',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['React Native', 'C#', 'JavaScript', 'MySQL', 'MongoDB'],
    url: 'https://programathor.com.br/jobs/29480-desenvolvedor-a-full-stack-c-e-react-native-pleno',
    headerInfo: 'Pleno',
  },
  {
    title: 'Especialista em Arquitetura de Soluções AWS',
    company: 'Zup Innovation',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    url: 'https://boards.greenhouse.io/zupinnovation/jobs/5746812003',
    headerInfo: 'Pleno',
    skills: ['Microsserviços', 'Serverless', 'Python', 'Java', 'Kotlin'],
  },
  {
    title: 'Engenheira de Software BackEnd Sênior',
    company: 'Cora',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    url: 'https://boards.greenhouse.io/cora/jobs/6960033002',
    headerInfo: 'Sênior(Preferencialmente para mulheres)',
    skills: [
      'Java',
      'Kotlin',
      'Go',
      'Microsserviços',
      'Resolução de Problemas',
    ],
  },
  {
    title: 'Desenvolvedora iOS Sênior',
    company: 'Cora',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    url: 'https://boards.greenhouse.io/cora/jobs/6941604002',
    headerInfo: 'Sênior(Preferencialmente para mulheres)',
    skills: [
      'Swift',
      'View Code',
      'Persistência de Dados',
      'SOLID',
      'Testes Unitários',
    ],
  },
  {
    company: 'Impulso',
    title: 'Sênior Golang',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Golang', 'AWS', 'Kubernetes', 'Terraform', 'Helm'],
    headerInfo: 'Sênior(R$15,040 até R$20,000)',
    url: 'https://impulso.team/pt/profissionais/oportunidade/1996',
  },
  {
    company: 'Impulso',
    title: 'Sênior Reactjs',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['ReactJS', 'Docker', 'JQuery', 'HTML', 'PWA'],
    headerInfo: 'Sênior(R$15,000 até R$19,800)',
    url: 'https://impulso.team/pt/profissionais/oportunidade/1995',
  },
  {
    company: 'Impulso',
    title: 'Sênior .NET | JavaScript',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['.NET', 'JavaScript', 'Angular', 'RabbitMQ', 'Reactjs'],
    headerInfo: 'Sênior(R$15,200 até R$16,800)',
    url: 'https://impulso.team/pt/profissionais/oportunidade/1948',
  },
  {
    company: 'Impulso',
    title: 'Sênior Reactjs',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['ReactJS', 'CSS', 'Docker', 'JQuery', 'PWA'],
    headerInfo: 'Sênior(R$11,400 até R$16,800)',
    url: 'https://impulso.team/pt/profissionais/oportunidade/1991',
  },
  {
    company: 'Shark IT',
    title: 'Desenvolvedor(a) Flutter',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Flutter', 'iOS', 'Kotlin', 'Android', 'Dart'],
    headerInfo: 'Sênior(até R$15,000)',
    url: 'https://programathor.com.br/jobs/29487-desenvolvedor-a-flutter-senior',
  },
  {
    company: 'Solfácil',
    title: 'Desenvolvedor(a) Backend SR',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['API', 'JavaScript', 'Python'],
    headerInfo: 'Sênior(até R$12,000)',
    url: 'https://programathor.com.br/jobs/29467-desenvolvedor-a-backend-sr',
  },
  {
    company: 'Avantti Consultoria',
    title: 'Desenvolvedor(a) Node e Javascript Sênior',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['NoSQL', 'Golang', 'React', 'Kafka', 'Redis'],
    headerInfo: 'Sênior(R$10,000)',
    url: 'https://programathor.com.br/jobs/29475-desenvolvedor-a-node-e-javascript-senior',
  },
  {
    company: 'People Interactive',
    title: 'Desenvolvedor(a) Front-End React Native Sênior',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['React Native', 'JavaScript', 'MongoDB', 'MySQL', 'CI/CD'],
    headerInfo: 'Sênior',
    url: 'https://programathor.com.br/jobs/29479-desenvolvedor-a-front-end-react-native-senior',
  },
]

const globalOpenings: Opening[] = [
  {
    title: 'Mid-senior Full-stack Engineer - React.js, Golang',
    company: 'Strider',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    headerInfo: 'Mínimo de 3 anos de XP($4,000)',
    skills: ['React.js', 'Golang', 'Node.js'],
    url: 'app.onstrider.com/r/trampar_de_casa?job=bWlkLXNlbmlvci1mdWxsLXN0YWNrLWVuZ2luZWVyLXJlYWN0LmpzLWdvbGFuZy03NTAyMzA3MT9yZWZlcnJhbD10cmFtcGFyX2RlX2Nhc2E=',
  },
  {
    title: 'Mid-Senior Back-end Engineer - Django',
    company: 'Strider',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    headerInfo: 'Mínimo de 3 anos de XP($6,000)',
    skills: ['Python', 'Django', 'Django Rest Framework'],
    url: 'app.onstrider.com/r/trampar_de_casa?job=bWlkLXNlbmlvci1iYWNrLWVuZC1lbmdpbmVlci00NWU5N2IxZD9yZWZlcnJhbD10cmFtcGFyX2RlX2Nhc2E=',
  },
  {
    title: 'Senior Full-stack Engineer - Node.js, TypeScript',
    company: 'Strider',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    headerInfo: 'Mínimo de 4 anos de XP($40,00/hora)',
    url: 'app.onstrider.com/r/trampar_de_casa?job=c2VuaW9yLWZ1bGwtc3RhY2stZW5naW5lZXItbm9kZS5qcy10eXBlc2NyaXB0LTE5Y2QxZmZhP3JlZmVycmFsPXRyYW1wYXJfZGVfY2FzYQ==',
    skills: ['TypeScript', 'JavaScript', 'Git', 'Jira', 'Confluence'],
  },
  {
    title: 'Mid-Senior Back-end/Data Engineer',
    company: 'Strider',
    location: 'Estados Unidos',
    language: 'Inglês',
    url: 'app.onstrider.com/r/trampar_de_casa?job=bWlkLXNlbmlvci1pbmZyYXN0cnVjdHVyZS1lbmdpbmVlci1lMGUxZGE3Mz9yZWZlcnJhbD10cmFtcGFyX2RlX2Nhc2E=',
    headerInfo: 'Mínimo de 4 anos de XP(até $4,000)',
    skills: ['Python', 'Web Scraping', 'BeautifulSoup', 'Playwright'],
    currency: 'U$',
  },
  {
    title: 'Senior Mobile Engineer - Android SDK',
    company: 'Strider',
    location: 'Estados Unidos',
    language: 'Inglês',
    url: 'app.onstrider.com/r/trampar_de_casa?job=c2VuaW9yLW1vYmlsZS1lbmdpbmVlci1zZGstNTg4ZDdhMTc/cmVmZXJyYWw9dHJhbXBhcl9kZV9jYXNh',
    headerInfo: 'Mínimo de 5 anos de XP(até $6,000)',
    skills: ['iOS SDK', 'Swift', 'Android SDK', 'Java'],
    currency: 'U$',
  },
  {
    title: 'Senior Back-end Engineer - Ruby on Rails',
    company: 'Strider',
    url: 'app.onstrider.com/r/trampar_de_casa?job=c2VuaW9yLWJhY2stZW5kLWVuZ2luZWVyLXJ1Ynktb24tcmFpbHMtYTY1MTczYTc/cmVmZXJyYWw9dHJhbXBhcl9kZV9jYXNh',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    headerInfo: 'Mínimo de 5 anos de XP($6,000)',
    skills: ['Ruby on Rails', 'AWS', 'Elasticsearch', 'RDBMS'],
  },
  {
    title: 'Senior Full-stack Engineer - Django, React.js',
    company: 'Strider',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    headerInfo: 'Mínimo de 5 anos de XP($6,000)',
    skills: ['Django', 'React.js'],
    url: 'app.onstrider.com/r/trampar_de_casa?job=c2VuaW9yLWZ1bGwtc3RhY2stZW5naW5lZXItZGphbmdvLXJlYWN0LmpzLTBhOTc2MjU0MmEwMj9yZWZlcnJhbD10cmFtcGFyX2RlX2Nhc2E=',
  },
  {
    title: 'Senior iOS Developer - Swift',
    company: 'Strider',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    headerInfo: 'Mínimo de 5 anos de XP($15,00/hora)',
    skills: ['Swift', 'RESTful APIs', 'Design Patterns'],
    url: 'app.onstrider.com/r/trampar_de_casa?job=c2VuaW9yLWlvcy1kZXZlbG9wZXItc3dpZnQtYWIyNGVmOTc/cmVmZXJyYWw9dHJhbXBhcl9kZV9jYXNh',
  },
  {
    title: 'Senior DevOps Engineer',
    company: 'Strider',
    location: 'Estados Unidos',
    language: 'Inglês',
    url: 'app.onstrider.com/r/trampar_de_casa?job=c2VuaW9yLWRldm9wcy1lbmdpbmVlci0yZmM3YWQ5MT9yZWZlcnJhbD10cmFtcGFyX2RlX2Nhc2E=',
    headerInfo: 'Mínimo de 6 anos de XP(até $6,000)',
    skills: ['CI/CD', 'Linux', 'Redis', 'OVH Cloud'],
    currency: 'U$',
  },
  {
    title: 'Senior Machine Learning Engineer',
    company: 'Strider',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    headerInfo: 'Mínimo de 6 anos de XP($6,000)',
    skills: ['Deep Learning', 'Computer Vision', 'Machine Learning', 'Python'],
    url: 'https://app.onstrider.com/r/trampar_de_casa?job=c2VuaW9yLW1hY2hpbmUtbGVhcm5pbmctZW5naW5lZXItZTUzMDIyZDc/cmVmZXJyYWw9dHJhbXBhcl9kZV9jYXNh',
  },
  {
    title: 'Senior Back-end Engineer - Python, SQL',
    company: 'Strider',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    headerInfo: 'Mínimo de 6 anos de XP($6,000)',
    skills: ['Python', 'SQL'],
    url: 'app.onstrider.com/r/trampar_de_casa?job=c2VuaW9yLWJhY2stZW5kLWVuZ2luZWVyLXB5dGhvbi1zcWwtYWE3NmNmNTQ/cmVmZXJyYWw9dHJhbXBhcl9kZV9jYXNh',
  },
  {
    title: 'Lead Data Scientist',
    company: 'Strider',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    headerInfo: 'Mínimo de 6 anos de XP($6,000)',
    skills: ['Generative AI'],
    url: 'app.onstrider.com/r/trampar_de_casa?job=bGVhZC1kYXRhLXNjaWVudGlzdC1kOGViNmJjYT9yZWZlcnJhbD10cmFtcGFyX2RlX2Nhc2E=',
  },
  {
    title: 'Senior Back-end Engineer',
    company: 'Strider',
    location: 'Estados Unidos',
    language: 'Inglês',
    url: 'app.onstrider.com/r/trampar_de_casa?job=c2VuaW9yLWJhY2stZW5kLWVuZ2luZWVyLWdvLXJ1c3QtcHl0aG9uLWMtMGE5MGQxM2E/cmVmZXJyYWw9dHJhbXBhcl9kZV9jYXNh',
    headerInfo: 'Mínimo de 7 anos de XP(até $7,000)',
    skills: ['Golang', 'Rust', 'Python', 'C++', 'Web3'],
    currency: 'U$',
  },
  {
    title: 'Frontend Engineer, Near.org Developer Experience',
    company: 'Pagoda',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    url: 'https://wellfound.com/jobs/2821784-frontend-engineer-near-org-developer-experience?utm_campaign=startup_share&utm_content=startup_share_module&utm_medium=social&utm_term=pagodaco',
    headerInfo: 'Pleno($12,416 até $14,583)',
    skills: ['Typescript', 'Javascript', 'CSS'],
  },
  {
    title: 'Javascript Engineer',
    company: 'MindCloud',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    url: 'https://wellfound.com/jobs/2437692-javascript-engineer?utm_campaign=startup_share&utm_content=startup_share_module&utm_medium=social&utm_term=mindcloud-1',
    headerInfo: 'Pleno($4,583 até $5,833)',
    skills: [
      'Node.js',
      'Javascript',
      'API Integration',
      'Data Transformations',
      'Web Basics',
    ],
  },
  {
    title: 'Account Manager at a Fast-Growing Amazon Agency',
    company: 'AMZ Clever',
    location: 'Global',
    language: 'Inglês',
    url: 'https://dynamitejobs.com/apply/OxPW0FcwFAT4oDTQLSPK',
    headerInfo: 'Pleno($3,333 até $4,583)',
    skills: ['Amazon Account Management', 'Amazon Ads', 'Project Management'],
    currency: 'U$',
    salary: '$40k - $55k por ano',
  },
  {
    title: 'Frontend Developer',
    company: 'Quinncia',
    location: 'Global',
    language: 'Inglês',
    currency: 'U$',
    url: 'https://wellfound.com/jobs/1029763-frontend-developer?utm_campaign=startup_share&utm_content=startup_share_module&utm_medium=social&utm_term=quinncia',
    headerInfo: 'Pleno($2,083 até $3,750)',
    skills: ['TypeScript', 'Next.js', 'Jest', 'Webpack', 'GraphQL'],
  },
  {
    title: 'WordPress Developer (Dynamic Content Specialist)',
    company: 'Smart Apartment Data',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    url: 'https://wellfound.com/jobs/2799521-wordpress-developer-dynamic-content-specialist?utm_campaign=startup_share&utm_content=startup_share_module&utm_medium=social&utm_term=smart-apartment-data-1',
    headerInfo: 'Pleno($2,500 até $3,500)',
    skills: ['WordPress', 'HTML', 'CSS', 'JavaScript'],
  },
  {
    title: 'Full Stack Developer (Laravel/Vue.js)',
    company: 'Zen Projects',
    location: 'Global',
    language: 'Inglês',
    url: 'https://dynamitejobs.com/apply/G4AQP3es1Mup6bRZTZrB',
    headerInfo: 'Mínimo de 3 anos de XP',
    skills: ['Laravel', 'Vue.js', 'Git', 'GitHub', 'Figma'],
    currency: 'U$',
  },
  {
    title: 'Paid Social Manager',
    company: 'Giant Propeller',
    location: 'América Latina',
    language: 'Inglês',
    url: 'https://dynamitejobs.com/apply/AOtUfdJRlX6eFEGmocgc',
    headerInfo: 'Pleno',
    skills: ['Meta', 'TikTok', 'LinkedIn', 'Twitter', 'B2C'],
    currency: 'U$',
  },
  {
    title: 'Senior Frontend Engineer',
    company: 'Salespeak',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    url: 'https://wellfound.com/jobs/2697171-senior-frontend-engineer?utm_campaign=startup_share&utm_content=startup_share_module&utm_medium=social&utm_term=salespeak-ai',
    headerInfo: 'Sênior($7,500 até $10,000)',
    skills: ['JavaScript', 'ReactJS', 'Cloud', 'UI', 'Collaboration'],
  },
  {
    title: 'Senior Backend Developer - PHP/Node.js',
    company: 'Sequencing',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    url: 'https://wellfound.com/jobs/2819090-senior-backend-developer-php-node-js?utm_campaign=startup_share&utm_content=startup_share_module&utm_medium=social&utm_term=sequencing',
    headerInfo: 'Sênior($6,250 até $10,000)',
    skills: ['PHP', 'Node.js', 'Stripe API', 'MySQL', 'API Integration'],
  },
  {
    title: 'Senior Magento Developer',
    company: 'Proxify',
    location: 'Global',
    language: 'Inglês',
    currency: 'U$',
    url: 'https://career.proxify.io/apply?utm_source=remotive&utm_medium=job_posting&utm_campaign=senior_magento',
    headerInfo: 'Mínimo de 5 anos de XP',
    skills: ['Magento II', 'JavaScript', 'PHP', 'CSS', 'MySQL'],
  },
]

export const openings20231011: Openings = {
  localOpenings,
  globalOpenings,
}
;(async () => {
  await Promise.all([
    await saveOpenings(globalOpenings, Topics.INTERNATIONAL_VACANCIES),
    await saveOpenings(localOpenings, Topics.NATIONAL_VACANCIES),
  ])
})()
