export const programmingLangsAndTechnologies = [
      "PHP",
      "HTML",
      "CSS",
      "Node",
      "JavaScript",
      "Python",
      "Java",
      "C#",
      "C++",
      "Ruby",
      "Swift",
      "Flutter",
      "Dart",
      "Kotlin",
      "TypeScript",
      "React",
      "React-native",
      "Angular",
      "Vue.js",
      "Express.js",
      "Django",
      "Ruby on Rails",
      "Spring Boot",
      "ASP.NET",
      "Laravel",
      "Flask",
      "MySQL",
      "PostgreSQL",
      "MongoDB",
      "SQLite",
      "Redis",
      "Oracle",
      "SQL Server",
      "Firebase",
      "Cassandra",
      "Elasticsearch",
      "Docker"
]
  