import { Opening } from 'shared/src/email/openings-email/Opening'
import { Openings } from '../Openings'

const localOpenings: Opening[] = []

const globalOpenings: Opening[] = [
  {
    company: 'Meteor Software',
    title: 'DevOps Engineer',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: [
      'AWS',
      'Kubernetes',
      'Terraform',
      'Observability',
      'ShellScripting',
    ],
    headerInfo: 'Pleno (até $3,500)',
    url: 'https://public.app.shortcut.com/62/meteor-software/docs/33M0mvrlVcqjX85UO74Hdl/devops-engineer',
  },
  {
    company: 'Strider',
    title: 'Engenheiro Full-Stack Pleno - Angular.js',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Angular.js', 'POO', 'TypeScript', 'JavaScript'],
    headerInfo: 'Mínimo de 3 anos de XP',
    url: '',
  },
  {
    company: 'Strider',
    title: 'Mid-Senior Full-stack Engineer - Spring Boot, React.js',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Java', 'SpringBoot', 'React.js'],
    headerInfo: 'Mínimo de 4 anos de XP',
    url: 'app.onstrider.com/r/trampar_de_casa?job=bWlkLXNlbmlvci1mdWxsLXN0YWNrLWVuZ2luZWVyLXNwcmluZy1ib290LXJlYWN0LmpzLWIxYWJmMTM3P3JlZmVycmFsPXRyYW1wYXJfZGVfY2FzYQ==',
  },
  {
    company: 'Strider',
    title: 'Full-stack Engineer - Node.js, Vue.js',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Node.js', 'Vue.js'],
    headerInfo: 'Mínimo de 4 anos de XP',
    url: 'app.onstrider.com/r/trampar_de_casa?job=ZnVsbC1zdGFjay1lbmdpbmVlci1ub2RlLmpzLXZ1ZS5qcy0wOGJlYWI3MT9yZWZlcnJhbD10cmFtcGFyX2RlX2Nhc2E=',
  },
  {
    company: 'Strider',
    title: 'Senior Data Engineer',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Python', 'AWS', 'Azure', 'Airflow', 'Databricks'],
    headerInfo: 'Mínimo de 5 anos de XP',
    url: 'app.onstrider.com/r/trampar_de_casa?job=c2VuaW9yLWRhdGEtZW5naW5lZXItNWM0YzQ2YjQ/cmVmZXJyYWw9dHJhbXBhcl9kZV9jYXNh',
  },
  {
    company: 'Strider',
    title: 'Software Developer, Audio',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['C++', 'Juce'],
    headerInfo: 'Mínimo de 5 anos de XP',
    url: 'app.onstrider.com/r/trampar_de_casa?job=c29mdHdhcmUtZGV2ZWxvcGVyLWF1ZGlvLTFiOGMzM2U3P3JlZmVycmFsPXRyYW1wYXJfZGVfY2FzYQ==',
  },
  {
    title: 'Product Designer',
    company: 'Strider',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    headerInfo: 'Mínimo de 7 anos de XP',
    skills: ['UI', 'UX', 'Comunicação'],
    url: 'app.onstrider.com/r/trampar_de_casa?job=cHJvZHVjdC1kZXNpZ25lci1kN2VkMmJhOT9yZWZlcnJhbD10cmFtcGFyX2RlX2Nhc2E=',
  },
  {
    company: 'StarTree',
    title: 'Full Stack Web Developer',
    location: 'Global',
    language: 'Inglês',
    currency: 'U$',
    skills: ['CI/CD', 'FullStack', 'Next.js', 'React.js', 'TypeScript'],
    headerInfo: 'Mínimo de 3 anos de XP',
    url: 'https://boards.greenhouse.io/startree/jobs/4928144004',
    //https://dynamitejobs.com/company/startree/remote-job/full-stack-web-developer-1
  },
  {
    company: 'TrustSwap',
    title: 'Front-End Engineer for DeFi company',
    location: 'Global',
    language: 'Inglês',
    currency: 'U$',
    skills: ['FrontEnd', 'JavaScript', 'Next.js', 'TypeScript', 'UI'],
    headerInfo: 'Mínimo de 3 anos de XP($3,750 até $5,833)',
    url: 'https://trustswap.com/front-end-engineer-for-defi-company/',
    //https://dynamitejobs.com/company/trustswap/remote-job/front-end-engineer-for-defi-company
  },
  {
    company: 'Binance',
    title: 'Golang Developer',
    location: 'Global',
    language: 'Inglês',
    currency: 'U$',
    skills: ['AWS', 'Azure', 'Blockchain', 'NoSQL', 'Rust'],
    headerInfo: 'Mínimo de 4 anos de XP',
    url: 'https://jobs.lever.co/binance/47df46fd-6a1e-4304-b758-662f8b711e59',
    //https://dynamitejobs.com/company/binance/remote-job/golang-developer
  },
  {
    company: 'Deepgram',
    title: 'Backend Software Engineer',
    location: 'Global',
    language: 'Inglês',
    currency: 'U$',
    skills: ['C/C++', 'Design', 'Python', 'Rust', 'Unix'],
    headerInfo: 'Mínimo de 5 anos de XP($10,000 até $16,666)',
    url: 'https://jobs.ashbyhq.com/Deepgram/aa0687e8-b8ac-4f9e-abaa-617989db4026',
    //https://dynamitejobs.com/company/deepgram/remote-job/backend-software-engineer-1
  },
  {
    company: 'Dforth Technlogies',
    title: 'Senior Data Engineer (GCP)',
    location: 'Global',
    language: 'Inglês',
    salary: '$30k - $40k',
    skills: ['Python', 'GoogleBigquery', 'Looker', 'GCP'],
    currency: 'U$',
    headerInfo: 'Mínimo de 5 anos de XP',
    url: 'https://wellfound.com/company-l/dforth-technlogies/jobs/2771573-senior-data-engineer-gcp?autoOpenApplication=true',
  },
  {
    company: 'Flylance',
    title: 'Sr. React Engineer',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['React', 'TypeScript', 'Material UI'],
    headerInfo: 'Sênior',
    url: 'https://www.flylance.com/role?id=recMaDly969lDSw7G',
  },
  {
    company: 'Odyssey Interactive',
    title: 'Engenheiro Sênior de Gameplay (C++ / Unreal)',
    location: 'Global',
    language: 'Inglês',
    currency: 'U$',
    skills: ['C++', 'UnrealEngine', 'GameplaySystems', 'Low-level'],
    headerInfo: 'Mínimo de 6 anos de XP',
    url: 'https://jobs.smartrecruiters.com/OdysseyInteractive/743999919264080-senior-gameplay-engineer-c-unreal-remote-',
    // https://remotive.com/remote-jobs/software-dev/senior-gameplay-engineer-c-unreal-1759137
  },
  {
    company: 'Terminal49',
    title: 'Senior Back End Engineer (Ruby on Rails)',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['AWS', 'Backend', 'PostgreSQL', 'RubyOnRails', 'SQL'],
    headerInfo: 'Sênior ($11,666 até $16,666)',
    url: 'https://apply.workable.com/terminal49/j/466F7DD66B/',
    //https://dynamitejobs.com/company/terminal49/remote-job/senior-back-end-engineer-ruby-on-rails
  },
]

export const openings20230823: Openings = {
  localOpenings,
  globalOpenings,
}
