import { saveOpenings } from 'db'
import { Topics } from 'shared'
import { Opening } from 'shared/src/email/openings-email/Opening'
import { Openings } from '../Openings'

const localOpenings: Opening[] = [
  {
    title: 'Desenvolvedor Pleno (.NET | JavaScript)',
    company: 'Impulso',
    location: 'Brasil',
    language: 'Português',
    url: 'https://impulso.team/pt/profissionais/oportunidade/1947',
    headerInfo: 'Pleno (R$12,000 até R$13,600)',
    skills: ['.NET', 'JavaScript', 'Postgres', 'RabbitMQ', 'React'],
    currency: 'R$',
  },
  {
    title: 'Pleno Backend Golang',
    company: 'Impulser Professional',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    salary: 'R$ 11.400 - R$ 16.800',
    url: 'https://impulso.team/pt/profissionais/oportunidade/1991',
    headerInfo: 'Pleno (R$11,400 até R$16,800)',
    skills: ['Go', 'Docker', 'Kubernetes'],
  },
  {
    title: 'Pleno/Sênior Funcional de Salesforce',
    company: 'Impulso',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    salary: 'R$ 12.000 - R$ 20.800',
    url: 'URL do Anúncio de Emprego (se disponível)',
    headerInfo: 'Pleno/Sênior (R$12,000 até R$20,800)',
    skills: ['Salesforce', 'GitHub', 'Kanban', 'Scrum'],
  },
  {
    company: 'Capco',
    title: 'QA Analyst',
    location: 'Brasil',
    language: 'Inglês',
    currency: 'R$',
    skills: ['Java', 'Maven', 'Selenium', 'TestNG Testing', 'Git'],
    headerInfo: 'Pleno',
    url: 'https://boards.greenhouse.io/capco/jobs/5447152',
  }, // https://remotar.com.br/job/27842/capco/analista-de-qa-(testes-automatizados)
  {
    title: 'Sênior Data Engineering',
    company: 'Impulso',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    salary: 'R$ 16.800 - R$ 22.240',
    url: 'https://impulso.team/pt/profissionais/oportunidade/1989',
    headerInfo: 'Sênior (R$16,800 até R$22,240)',
    skills: ['Python', 'AWS', 'SQL'],
  },
  {
    title: 'Arquiteto de Software Sênior',
    company: 'Impulso',
    location: 'Brasil',
    language: 'Português',
    url: 'https://impulso.team/pt/profissionais/oportunidade/1953',
    headerInfo: 'Sênior (R$15,200 até R$17,120)',
    skills: ['Angular', 'AWS', 'Django', 'JavaScript', 'Kafka'],
    currency: 'R$',
  },
  {
    title: 'Desenvolvedor Sênior (.NET | JavaScript)',
    company: 'Impulso',
    location: 'Brasil',
    language: 'Português',
    url: 'https://impulso.team/pt/profissionais/oportunidade/1948',
    headerInfo: 'Sênior (R$15,200 até R$16,800)',
    currency: 'R$',
    skills: ['.NET', 'JavaScript', 'Postgres', 'RabbitMQ', 'React'],
  },
  {
    title: 'Sênior Golang',
    company: 'Impulso',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    salary: 'R$ 15.040 - R$ 20.000',
    url: 'https://impulso.team/pt/profissionais/oportunidade/1996',
    headerInfo: 'Sênior (R$15,040 até R$20,000)',
    skills: ['Go', 'AWS', 'Kubernetes', 'Terraform'],
  },
  {
    title: 'Sênior ReactJS',
    company: 'Impulso',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    salary: 'R$ 15.000 - R$ 19.800',
    url: 'https://impulso.team/pt/profissionais/oportunidade/1995',
    headerInfo: 'Sênior (R$15,000 até R$19,800)',
    skills: ['React', 'CSS', 'Docker', 'JavaScript', 'Jest'],
  },
  {
    company: 'Verzel',
    title: 'Desenvolvedor(a) Back-End Especialista',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Python', 'Django', 'SQL', 'Docker', 'AWS Lambda'],
    headerInfo: 'Sênior (até R$15,000)',
    url: 'https://programathor.com.br/jobs/29516-desenvolvedor-a-back-end-especialista',
  },
  {
    title: 'Sênior Golang',
    company: 'Impulso',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    salary: 'R$ 13.200 - R$ 18.700',
    url: 'https://impulso.team/pt/profissionais/oportunidade/1992',
    headerInfo: 'Sênior (R$13,200 até R$18,700)',
    skills: ['Golang', 'Docker', 'Kubernetes', 'AWS', 'Tests'],
  },
  {
    title: 'Tech Lead Frontend Software Engineer I',
    company: 'Gympass',
    location: 'Brasil',
    currency: 'R$',
    language: 'Inglês',
    skills: ['React', 'TypeScript'],
    url: 'https://boards.greenhouse.io/gympass/jobs/6687524002',
    headerInfo: 'Sênior',
  }, // https://remotar.com.br/job/27807/gympass/tech-lead-frontend-software-engineer
  {
    company: 'Gympass',
    title: 'Staff Backend Software Engineer I Tagus',
    location: 'Brasil',
    language: 'Inglês',
    currency: 'R$',
    skills: ['Go', 'Java', 'Kotlin', 'Scala', 'Python'],
    headerInfo: 'Sênior',
    url: 'https://boards.greenhouse.io/gympass/jobs/6943904002',
  }, // https://remotar.com.br/job/27808/gympass/staff-backend-software-engineer
  {
    company: 'Proprli',
    title: 'UX/UI Designer Sênior',
    location: 'Brasil',
    language: 'Inglês',
    currency: 'R$',
    skills: ['SaaS', 'UX Design', 'UI Design'],
    headerInfo: 'Sênior',
    url: 'https://vagas.byintera.com/home/proprli-carreiras/',
  }, // https://remotar.com.br/job/27873/proprli/uxui-designer-sr
  {
    company: 'Proprli',
    title: 'Front-End Developer Sênior',
    location: 'Brasil',
    language: 'Inglês',
    currency: 'R$',
    skills: ['JavaScript', 'HTML', 'CSS', 'Webpack', 'Babel'],
    headerInfo: 'Sênior',
    url: 'https://vagas.byintera.com/home/proprli-carreiras/',
  }, // https://remotar.com.br/job/27874/proprli/front-end-developer-sr
  {
    company: 'Proprli',
    title: 'Senior Backend Developer',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Postgres', 'PHP'],
    headerInfo: 'Sênior',
    url: 'https://vagas.byintera.com/home/proprli-carreiras/',
  }, // https://remotar.com.br/job/27875/proprli/senior-backend-developer
]

const globalOpenings: Opening[] = [
  {
    company: 'Strider',
    title: 'Mid-senior Full-stack Engineer',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['React', 'Go', 'Node'],
    headerInfo: 'Mínimo de 3 anos de XP(até $4,000)',
    url: 'https://app.onstrider.com/r/trampar_de_casa?job=bWlkLXNlbmlvci1mdWxsLXN0YWNrLWVuZ2luZWVyLXJlYWN0LmpzLWdvbGFuZy03NTAyMzA3MT9yZWZlcnJhbD10cmFtcGFyX2RlX2Nhc2E=',
  },
  {
    company: 'Strider',
    title: 'Mid-Senior Back-end Engineer - Django',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Python', 'Django'],
    headerInfo: 'Mínimo de 4 anos de XP(até $6,000)',
    url: 'app.onstrider.com/r/trampar_de_casa?job=bWlkLXNlbmlvci1iYWNrLWVuZC1lbmdpbmVlci00NWU5N2IxZD9yZWZlcnJhbD10cmFtcGFyX2RlX2Nhc2E=',
  },
  {
    company: 'Strider',
    title: 'Senior Full-stack Engineer',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Node', 'TypeScript', 'JavaScript'],
    headerInfo: 'Mínimo de 4 anos de XP(até $20/hora)',
    url: 'https://app.onstrider.com/r/trampar_de_casa?job=c2VuaW9yLWZ1bGwtc3RhY2stZW5naW5lZXItbm9kZS5qcy10eXBlc2NyaXB0LTE5Y2QxZmZhP3JlZmVycmFsPXRyYW1wYXJfZGVfY2FzYQ==',
  },
  {
    company: 'Strider',
    title: 'Senior Back-end/Data Engineer',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Python', 'AWS', 'Postgres', 'Terraform'],
    headerInfo: 'Mínimo de 5 anos de XP(até $6,000)',
    url: 'https://app.onstrider.com/r/trampar_de_casa?job=c2VuaW9yLWJhY2stZW5kLWRhdGEtZW5naW5lZXItcHl0aG9uLXN0cmlkZXItMmI2MjQzNjM/cmVmZXJyYWw9dHJhbXBhcl9kZV9jYXNh',
  },
  {
    company: 'Strider',
    title: 'Senior Mobile Engineer',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['iOS Development', 'Swift', 'Android Development', 'Java'],
    headerInfo: 'Mínimo de 5 anos de XP(até $6,000)',
    url: 'https://app.onstrider.com/r/trampar_de_casa?job=c2VuaW9yLW1vYmlsZS1lbmdpbmVlci1zZGstNTg4ZDdhMTc/cmVmZXJyYWw9dHJhbXBhcl9kZV9jYXNh',
  },
  {
    company: 'Strider',
    title: 'Senior Back-end Engineer',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Ruby on Rails', 'AWS', 'Elasticsearch'],
    headerInfo: 'Mínimo de 5 anos de XP(até $6,000)',
    url: 'https://app.onstrider.com/r/trampar_de_casa?job=c2VuaW9yLWJhY2stZW5kLWVuZ2luZWVyLXJ1Ynktb24tcmFpbHMtYTY1MTczYTc/cmVmZXJyYWw9dHJhbXBhcl9kZV9jYXNh',
  },
  {
    company: 'Strider',
    title: 'Senior iOS Developer - Swift',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Swift'],
    headerInfo: 'Mínimo de 5 anos de XP(até $15/hora)',
    url: 'https://app.onstrider.com/r/trampar_de_casa?job=c2VuaW9yLWlvcy1kZXZlbG9wZXItc3dpZnQtYWIyNGVmOTc/cmVmZXJyYWw9dHJhbXBhcl9kZV9jYXNh',
  },
  {
    company: 'Strider',
    title: 'Senior DevOps Engineer',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['CI', 'CD', 'Linux', 'Redis'],
    headerInfo: 'Mínimo de 6 anos de XP(até $6,000)',
    url: 'https://app.onstrider.com/r/trampar_de_casa?job=c2VuaW9yLWRldm9wcy1lbmdpbmVlci0yZmM3YWQ5MT9yZWZlcnJhbD10cmFtcGFyX2RlX2Nhc2E=',
  },
  {
    company: 'Strider',
    title: 'Senior Back-end Engineer',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Python', 'SQL'],
    headerInfo: 'Mínimo de 6 anos de XP(até $6,000)',
    url: 'https://app.onstrider.com/r/trampar_de_casa?job=YXBwLm9uc3RyaWRlci5jb20vci90cmFtcGFyX2RlX2Nhc2E/am9iPWMyVnVhVzl5TFdKaFkyc3RaVzVrTFdWdVoybHVaV1Z5TFhCNWRHaHZiaTF6Y1d3dFlXRTNObU5tTlRRJTJGY21WbVpYSnlZV3c5ZEhKaGJYQmhjbDlrWlY5allYTmgmcmVmZXJyYWw9dHJhbXBhcl9kZV9jYXNh',
  },
  {
    company: 'Strider',
    title: 'Senior Machine Learning Engineer',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Deep Learning', 'Computer Vision', 'Machine Learning', 'Python'],
    headerInfo: 'Mínimo de 6 anos de XP(até $6,000)',
    url: 'https://app.onstrider.com/r/trampar_de_casa?job=c2VuaW9yLW1hY2hpbmUtbGVhcm5pbmctZW5naW5lZXItZTUzMDIyZDc/cmVmZXJyYWw9dHJhbXBhcl9kZV9jYXNh',
  },
  {
    company: 'Strider',
    title: 'Lead Data Scientist',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['AI'],
    headerInfo: 'Mínimo de 6 anos de XP(até $6,000)',
    url: 'https://app.onstrider.com/r/trampar_de_casa?job=bGVhZC1kYXRhLXNjaWVudGlzdC1kOGViNmJjYT9yZWZlcnJhbD10cmFtcGFyX2RlX2Nhc2E=',
  },
  {
    company: 'Strider',
    title: 'Senior Full-stack Engineer',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Django', 'React'],
    headerInfo: 'Mínimo de 6 anos de XP(até $5,000)',
    url: 'https://app.onstrider.com/r/trampar_de_casa?job=c2VuaW9yLWZ1bGwtc3RhY2stZW5naW5lZXItZGphbmdvLXJlYWN0LmpzLTBhOTc2MjU0MmEwMj9yZWZlcnJhbD10cmFtcGFyX2RlX2Nhc2E=',
  },
  {
    company: 'Strider',
    title: 'Senior Back-end Engineer',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Go', 'Rust', 'Python', 'C++', 'Web3'],
    headerInfo: 'Mínimo de 7 anos de XP(até $7,000)',
    url: 'https://app.onstrider.com/r/trampar_de_casa?job=c2VuaW9yLWJhY2stZW5kLWVuZ2luZWVyLWdvLXJ1c3QtcHl0aG9uLWMtMGE5MGQxM2E/cmVmZXJyYWw9dHJhbXBhcl9kZV9jYXNh',
  },
  {
    company: 'Planned 5D',
    title: 'iOS Developer',
    location: 'Polônia',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Swift', 'Objective-C', 'iOS Development', 'CI', 'CD'],
    headerInfo: 'Pleno',
    url: 'https://jobs.lever.co/planner5d/5892d7bf-1448-43d7-a737-c78a6af4a33f',
  },
]

export const openings20231011: Openings = {
  localOpenings,
  globalOpenings,
}
;(async () => {
  await Promise.all([
    await saveOpenings(globalOpenings, Topics.INTERNATIONAL_VACANCIES),
    await saveOpenings(localOpenings, Topics.NATIONAL_VACANCIES),
  ])
})()
