import { Opening } from 'shared/src/email/openings-email/Opening'
import { striderOpening } from 'shared/src/email/openings-email/striderOpening'
import { Openings } from '../Openings'

const localJrOpenings: Opening[] = [
  {
    company: 'Codecycle',
    title: 'Desenvolvedor(a) .Net (C#) Júnior',
    location: 'Brasil',
    language: 'Português',
    currency: 'BRL',
    salary: 'Até R$4.000',
    skills: ['C#', '.NET', 'SQLServer', 'Angular', 'API'],
    headerInfo: 'Júnior (R$4.000)',
    url: 'https://programathor.com.br/jobs/29015-desenvolvedor-a-net-c-junior',
  },
  {
    url: 'https://www.klutch.com.br/vagas/desenvolvedor-react-junior',
    company: 'Klutch Tecnologia',
    title: 'Desenvolvedor(a) React Front-End',
    location: 'Brasil',
    currency: 'BRL',
    salary: 'from R$ 0,00 to R$ 0,00 BRL/monthly',
    headerInfo: 'Júnior',
    language: 'Inglês',
    skills: ['HTML', 'CSS', 'React'],
  },
  {
    company: 'Dock',
    title: 'Junior Software Engineer (Java - Authorization)',
    location: 'Brasil',
    language: 'Português',
    currency: 'BRL',
    skills: ['Java 8+', 'Spring Boot', 'Banco de dados SQL Server', 'Linux'],
    headerInfo: 'Júnior',
    url: 'https://dock.gupy.io/job/eyJzb3VyY2UiOiJndXB5X3B1YmxpY19wYWdlIiwiam9iSWQiOjQ4OTUyMDF9',
  },
  {
    company: 'Serasa Experian',
    title: 'Desenvolvedor(a) iOS Jr',
    location: 'Brasil',
    language: 'Português',
    currency: 'BRL',
    salary: 'Not specified',
    skills: ['Swift', 'Git', 'Storyboard', 'Mobile'],
    headerInfo: 'Júnior',
    url: 'https://jobs.smartrecruiters.com/Experian/743999914424554-desenvolvedor-a-ios-jr',
  },
  {
    company: 'Nuuvem',
    title: 'Desenvolvedor Bubble Jr',
    location: 'Brasil',
    language: 'Português',
    currency: 'BRL',
    salary: 'R$5.100 a R$6.000',
    skills: ['Bubble', 'HTML', 'CSS', 'JavaScript'],
    headerInfo: 'Júnior (R$5.000 a R$6.000)',
    url: 'https://careers.nuuvem.com/o/desenvolvedor-bubble-jr-1',
  },
  {
    company: 'Knewin',
    title: 'Pessoa Desenvolvedora Java Fullstack (Júnior)',
    location: 'Brasil',
    language: 'Português',
    currency: 'BRL',
    salary: 'Not specified',
    skills: ['Java', 'Javascript', 'Typescript', 'Nodejs', 'SQL'],
    headerInfo: 'Júnior',
    url: 'https://knewin.gupy.io/job/eyJzb3VyY2UiOiJndXB5X3B1YmxpY19wYWdlIiwiam9iSWQiOjUwMzk4MjN9',
  },
  {
    company: 'Celcoin',
    title: 'Administrador de Banco de dados Jr',
    location: 'Barueri - SP',
    language: 'Português',
    currency: 'BRL',
    skills: ['Curso Superior', 'SQL', 'ETL'],
    headerInfo: 'Júnior',
    url: 'https://celcoin.gupy.io/job/eyJqb2JJZCI6NDk2OTE5Nywic291cmNlIjoibGlua2VkaW4ifQ==',
  },
  {
    company: 'Melhor Escolha',
    title: 'Analista de Testes Júnior',
    location: 'Brasil',
    language: 'Português',
    currency: 'BRL',
    salary: 'Até R$3.500',
    skills: [
      'CSS',
      'JavaScript',
      'HTML',
      'Testes Automatizados',
      'Testes Regressão',
    ],
    headerInfo: 'Júnior (R$3.500)',
    url: 'https://programathor.com.br/jobs/28976-analista-de-testes-junior-100-remoto',
  },
]

const localOpenings: Opening[] = [
  {
    company: 'Going2 Corporation S/A',
    title: 'Dev. Front-end Pleno Mobile (React Native)',
    location: 'Sorocaba / SP',
    language: 'Português',
    currency: 'BRL',
    skills: [
      'React Native',
      'CI/CD',
      'Arquitetura',
      'Firebase',
      'Banco de dados offline',
      'Notificações por push',
    ],
    headerInfo: 'Pleno',
    url: 'https://going2.solides.jobs/vacancies/269146',
  },
  {
    url: 'https://careers.nuuvem.com/o/fullstack-web-developer-ruby',
    company: 'Nuuvem',
    title: 'Full-Stack Web Developer (Ruby)',
    currency: 'BRL',
    salary: 'from R$ 7.500,00 to R$ 15.000,00 BRL/monthly',
    location: 'Rio de Janeiro',
    language: 'Português',
    skills: ['HTML', 'CSS', 'Node', 'JavaScript', 'Python'],
    headerInfo: 'Mínimo de 3 anos de XP (R$ 7.500 a R$ 13.000)',
  },
  {
    url: 'https://programathor.com.br/jobs/28981-desenvolvedor-a-de-software-pleno',
    company: 'ProgramaThor',
    title: 'Desenvolvedor(a) de Software Pleno',
    currency: 'BRL',
    salary: 'from R$ 8.000,00 to R$ 8.000,00 BRL/monthly',
    headerInfo: 'Pleno (até R$ 8.000)',
    language: 'Inglês',
    skills: ['HTML', 'CSS', 'Python', 'Java', 'C++'],
    location: 'Brasil',
  },

  {
    url: 'https://programathor.com.br/jobs/28983-desenvolvedor-a-react-pleno',
    company: 'ProgramaThor',
    title: 'Desenvolvedor(a) React Pleno',
    currency: 'BRL',
    salary: 'from R$ 8.000,00 to R$ 8.000,00 BRL/monthly',
    location: 'Brasil',
    headerInfo: 'Pleno (até R$ 8.000,00)',
    language: 'Português',
    skills: ['CSS', 'JavaScript', 'Java', 'TypeScript', 'React'],
  },
  {
    url: 'https://jobs.quickin.io/ucondo/jobs/649c2db133769e001a3fa28b',
    company: 'uCondo',
    location: 'Brasil',
    title: 'Product Designer Sênior',
    currency: 'BRL',
    headerInfo: 'Sênior (R$ 7.000 a R$ 9.000)',
    language: 'Português',
    skills: ['Formação em UI/UX', 'Design System', 'Temas Saas'],
  },
  {
    company: 'JFOX',
    title: 'Gerente de Projetos Salesforce Pleno',
    location: 'Nova Lima - MG',
    language: 'Português',
    currency: 'BRL',
    skills: [
      'Gerenciamento de Projetos',
      'Scrum',
      'Salesforce',
      'Comunicação',
      'Liderança',
    ],
    headerInfo: 'Pleno',
    url: 'https://www.careerjet.com.br/jobad/br7869c519287010ac8c7e4ec176cad9e3',
  },
  {
    company: 'Welkron Pensamento',
    title: 'Pessoa Desenvolvedora PHP (Remoto)',
    location: 'Porto Alegre-RS',
    language: 'Português',
    currency: 'BRL',
    skills: [
      'PHP 7+',
      'Laravel',
      'SQL',
      'MySQL',
      'NoSQL',
      'MongoDB',
      'API REST',
      'Git',
    ],
    headerInfo: 'Pleno',
    url: 'https://vagas.empregos.com.br/vaga/8778745/pessoa-desenvolvedora-php-remoto-em-porto-alegre-rs',
  },
  {
    company: 'Zup Innovation',
    title: 'Senior Front-End Developer | Angular',
    location: 'Remoto',
    language: 'Português',
    currency: 'BRL',
    skills: ['Angular', 'AWS'],
    headerInfo: 'Sênior',
    url: 'https://boards.greenhouse.io/zupinnovation/jobs/5559469003',
  },
]

const globalPartnerCompanies: Opening[] = [
  {
    company: 'Meteor Software',
    title: 'DevOps Engineer',
    location: 'Remoto',
    language: 'Inglês',
    currency: 'USD',
    skills: ['AWS', 'Docker', 'Kubernetes', 'Terraform', 'Linux'],
    headerInfo: 'Júnior a Pleno ($2,000 a $3,500)',
    url: 'https://public.app.shortcut.com/62/meteor-software/docs/33M0mvrlVcqjX85UO74Hdl/devops-engineer',
  },
  striderOpening(
    'Mid-level Scraping Engineer - Python',
    3,
    'app.onstrider.com/r/trampar_de_casa?job=bWlkLWxldmVsLXNjcmFwaW5nLWVuZ2luZWVyLXB5dGhvbi03NjhiOTdhYz9yZWZlcnJhbD10cmFtcGFyX2RlX2Nhc2E=',
    ['Python', 'Playwright', 'HTML'],
    'U$ 4,000 a U$ 6,200'
  ),
  striderOpening(
    'Product Designer',
    3,
    'app.onstrider.com/r/trampar_de_casa?job=cHJvZHVjdC1kZXNpZ25lci1kN2VkMmJhOT9yZWZlcnJhbD10cmFtcGFyX2RlX2Nhc2E=',
    ['Design for Web', 'UI/UX', 'Data Visualization'],
    'U$ 6,300 a U$ 10,000'
  ),
  striderOpening(
    'Database Administrator',
    4,
    'app.onstrider.com/r/trampar_de_casa?job=c2VuaW9yLWRiYS1tc3NxbC04NjM3MThkMz9yZWZlcnJhbD10cmFtcGFyX2RlX2Nhc2E=',
    ['SQL', 'Temporary Tables', 'SQL Test Scripts'],
    'U$ 3,300 a U$ 4,500'
  ),
  striderOpening(
    'Senior BE Engineer - Java, Spring',
    4,
    'app.onstrider.com/r/trampar_de_casa?job=c2VuaW9yLWRiYS1tc3NxbC04NjM3MThkMz9yZWZlcnJhbD10cmFtcGFyX2RlX2Nhc2E=',
    ['Java', 'Spring', 'React'],
    'U$ 6,300 a U$ 8,000'
  ),
  striderOpening(
    'Senior Full-stack Engineer - Spring, React.js',
    5,
    'app.onstrider.com/r/trampar_de_casa?job=c2VuaW9yLWZ1bGwtc3RhY2stZW5naW5lZXItc3ByaW5nLXJlYWN0anMtYTFiZmFjNjY/cmVmZXJyYWw9dHJhbXBhcl9kZV9jYXNh',
    ['Spring', 'React', 'Strong English']
  ),
  striderOpening(
    'Senior Full-stack Engineer',
    5,
    'app.onstrider.com/r/trampar_de_casa?job=c2VuaW9yLWZ1bGwtc3RhY2stZW5naW5lZXItZGphbmdvLXJlYWN0LmpzLTBhOTc2MjU0MmEwMj9yZWZlcnJhbD10cmFtcGFyX2RlX2Nhc2E=',
    ['Django', 'React', 'Full Stack', '50/50'],
    'U$ 5,000 a U$ 7,500'
  ),
  striderOpening(
    'Senior Machine Learning Engineer',
    6,
    'app.onstrider.com/r/trampar_de_casa?job=c2VuaW9yLW1hY2hpbmUtbGVhcm5pbmctZW5naW5lZXItZTUzMDIyZDc/cmVmZXJyYWw9dHJhbXBhcl9kZV9jYXNh',
    ['Deep Learning', 'Computer Vision', 'Published Papers'],
    'U$ 5,000 a U$ 6,500'
  ),
]

const globalOpenings: Opening[] = [
  {
    url: 'https://programathor.com.br/jobs/28986-desenvolvedor-a-rust-go-senior',
    company: 'ProgramaThor',
    title: 'Desenvolvedor(a) Rust/Go Sênior',
    location: 'United States',
    currency: 'USD',
    salary: 'from R$ 18.000,00 to R$ 18.000,00 BRL/monthly',
    headerInfo: 'Sênior (R$ 18.000)',
    language: 'Inglês',
    skills: ['Python', 'C++', 'MySQL', 'PostgreSQL', 'MongoDB'],
  },
]

export const openings20230712: Openings = {
  localOpenings: [...localJrOpenings, ...localOpenings],
  globalOpenings: [...globalPartnerCompanies, ...globalOpenings],
}
