import { Opening } from 'shared/src/email/openings-email/Opening'
import { striderOpening } from 'shared/src/email/openings-email/striderOpening'
import { Openings } from '../Openings'

const localJrOpenings: Opening[] = [
  {
    company: 'Melhor Escolha',
    title: 'Analista de Testes Júnior',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    salary: 'Até R$3.500',
    skills: [
      'CSS',
      'JavaScript',
      'HTML',
      'Testes Automatizados',
      'Testes Regressão',
    ],
    headerInfo: 'Júnior (R$3.500)',
    url: 'https://programathor.com.br/jobs/28976-analista-de-testes-junior-100-remoto',
  },
  {
    company: 'Codecycle',
    title: 'Desenvolvedor(a) .Net (C#) Júnior',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    salary: 'Até R$4.000',
    skills: ['C#', '.NET', 'SQLServer', 'Angular', 'API'],
    headerInfo: 'Júnior (R$4.000)',
    url: 'https://programathor.com.br/jobs/29015-desenvolvedor-a-net-c-junior',
  },
  {
    company: 'Nuuvem',
    title: 'Desenvolvedor Bubble Jr',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    salary: 'R$5.100 a R$ 6.000',
    skills: ['Bubble', 'HTML', 'CSS', 'JavaScript'],
    headerInfo: 'Júnior (R$5.000 a R$ 6.000)',
    url: 'https://careers.nuuvem.com/o/desenvolvedor-bubble-jr-1',
  },
  {
    url: 'https://www.klutch.com.br/vagas/desenvolvedor-react-junior',
    company: 'Klutch Tecnologia',
    title: 'Desenvolvedor(a) React Front-End',
    location: 'Brasil',
    currency: 'R$',
    salary: 'from R$ 0,00 to R$ 0,00 BRL/monthly',
    headerInfo: 'Júnior',
    language: 'Inglês',
    skills: ['HTML', 'CSS', 'React'],
  },
  {
    company: 'Dock',
    title: 'Junior Software Engineer (Java - Authorization)',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Java 8+', 'Spring Boot', 'Banco de dados SQL Server', 'Linux'],
    headerInfo: 'Júnior',
    url: 'https://dock.gupy.io/job/eyJzb3VyY2UiOiJndXB5X3B1YmxpY19wYWdlIiwiam9iSWQiOjQ4OTUyMDF9',
  },
  {
    company: 'Serasa Experian',
    title: 'Desenvolvedor(a) iOS Jr',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    salary: 'Not specified',
    skills: ['Swift', 'Git', 'Storyboard', 'Mobile'],
    headerInfo: 'Júnior',
    url: 'https://jobs.smartrecruiters.com/Experian/743999914424554-desenvolvedor-a-ios-jr',
  },

  {
    company: 'Knewin',
    title: 'Pessoa Desenvolvedora Java Fullstack (Júnior)',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    salary: 'Not specified',
    skills: ['Java', 'Javascript', 'Typescript', 'Nodejs', 'SQL'],
    headerInfo: 'Júnior',
    url: 'https://knewin.gupy.io/job/eyJzb3VyY2UiOiJndXB5X3B1YmxpY19wYWdlIiwiam9iSWQiOjUwMzk4MjN9',
  },
  {
    company: 'Celcoin',
    title: 'Administrador de Banco de dados Jr',
    location: 'Barueri - SP',
    language: 'Português',
    currency: 'R$',
    skills: ['Curso Superior', 'SQL', 'ETL'],
    headerInfo: 'Júnior',
    url: 'https://celcoin.gupy.io/job/eyJqb2JJZCI6NDk2OTE5Nywic291cmNlIjoibGlua2VkaW4ifQ==',
  },
]

const localOpenings: Opening[] = [
  {
    company: 'Going2 Corporation S/A',
    title: 'Dev. Front-end Pleno Mobile (React Native)',
    location: 'Sorocaba / SP',
    language: 'Português',
    currency: 'R$',
    skills: [
      'React Native',
      'CI/CD',
      'Arquitetura',
      'Firebase',
      'Banco de dados offline',
    ],
    headerInfo: 'Pleno',
    url: 'https://going2.solides.jobs/vacancies/269146',
  },
  {
    url: 'https://careers.nuuvem.com/o/fullstack-web-developer-ruby',
    company: 'Nuuvem',
    title: 'Full-Stack Web Developer (Ruby)',
    currency: 'R$',
    salary: 'from R$ 7.500,00 to R$ 15.000,00 BRL/monthly',
    location: 'Rio de Janeiro',
    language: 'Português',
    skills: ['HTML', 'CSS', 'Node', 'JavaScript', 'Python'],
    headerInfo: 'Mínimo de 3 anos de XP (R$ 7.500 a R$ 13.000)',
  },
  {
    url: 'https://programathor.com.br/jobs/28981-desenvolvedor-a-de-software-pleno',
    company: 'ProgramaThor',
    title: 'Desenvolvedor(a) de Software Pleno',
    currency: 'R$',
    salary: 'from R$ 8.000,00 to R$ 8.000,00 BRL/monthly',
    headerInfo: 'Pleno (até R$8.000)',
    language: 'Inglês',
    skills: ['HTML', 'CSS', 'Python', 'Java', 'C++'],
    location: 'Brasil',
  },
  {
    company: 'JFOX',
    title: 'Gerente de Projetos Salesforce Pleno',
    location: 'Nova Lima - MG',
    language: 'Português',
    currency: 'R$',
    skills: [
      'Gerenciamento de Projetos',
      'Scrum',
      'Salesforce',
      'Comunicação',
      'Liderança',
    ],
    headerInfo: 'Pleno',
    url: 'https://www.careerjet.com.br/jobad/br7869c519287010ac8c7e4ec176cad9e3',
  },
  {
    company: 'Welkron Pensamento',
    title: 'Pessoa Desenvolvedora PHP (Remoto)',
    location: 'Porto Alegre-RS',
    language: 'Português',
    currency: 'R$',
    skills: ['PHP 7+', 'Laravel', 'SQL', 'MySQL', 'MongoDB'],
    headerInfo: 'Pleno',
    url: 'https://vagas.empregos.com.br/vaga/8778745/pessoa-desenvolvedora-php-remoto-em-porto-alegre-rs',
  },

  {
    url: 'https://programathor.com.br/jobs/28983-desenvolvedor-a-react-pleno',
    company: 'ProgramaThor',
    title: 'Desenvolvedor(a) React Pleno',
    currency: 'R$',
    salary: 'from R$ 8.000,00 to R$ 8.000,00 BRL/monthly',
    location: 'Brasil',
    headerInfo: 'Pleno (até R$ 8.000)',
    language: 'Português',
    skills: ['CSS', 'JavaScript', 'Java', 'TypeScript', 'React'],
  },
  {
    url: 'https://jobs.quickin.io/ucondo/jobs/649c2db133769e001a3fa28b',
    company: 'uCondo',
    location: 'Brasil',
    title: 'Product Designer Sênior',
    currency: 'R$',
    headerInfo: 'Sênior (R$ 7.000 a R$9.000)',
    language: 'Português',
    skills: ['Formação em UI/UX', 'Design System', 'Temas Saas'],
  },

  {
    company: 'Zup Innovation',
    title: 'Senior Front-End Developer | Angular',
    location: 'Remoto',
    language: 'Português',
    currency: 'R$',
    skills: ['Angular', 'AWS'],
    headerInfo: 'Sênior',
    url: 'https://boards.greenhouse.io/zupinnovation/jobs/5559469003',
  },
]

const globalPartnerCompanies: Opening[] = [
  {
    company: 'Meteor Software',
    title: 'DevOps Engineer',
    location: 'Remoto',
    language: 'Inglês',
    currency: 'U$',
    skills: ['AWS', 'Docker', 'Kubernetes', 'Terraform', 'Linux'],
    headerInfo: 'Júnior a Pleno ($2,000 a $ 3,500)',
    url: 'https://public.app.shortcut.com/62/meteor-software/docs/33M0mvrlVcqjX85UO74Hdl/devops-engineer',
  },
  striderOpening(
    'Mid-level Scraping Engineer - Python',
    3,
    'app.onstrider.com/r/trampar_de_casa?job=bWlkLWxldmVsLXNjcmFwaW5nLWVuZ2luZWVyLXB5dGhvbi03NjhiOTdhYz9yZWZlcnJhbD10cmFtcGFyX2RlX2Nhc2E=',
    ['Python', 'Playwright', 'HTML'],
    '$4,000 a $ 6,200'
  ),
  striderOpening(
    'Product Designer',
    3,
    'app.onstrider.com/r/trampar_de_casa?job=cHJvZHVjdC1kZXNpZ25lci1kN2VkMmJhOT9yZWZlcnJhbD10cmFtcGFyX2RlX2Nhc2E=',
    ['Design for Web', 'UI/UX', 'Data Visualization'],
    '$6,300 a $ 10,000'
  ),
  striderOpening(
    'Database Administrator',
    4,
    'app.onstrider.com/r/trampar_de_casa?job=c2VuaW9yLWRiYS1tc3NxbC04NjM3MThkMz9yZWZlcnJhbD10cmFtcGFyX2RlX2Nhc2E=',
    ['SQL', 'Temporary Tables', 'SQL Test Scripts'],
    '$3,300 a $ 4,500'
  ),
  striderOpening(
    'Senior BE Engineer - Java, Spring',
    4,
    'app.onstrider.com/r/trampar_de_casa?job=c2VuaW9yLWRiYS1tc3NxbC04NjM3MThkMz9yZWZlcnJhbD10cmFtcGFyX2RlX2Nhc2E=',
    ['Java', 'Spring', 'React'],
    '$6,300 a $ 8,000'
  ),
  striderOpening(
    'Senior Full-stack Engineer - Spring, React.js',
    5,
    'app.onstrider.com/r/trampar_de_casa?job=c2VuaW9yLWZ1bGwtc3RhY2stZW5naW5lZXItc3ByaW5nLXJlYWN0anMtYTFiZmFjNjY/cmVmZXJyYWw9dHJhbXBhcl9kZV9jYXNh',
    ['Spring', 'React', 'Strong English']
  ),
  striderOpening(
    'Senior Full-stack Engineer',
    5,
    'app.onstrider.com/r/trampar_de_casa?job=c2VuaW9yLWZ1bGwtc3RhY2stZW5naW5lZXItZGphbmdvLXJlYWN0LmpzLTBhOTc2MjU0MmEwMj9yZWZlcnJhbD10cmFtcGFyX2RlX2Nhc2E=',
    ['Django', 'React', 'Full Stack', '50/50'],
    '$5,000 a $ 7,500'
  ),
  striderOpening(
    'Senior Machine Learning Engineer',
    6,
    'app.onstrider.com/r/trampar_de_casa?job=c2VuaW9yLW1hY2hpbmUtbGVhcm5pbmctZW5naW5lZXItZTUzMDIyZDc/cmVmZXJyYWw9dHJhbXBhcl9kZV9jYXNh',
    ['Deep Learning', 'Computer Vision', 'Published Papers'],
    '$5,000 a $ 6,500'
  ),
]

const globalOpenings: Opening[] = [
  {
    title: 'Front End Product Software Engineer',
    company: 'Dropbox',
    location: 'Polônia',
    language: 'Inglês',
    url: 'https://dynamitejobs.com/company/dropbox/remote-job/front-end-product-software-engineer',
    currency: 'U$',
    headerInfo: 'Mínimo 2 anos de XP ($3,700 a $6,600)',
    skills: ['JavaScript', 'React.js', 'TypeScript'],
  },
  {
    title: 'Remote iOS Developer',
    company: 'Photo AI',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    url: 'https://remoteok.com/remote-jobs/remote-ios-developer-photo-ai-311851',
    headerInfo: '$2,500 a $6,600',
    skills: [
      'Swift',
      'iOS frameworks',
      'RESTful APIs',
      'Memory management',
      'Multithreading',
    ],
  },
  {
    title: 'Front End Developer',
    company: 'Coalition Technologies',
    location: 'Mundial',
    language: 'Inglês',
    url: 'https://remotive.com/remote-jobs/software-dev/front-end-developer-1680495',
    currency: 'U$',
    headerInfo: 'Sênior ($2,600 a $6,000)',
    skills: ['HTML5', 'CSS3', 'jQuery', 'Twitter’s Bootstrap', 'PHP/MYSQL'],
  },
  {
    title: 'Front-end developer',
    company: 'TextMagic',
    location: 'Estônia',
    language: 'Inglês',
    url: 'https://dynamitejobs.com/company/textmagic/remote-job/front-end-developer-vue-js-typescript-spa-remote',
    currency: 'U$',
    headerInfo: 'Sênior ($5,000 a $10,000)',
    skills: ['Vue.js', 'JavaScript', 'TypeScript', 'CSS'],
  },

  {
    title: 'Sr. Product Designer',
    company: 'FlyLance',
    location: 'Estados Unidos',
    language: 'Inglês',
    url: 'https://www.flylance.com/role?id=receY44tUh9fTv0q6',
    currency: 'U$',
    headerInfo: 'Mínimo de 7 anos de XP',
    skills: ['Figma', 'Teste de Usabilidade', 'Persona'],
  },
  {
    title: 'Senior Backend Developer - Node (Remote)',
    company: 'Bitfinex',
    location: 'Mundial',
    language: 'Inglês',
    url: 'https://wellfound.com/company/bitfinex/jobs/2731909-senior-backend-developer-node-remote',
    currency: 'U$',
    headerInfo: 'Sênior ( $5,000 a $10,000 )',
    skills: ['Javascript', 'MySQL', 'MongoDB', 'Node.js', 'Blockchain'],
  },
  {
    title: 'Machine Learning Intern',
    company: 'Ivy',
    location: 'Estados Unidos',
    language: 'Inglês',
    url: 'https://dynamitejobs.com/company/ivy01/remote-job/machine-learning-intern-3',
    currency: 'U$',
    headerInfo: 'Estagiário ( $2,500 a $4,000 )',
    skills: ['Machine Learning', 'Python', 'PyTorch', 'Tensorflow'],
  },
  {
    url: 'https://programathor.com.br/jobs/28986-desenvolvedor-a-rust-go-senior',
    company: 'ProgramaThor',
    title: 'Desenvolvedor(a) Rust/Go Sênior',
    location: 'United States',
    currency: 'U$',
    salary: 'from R$ 18.000,00 to R$ 18.000,00 BRL/monthly',
    headerInfo: 'Sênior (R$ 18.000)',
    language: 'Inglês',
    skills: ['Python', 'C++', 'MySQL', 'PostgreSQL', 'MongoDB'],
  },
  {
    title: 'Sr. React Engineer',
    company: 'FlyLance',
    location: 'Estados Unidos',
    language: 'Inglês',
    url: 'https://www.flylance.com/role?id=recMaDly969lDSw7G',
    currency: 'U$',
    headerInfo: 'Senior',
    skills: ['REACT', 'Typescript', 'Material UI', 'Azure DevOps'],
  },
  {
    title: 'Sr. Frontend Engineer (Vue.js)',
    company: 'FlyLance',
    location: 'Estados Unidos',
    language: 'Inglês',
    url: 'https://www.flylance.com/role?id=rec1agBSh1RRZSzfu',
    currency: 'U$',
    headerInfo: 'Mínimo de 5 anos de XP',
    skills: [
      'Vue.js',
      'JavaScript',
      'REST API Development',
      'SQL',
      'Agile software development',
    ],
  },
  {
    title: 'Backend Developer (Python)',
    company: 'dresslife',
    location: 'Alemanha',
    language: 'Inglês',
    url: 'https://wellfound.com/company/dresslife/jobs/557180-backend-developer-python',
    currency: 'U$',
    headerInfo: '€3.750 a €4.580',
    skills: [
      'Python',
      'Node.js',
      'Solutions Architecture',
      'ECMAScript',
      'Clean Code',
    ],
  },
]

export const openings20230712: Openings = {
  localOpenings: [...localJrOpenings, ...localOpenings],
  globalOpenings: [...globalPartnerCompanies, ...globalOpenings],
}
