export const skillArray = [
  '.NET',
  'AB Testing',
  'API Development',
  'AR/VR Design',
  'ASP.NET',
  'AWS',
  'Academic Writing',
  'Account Management',
  'Adobe XD',
  'Affiliate Marketing',
  'Agile Methodologies',
  'Android Development',
  'AngularJS',
  'Animation',
  'B2B Sales',
  'B2C Sales',
  'Bash/Shell',
  'Blogging',
  'Bootstrap',
  'Brand Management',
  'Budgeting',
  'Business Development',
  'Business Strategy',
  'C',
  'C#',
  'C++',
  'CRM',
  'CSS',
  'CSS3',
  'Change Management',
  'Channel Sales',
  'Cold Calling',
  'Color Theory',
  'Conflict Resolution',
  'Content Marketing',
  'Content Writing',
  'Conversion Rate Optimization',
  'Copywriting',
  'Creative Writing',
  'Data Analysis',
  'Data-driven Decision Making',
  'Direct Sales',
  'Django',
  'Docker',
  'Drupal',
  'Editing',
  'Email Marketing',
  'Emotional Intelligence',
  'Enterprise Sales',
  'Facebook Ads',
  'Figma',
  'Flutter',
  'Frontend Development',
  'Go',
  'Google Adwords',
  'Google Analytics',
  'Google Tag Manager',
  'Grant Writing',
  'Graphic Design',
  'HTML',
  'HTML5',
  'ITIL',
  'Illustrator',
  'InDesign',
  'Inbound Sales',
  'Interaction Design',
  'Java',
  'JavaScript',
  'Kanban',
  'Kotlin',
  'Laravel',
  'Leadership',
  'Lean',
  'Market Research',
  'Marketing Automation',
  'Marketing Strategy',
  'Medical Writing',
  'Mobile Advertising',
  'MongoDB',
  'Motion Graphics',
  'MySQL',
  'Negotiation',
  'Newsletters',
  'Objective-C',
  'Outbound Sales',
  'PHP',
  'PPC',
  'Performance Management',
  'Perl',
  'Photoshop',
  'Press Releases',
  'Prince2',
  'Project Management',
  'Proofreading',
  'Prototyping',
  'Public Relations',
  'Python',
  'Resource Management',
  'Responsive Design',
  'Risk Management',
  'Ruby on Rails',
  'Ruby',
  'Rust',
  'SEM',
  'SEO Writing',
  'SEO',
  'SQL',
  'SaaS Sales',
  'Sales Analytics',
  'Sales Closing',
  'Sales Enablement',
  'Sales Forecasting',
  'Sales Management',
  'Sales Operations',
  'Sales Process',
  'Sales Strategy',
  'Salesforce',
  'Scala',
  'Scrum',
  'Sketch',
  'Social Media Marketing',
  'Strategic Planning',
  'Swift',
  'Team Building',
  'Technical Writing',
  'Telesales',
  'TypeScript',
  'Typography',
  'UI Design',
  'UX Design',
  'UX Research',
  'Video Marketing',
  'Viral Marketing',
  'Vue.js',
  'Waterfall',
  'Web Analytics',
  'Web Content Writing',
  'Web Design',
  'Web Development',
  'Whitepapers',
  'Wireframing',
  'WordPress',
  'YouTube Marketing',
  'iOS Development',
  'Frontend',
  'Backend',
  'React',
  'Angular',
  'Vue.js',
  'Astro.js',
  'Svelte',
  'Ember.js',
  'Next.js',
  'Express.js',
  'Meteor.js',
  'Nest.js',
  'Aurelia',
  'Remix.js',
  'Core Java',
  'Java SE',
  'Java EE',
  'Oracle JDK',
  'OpenJDK',
  'Eclipse IDE',
  'IntelliJ IDEA',
  'NetBeans IDE',
  'Apache Maven',
  'Apache Ant',
  'Gradle',
  'Spring Framework',
  'Spring Core',
  'Spring MVC',
  'Spring Boot',
  'Spring Data',
  'Spring Security',
  'Hibernate ORM',
  'Struts Framework',
  'JavaServer Faces',
  'Play Framework',
  'Grails Framework',
  'Apache Wicket',
  'Servlets',
  'JavaServer Pages',
  'WebSocket API',
  'JAX-RS',
  'JSON-B',
  'Enterprise JavaBeans',
  'Session Beans',
  'Message-Driven Beans',
  'Entity Beans',
  'Java Persistence',
  'Java Messaging',
  'JDBC',
  'JUnit Testing',
  'TestNG Testing',
  'SLF4J Logging',
  'Log4j Logging',
  'RMI',
  'Java Security',
  'Kotlin Language',
  'Scala Language',
  '.NET Framework',
  '.NET Core',
  '.NET 5',
  '.NET 6',
  'ASP.NET Core',
  'Entity Framework',
  'Entity Framework Core',
  'Blazor',
  'Windows Forms',
  'Xamarin',
  'Unity3D',
  'PowerShell',
  'LINQ',
  'Kubernetes',
  'Amazon EC2',
  'Amazon EC2 Auto Scaling',
  'Amazon Lightsail',
  'AWS Lambda',
  'Amazon S3',
  'Amazon EBS',
  'Amazon Glacier',
  'Amazon S3 Glacier Deep Archive',
  'Amazon RDS',
  'Amazon DynamoDB',
  'Amazon Redshift',
  'Amazon Aurora',
  'Amazon VPC',
  'Amazon Route 53',
  'AWS Direct Connect',
  'Amazon API Gateway',
  'AWS Identity and Access Management (IAM)',
  'AWS Key Management Service (KMS)',
  'Amazon Cognito',
  'Amazon SageMaker',
  'AWS Comprehend',
  'AWS Rekognition',
  'Amazon Polly',
  'Amazon Lex',
  'AWS CodePipeline',
  'AWS CodeBuild',
  'AWS CodeDeploy',
  'AWS CodeCommit',
  'AWS Cloud9',
  'Amazon CloudWatch',
  'AWS CloudTrail',
  'AWS Config',
  'AWS Systems Manager',
  'AWS IoT Core',
  'AWS IoT Greengrass',
  'Amazon FreeRTOS',
  'Amazon ECS',
  'Amazon EKS',
  'AWS Fargate',
  'AWS Step Functions',
  'Amazon EventBridge',
  'Amazon Athena',
  'Amazon EMR',
  'Amazon Kinesis',
  'Amazon QuickSight',
  'Amazon GameLift',
  'Amazon Managed Blockchain',
  'Amazon Sumerian',
  'Elixir',
  'Phoenix Framework',
  'Absinthe GraphQL',
  'Nerves Framework',
  'Mix Build Tool',
  'Erlang OTP',
  'RabbitMQ',
  'Rebar3 Build Tool',
  'Erlang Web',
  'LFE (Lisp Flavored Erlang)',
  'PHP',
  'Laravel',
  'Symfony',
  'CodeIgniter',
  'Yii',
  'Zend Framework',
  'Phalcon',
  'Laminas',
  'CakePHP',
  'Slim',
  'WordPress (Plugin Development)',
  'Drupal (Module Development)',
  'Joomla (Extension Development)',
  'Rust',
  'Dart',
  'Flutter',
  'Swift',
  'Kotlin',
  'Objective-C',
  'React Native',
  'Ionic Framework',
  'Cordova',
  'PhoneGap',
  'Xamarin',
  'TensorFlow',
  'PyTorch',
  'Keras',
  'Natural Language Processing (NLP)',
  'Reinforcement Learning',
  'Unity3D',
  'Unreal Engine',
  'Game Development',
  'Virtual Reality (VR)',
  'Augmented Reality (AR)',
  'Blockchain Development',
  'Smart Contracts',
  'Solidity',
  'Web3.js',
  'Truffle Framework',
  'IPFS (InterPlanetary File System)',
  'Decentralized Finance (DeFi)',
  'Non-Fungible Tokens (NFTs)',
  'Cybersecurity',
  'Ethical Hacking',
  'Penetration Testing',
  'Cryptography',
  'Network Security',
  'OWASP Top Ten',
  'Secure Coding Practices',
  'Computer Vision',
  'Internet of Things (IoT)',
  'Edge Computing',
  'Big Data',
  'Hadoop',
  'Spark',
  'NoSQL Databases (MongoDB, Cassandra, Couchbase)',
  'Data Warehousing',
  'Data Mining',
  'Machine Learning',
  'Deep Learning',
  'Computer Graphics',
  'Game Design',
  'Game Mechanics',
  'User Interface (UI) Design',
  'User Experience (UX) Design',
  'Human-Computer Interaction (HCI)',
  'Responsive Web Design',
  'Progressive Web Apps (PWA)',
  'WebAssembly',
  'Serverless Architecture',
  'Microservices Architecture',
  'GraphQL',
  'RESTful APIs',
  'SOAP',
  'JSON-RPC',
  'XML-RPC',
  'WebSockets',
  'OAuth',
  'JWT (JSON Web Tokens)',
  'GraphQL Subscriptions',
  'gRPC',
  'Apache Kafka',
  'RabbitMQ',
  'AWS SQS (Simple Queue Service)',
  'Docker Swarm',
  'Kubernetes',
  'Jenkins',
  'Travis CI',
  'GitLab CI/CD',
  'GitHub Actions',
  'Heroku',
  'Netlify',
  'Vercel',
  'Google Cloud Platform (GCP)',
  'Microsoft Azure',
  'IBM Cloud',
  'Alibaba Cloud',
  'DigitalOcean',
  'Firebase',
  'Nginx',
  'Apache HTTP Server',
  'Microsoft IIS',
  'HAProxy',
  'CDN (Content Delivery Network)',
  'Load Balancing',
  'Reverse Proxy',
  'Web Servers Configuration',
  'DevOps Practices',
  'Agile Project Management Tools (Jira, Trello, Asana)',
  'Version Control Systems (Git, SVN)',
  'Continuous Integration/Continuous Deployment (CI/CD)',
  'Infrastructure as Code (IaC)',
  'Monitoring and Logging Tools (Prometheus, Grafana, ELK Stack)',
  'Container Orchestration',
  'Site Reliability Engineering (SRE)',
  'Incident Response',
  'Disaster Recovery Planning',
  'Compliance and Governance',
  'IT Service Management (ITSM)',
  'ITIL Framework',
  'Customer Relationship Management (CRM) Systems',
  'Salesforce',
  'HubSpot',
  'Zoho CRM',
  'Microsoft Dynamics CRM',
  'Customer Support Platforms (Zendesk, Freshdesk)',
  'E-commerce Platforms (Shopify, WooCommerce, Magento)',
  'Content Management Systems (WordPress, Drupal, Joomla)',
  'Learning Management Systems (LMS)',
  'E-learning Development Tools (Moodle, Articulate Storyline)',
  'Collaboration Tools (Slack, Microsoft Teams, Zoom)',
  'Productivity Suites (Microsoft 365, Google Workspace)',
  'Version Control Systems (Git, SVN)',
  'Code Review Tools (GitHub Pull Requests, Bitbucket Code Insights)',
  'Static Code Analysis Tools',
  'Automated Testing Tools (Selenium, JUnit, Jest)',
  'Performance Testing Tools (Apache JMeter, LoadRunner)',
  'Security Testing Tools (Burp Suite, OWASP ZAP)',
  'Continuous Monitoring Tools',
  'Log Management and Analysis',
  'Server and Network Monitoring',
  'Cloud Security',
  'Data Encryption',
  'Identity and Access Management (IAM)',
  'Multi-Factor Authentication (MFA)',
  'Security Information and Event Management (SIEM)',
  'Security Incident Response',
  'Endpoint Security',
  'Network Security Protocols (SSL/TLS, IPSec)',
  'Firewalls and Intrusion Detection Systems (IDS)',
  'Secure Software Development Lifecycle (SDLC) Practices',
  'Threat Modeling',
  'Secure Coding Guidelines',
  'Vulnerability Management',
  'Penetration Testing',
  'Ethical Hacking',
  'Security Awareness Training',
  'Regulatory Compliance (GDPR, HIPAA, PCI DSS)',
]
