export const skillArray = [
  '.NET',
  'AB Testing',
  'API Development',
  'AR/VR Design',
  'ASP.NET',
  'AWS',
  'Academic Writing',
  'Account Management',
  'Adobe XD',
  'Affiliate Marketing',
  'Agile Methodologies',
  'Android Development',
  'AngularJS',
  'Animation',
  'B2B Sales',
  'B2C Sales',
  'Bash/Shell',
  'Blogging',
  'Bootstrap',
  'Brand Management',
  'Budgeting',
  'Business Development',
  'Business Strategy',
  'C',
  'C#',
  'C++',
  'CRM',
  'CSS',
  'CSS3',
  'Change Management',
  'Channel Sales',
  'Cold Calling',
  'Color Theory',
  'Conflict Resolution',
  'Content Marketing',
  'Content Writing',
  'Conversion Rate Optimization',
  'Copywriting',
  'Creative Writing',
  'Data Analysis',
  'Data-driven Decision Making',
  'Direct Sales',
  'Django',
  'Docker',
  'Drupal',
  'Editing',
  'Email Marketing',
  'Emotional Intelligence',
  'Enterprise Sales',
  'Facebook Ads',
  'Figma',
  'Flutter',
  'Frontend Development',
  'Go',
  'Google Adwords',
  'Google Analytics',
  'Google Tag Manager',
  'Grant Writing',
  'Graphic Design',
  'HTML',
  'HTML5',
  'ITIL',
  'Illustrator',
  'InDesign',
  'Inbound Sales',
  'Interaction Design',
  'Java',
  'JavaScript',
  'Kanban',
  'Kotlin',
  'Laravel',
  'Leadership',
  'Lean',
  'Market Research',
  'Marketing Automation',
  'Marketing Strategy',
  'Medical Writing',
  'Mobile Advertising',
  'MongoDB',
  'Motion Graphics',
  'MySQL',
  'Negotiation',
  'Newsletters',
  'Objective-C',
  'Outbound Sales',
  'PHP',
  'PPC',
  'Performance Management',
  'Perl',
  'Photoshop',
  'Press Releases',
  'Prince2',
  'Project Management',
  'Proofreading',
  'Prototyping',
  'Public Relations',
  'Python',
  'Resource Management',
  'Responsive Design',
  'Risk Management',
  'Ruby on Rails',
  'Ruby',
  'Rust',
  'SEM',
  'SEO Writing',
  'SEO',
  'SQL',
  'SaaS Sales',
  'Sales Analytics',
  'Sales Closing',
  'Sales Enablement',
  'Sales Forecasting',
  'Sales Management',
  'Sales Operations',
  'Sales Process',
  'Sales Strategy',
  'Salesforce',
  'Scala',
  'Scrum',
  'Sketch',
  'Social Media Marketing',
  'Strategic Planning',
  'Swift',
  'Team Building',
  'Technical Writing',
  'Telesales',
  'TypeScript',
  'Typography',
  'UI Design',
  'UX Design',
  'UX Research',
  'Video Marketing',
  'Viral Marketing',
  'Vue.js',
  'Waterfall',
  'Web Analytics',
  'Web Content Writing',
  'Web Design',
  'Web Development',
  'Whitepapers',
  'Wireframing',
  'WordPress',
  'YouTube Marketing',
  'iOS Development',
  'Frontend',
  'Backend',
  'React',
  'Angular',
  'Vue.js',
  'Astro.js',
  'Svelte',
  'Ember.js',
  'Next.js',
  'Express.js',
  'Meteor.js',
  'Nest.js',
  'Aurelia',
  'Remix.js',
  'Core Java',
  'Java SE',
  'Java EE',
  'Oracle JDK',
  'OpenJDK',
  'Eclipse IDE',
  'IntelliJ IDEA',
  'NetBeans IDE',
  'Apache Maven',
  'Apache Ant',
  'Gradle',
  'Spring Framework',
  'Spring Core',
  'Spring MVC',
  'Spring Boot',
  'Spring Data',
  'Spring Security',
  'Hibernate ORM',
  'Struts Framework',
  'JavaServer Faces',
  'Play Framework',
  'Grails Framework',
  'Apache Wicket',
  'Servlets',
  'JavaServer Pages',
  'WebSocket API',
  'JAX-RS',
  'JSON-B',
  'Enterprise JavaBeans',
  'Session Beans',
  'Message-Driven Beans',
  'Entity Beans',
  'Java Persistence',
  'Java Messaging',
  'JDBC',
  'JUnit Testing',
  'TestNG Testing',
  'SLF4J Logging',
  'Log4j Logging',
  'RMI',
  'Java Security',
  'Kotlin Language',
  'Scala Language',
  '.NET Framework',
  '.NET Core',
  '.NET 5',
  '.NET 6',
  'ASP.NET Core',
  'Entity Framework',
  'Entity Framework Core',
  'Blazor',
  'Windows Forms',
  'Xamarin',
  'Unity3D',
  'PowerShell',
  'LINQ',
  'Kubernetes',
  'Amazon EC2',
  'Amazon EC2 Auto Scaling',
  'Amazon Lightsail',
  'AWS Lambda',
  'Amazon S3',
  'Amazon EBS',
  'Amazon Glacier',
  'Amazon S3 Glacier Deep Archive',
  'Amazon RDS',
  'Amazon DynamoDB',
  'Amazon Redshift',
  'Amazon Aurora',
  'Amazon VPC',
  'Amazon Route 53',
  'AWS Direct Connect',
  'Amazon API Gateway',
  'AWS Identity and Access Management (IAM)',
  'AWS Key Management Service (KMS)',
  'Amazon Cognito',
  'Amazon SageMaker',
  'AWS Comprehend',
  'AWS Rekognition',
  'Amazon Polly',
  'Amazon Lex',
  'AWS CodePipeline',
  'AWS CodeBuild',
  'AWS CodeDeploy',
  'AWS CodeCommit',
  'AWS Cloud9',
  'Amazon CloudWatch',
  'AWS CloudTrail',
  'AWS Config',
  'AWS Systems Manager',
  'AWS IoT Core',
  'AWS IoT Greengrass',
  'Amazon FreeRTOS',
  'Amazon ECS',
  'Amazon EKS',
  'AWS Fargate',
  'AWS Step Functions',
  'Amazon EventBridge',
  'Amazon Athena',
  'Amazon EMR',
  'Amazon Kinesis',
  'Amazon QuickSight',
  'Amazon GameLift',
  'Amazon Managed Blockchain',
  'Amazon Sumerian',
]
