export const skillArray = [
  { id: 0, name: '.NET' },
  { id: 1, name: 'AB Testing' },
  { id: 2, name: 'API Development' },
  { id: 3, name: 'AR/VR Design' },
  { id: 4, name: 'ASP.NET' },
  { id: 5, name: 'AWS' },
  { id: 6, name: 'Academic Writing' },
  { id: 7, name: 'Account Management' },
  { id: 8, name: 'Adobe XD' },
  { id: 9, name: 'Affiliate Marketing' },
  { id: 10, name: 'Agile Methodologies' },
  { id: 11, name: 'Android Development' },
  { id: 13, name: 'Animation' },
  { id: 14, name: 'B2B Sales' },
  { id: 15, name: 'B2C Sales' },
  { id: 16, name: 'Bash/Shell' },
  { id: 17, name: 'Blogging' },
  { id: 18, name: 'Bootstrap' },
  { id: 19, name: 'Brand Management' },
  { id: 20, name: 'Budgeting' },
  { id: 21, name: 'Business Development' },
  { id: 22, name: 'Business Strategy' },
  { id: 23, name: 'C' },
  { id: 24, name: 'C#' },
  { id: 25, name: 'C++' },
  { id: 26, name: 'CRM' },
  { id: 27, name: 'CSS' },
  { id: 29, name: 'Change Management' },
  { id: 30, name: 'Channel Sales' },
  { id: 31, name: 'Cold Calling' },
  { id: 32, name: 'Color Theory' },
  { id: 33, name: 'Conflict Resolution' },
  { id: 34, name: 'Content Marketing' },
  { id: 35, name: 'Content Writing' },
  { id: 36, name: 'Conversion Rate Optimization' },
  { id: 37, name: 'Copywriting' },
  { id: 38, name: 'Creative Writing' },
  { id: 39, name: 'Data Analysis' },
  { id: 40, name: 'Data-driven Decision Making' },
  { id: 41, name: 'Direct Sales' },
  { id: 42, name: 'Django' },
  { id: 43, name: 'Docker' },
  { id: 44, name: 'Drupal' },
  { id: 45, name: 'Editing' },
  { id: 46, name: 'Email Marketing' },
  { id: 47, name: 'Emotional Intelligence' },
  { id: 48, name: 'Enterprise Sales' },
  { id: 49, name: 'Facebook Ads' },
  { id: 50, name: 'Figma' },
  { id: 51, name: 'Flutter' },
  { id: 53, name: 'Go' },
  { id: 54, name: 'Google Adwords' },
  { id: 55, name: 'Google Analytics' },
  { id: 56, name: 'Google Tag Manager' },
  { id: 57, name: 'Grant Writing' },
  { id: 58, name: 'Graphic Design' },
  { id: 59, name: 'HTML' },
  { id: 61, name: 'ITIL' },
  { id: 62, name: 'Illustrator' },
  { id: 63, name: 'InDesign' },
  { id: 64, name: 'Inbound Sales' },
  { id: 65, name: 'Interaction Design' },
  { id: 66, name: 'Java' },
  { id: 67, name: 'JavaScript' },
  { id: 68, name: 'Kanban' },
  { id: 69, name: 'Kotlin' },
  { id: 70, name: 'Laravel' },
  { id: 71, name: 'Leadership' },
  { id: 72, name: 'Lean' },
  { id: 73, name: 'Market Research' },
  { id: 74, name: 'Marketing Automation' },
  { id: 75, name: 'Marketing Strategy' },
  { id: 76, name: 'Medical Writing' },
  { id: 77, name: 'Mobile Advertising' },
  { id: 78, name: 'MongoDB' },
  { id: 79, name: 'Motion Graphics' },
  { id: 80, name: 'MySQL' },
  { id: 81, name: 'Negotiation' },
  { id: 82, name: 'Newsletters' },
  { id: 83, name: 'Objective-C' },
  { id: 84, name: 'Outbound Sales' },
  { id: 85, name: 'PHP' },
  { id: 86, name: 'PPC' },
  { id: 87, name: 'Performance Management' },
  { id: 88, name: 'Perl' },
  { id: 89, name: 'Photoshop' },
  { id: 90, name: 'Press Releases' },
  { id: 91, name: 'Prince2' },
  { id: 92, name: 'Project Management' },
  { id: 93, name: 'Proofreading' },
  { id: 94, name: 'Prototyping' },
  { id: 95, name: 'Public Relations' },
  { id: 96, name: 'Python' },
  { id: 97, name: 'Resource Management' },
  { id: 98, name: 'Responsive Design' },
  { id: 99, name: 'Risk Management' },
  { id: 100, name: 'Ruby on Rails' },
  { id: 101, name: 'Ruby' },
  { id: 102, name: 'Rust' },
  { id: 103, name: 'SEM' },
  { id: 104, name: 'SEO Writing' },
  { id: 105, name: 'SEO' },
  { id: 106, name: 'SQL' },
  { id: 107, name: 'SaaS Sales' },
  { id: 108, name: 'Sales Analytics' },
  { id: 109, name: 'Sales Closing' },
  { id: 110, name: 'Sales Enablement' },
  { id: 111, name: 'Sales Forecasting' },
  { id: 112, name: 'Sales Management' },
  { id: 113, name: 'Sales Operations' },
  { id: 114, name: 'Sales Process' },
  { id: 115, name: 'Sales Strategy' },
  { id: 116, name: 'Salesforce' },
  { id: 117, name: 'Scala' },
  { id: 118, name: 'Scrum' },
  { id: 119, name: 'Sketch' },
  { id: 120, name: 'Social Media Marketing' },
  { id: 121, name: 'Strategic Planning' },
  { id: 122, name: 'Swift' },
  { id: 123, name: 'Team Building' },
  { id: 124, name: 'Technical Writing' },
  { id: 125, name: 'Telesales' },
  { id: 126, name: 'TypeScript' },
  { id: 127, name: 'Typography' },
  { id: 128, name: 'UI Design' },
  { id: 129, name: 'UX Design' },
  { id: 130, name: 'UX Research' },
  { id: 131, name: 'Video Marketing' },
  { id: 132, name: 'Viral Marketing' },
  { id: 134, name: 'Waterfall' },
  { id: 135, name: 'Web Analytics' },
  { id: 136, name: 'Web Content Writing' },
  { id: 137, name: 'Web Design' },
  { id: 138, name: 'Web Development' },
  { id: 139, name: 'Whitepapers' },
  { id: 140, name: 'Wireframing' },
  { id: 141, name: 'WordPress' },
  { id: 142, name: 'YouTube Marketing' },
  { id: 143, name: 'iOS Development' },
  { id: 144, name: 'Frontend' },
  { id: 145, name: 'Backend' },
  { id: 146, name: 'React' },
  { id: 147, name: 'Angular' },
  { id: 148, name: 'Vue' },
  { id: 149, name: 'Astro.js' },
  { id: 150, name: 'Svelte' },
  { id: 151, name: 'Ember' },
  { id: 152, name: 'Next' },
  { id: 153, name: 'Express' },
  { id: 154, name: 'Meteor' },
  { id: 155, name: 'Nest' },
  { id: 156, name: 'Aurelia' },
  { id: 157, name: 'Remix.js' },
  { id: 161, name: 'Oracle JDK' },
  { id: 162, name: 'OpenJDK' },
  { id: 163, name: 'Eclipse IDE' },
  { id: 164, name: 'IntelliJ IDEA' },
  { id: 165, name: 'NetBeans IDE' },
  { id: 166, name: 'Apache Maven' },
  { id: 167, name: 'Apache Ant' },
  { id: 168, name: 'Gradle' },
  { id: 172, name: 'Spring Boot' },
  { id: 175, name: 'Hibernate ORM' },
  { id: 176, name: 'Struts Framework' },
  { id: 178, name: 'Play Framework' },
  { id: 179, name: 'Grails Framework' },
  { id: 180, name: 'Apache Wicket' },
  { id: 181, name: 'Servlets' },
  { id: 183, name: 'WebSocket API' },
  { id: 184, name: 'JAX-RS' },
  { id: 185, name: 'JSON-B' },
  { id: 187, name: 'Session Beans' },
  { id: 188, name: 'Message-Driven Beans' },
  { id: 189, name: 'Entity Beans' },
  { id: 192, name: 'JDBC' },
  { id: 193, name: 'JUnit Testing' },
  { id: 194, name: 'TestNG Testing' },
  { id: 195, name: 'SLF4J Logging' },
  { id: 196, name: 'Log4j Logging' },
  { id: 197, name: 'RMI' },
  { id: 199, name: 'Kotlin Language' },
  { id: 200, name: 'Scala Language' },
  { id: 206, name: 'Entity Framework' },
  { id: 207, name: 'Entity Framework Core' },
  { id: 208, name: 'Blazor' },
  { id: 209, name: 'Windows Forms' },
  { id: 210, name: 'Xamarin' },
  { id: 211, name: 'Unity3D' },
  { id: 212, name: 'PowerShell' },
  { id: 213, name: 'LINQ' },
  { id: 214, name: 'Kubernetes' },
  { id: 215, name: 'Amazon EC2' },
  { id: 217, name: 'Amazon Lightsail' },
  { id: 218, name: 'AWS Lambda' },
  { id: 219, name: 'Amazon S3' },
  { id: 220, name: 'Amazon EBS' },
  { id: 221, name: 'Amazon Glacier' },
  { id: 223, name: 'Amazon RDS' },
  { id: 224, name: 'Amazon DynamoDB' },
  { id: 225, name: 'Amazon Redshift' },
  { id: 226, name: 'Amazon Aurora' },
  { id: 227, name: 'Amazon VPC' },
  { id: 228, name: 'Amazon Route 53' },
  { id: 229, name: 'AWS Direct Connect' },
  { id: 230, name: 'Amazon API Gateway' },
  { id: 231, name: 'AWS Identity and Access Management (IAM)' },
  { id: 232, name: 'AWS Key Management Service (KMS)' },
  { id: 233, name: 'Amazon Cognito' },
  { id: 234, name: 'Amazon SageMaker' },
  { id: 235, name: 'AWS Comprehend' },
  { id: 236, name: 'AWS Rekognition' },
  { id: 237, name: 'Amazon Polly' },
  { id: 238, name: 'Amazon Lex' },
  { id: 239, name: 'AWS CodePipeline' },
  { id: 240, name: 'AWS CodeBuild' },
  { id: 241, name: 'AWS CodeDeploy' },
  { id: 242, name: 'AWS CodeCommit' },
  { id: 243, name: 'AWS Cloud9' },
  { id: 244, name: 'Amazon CloudWatch' },
  { id: 245, name: 'AWS CloudTrail' },
  { id: 246, name: 'AWS Config' },
  { id: 247, name: 'AWS Systems Manager' },
  { id: 248, name: 'AWS IoT Core' },
  { id: 249, name: 'AWS IoT Greengrass' },
  { id: 250, name: 'Amazon FreeRTOS' },
  { id: 251, name: 'Amazon ECS' },
  { id: 252, name: 'Amazon EKS' },
  { id: 253, name: 'AWS Fargate' },
  { id: 254, name: 'AWS Step Functions' },
  { id: 255, name: 'Amazon EventBridge' },
  { id: 256, name: 'Amazon Athena' },
  { id: 257, name: 'Amazon EMR' },
  { id: 258, name: 'Amazon Kinesis' },
  { id: 259, name: 'Amazon QuickSight' },
  { id: 260, name: 'Amazon GameLift' },
  { id: 261, name: 'Amazon Managed Blockchain' },
  { id: 262, name: 'Amazon Sumerian' },
  { id: 263, name: 'Elixir' },
  { id: 264, name: 'Phoenix Framework' },
  { id: 265, name: 'Absinthe GraphQL' },
  { id: 266, name: 'Nerves Framework' },
  { id: 267, name: 'Mix Build Tool' },
  { id: 268, name: 'Erlang OTP' },
  { id: 269, name: 'RabbitMQ' },
  { id: 270, name: 'Rebar3 Build Tool' },
  { id: 271, name: 'Erlang Web' },
  { id: 272, name: 'LFE (Lisp Flavored Erlang)' },
  { id: 275, name: 'Symfony' },
  { id: 276, name: 'CodeIgniter' },
  { id: 277, name: 'Yii' },
  { id: 278, name: 'Zend Framework' },
  { id: 279, name: 'Phalcon' },
  { id: 280, name: 'Laminas' },
  { id: 281, name: 'CakePHP' },
  { id: 282, name: 'Slim' },
  { id: 283, name: 'WordPress (Plugin Development)' },
  { id: 284, name: 'Drupal (Module Development)' },
  { id: 285, name: 'Joomla (Extension Development)' },
  { id: 286, name: 'Rust' },
  { id: 287, name: 'Dart' },
  { id: 288, name: 'Flutter' },
  { id: 289, name: 'Swift' },
  { id: 291, name: 'Objective-C' },
  { id: 292, name: 'React Native' },
  { id: 293, name: 'Ionic Framework' },
  { id: 294, name: 'Cordova' },
  { id: 295, name: 'PhoneGap' },
  { id: 296, name: 'Xamarin' },
  { id: 297, name: 'TensorFlow' },
  { id: 298, name: 'PyTorch' },
  { id: 299, name: 'Keras' },
  { id: 300, name: 'Natural Language Processing (NLP)' },
  { id: 301, name: 'Reinforcement Learning' },
  { id: 302, name: 'Unity3D' },
  { id: 303, name: 'Unreal Engine' },
  { id: 304, name: 'Game Development' },
  { id: 305, name: 'Virtual Reality (VR)' },
  { id: 306, name: 'Augmented Reality (AR)' },
  { id: 307, name: 'Blockchain Development' },
  { id: 308, name: 'Smart Contracts' },
  { id: 309, name: 'Solidity' },
  { id: 310, name: 'Web3.js' },
  { id: 311, name: 'Truffle Framework' },
  { id: 312, name: 'IPFS (InterPlanetary File System)' },
  { id: 313, name: 'Decentralized Finance (DeFi)' },
  { id: 314, name: 'Non-Fungible Tokens (NFTs)' },
  { id: 315, name: 'Cybersecurity' },
  { id: 316, name: 'Ethical Hacking' },
  { id: 317, name: 'Penetration Testing' },
  { id: 318, name: 'Cryptography' },
  { id: 319, name: 'Network Security' },
  { id: 320, name: 'OWASP Top Ten' },
  { id: 321, name: 'Secure Coding Practices' },
  { id: 322, name: 'Computer Vision' },
  { id: 323, name: 'Internet of Things (IoT)' },
  { id: 324, name: 'Edge Computing' },
  { id: 325, name: 'Big Data' },
  { id: 326, name: 'Hadoop' },
  { id: 327, name: 'Spark' },
  { id: 328, name: 'NoSQL Databases (MongoDB, Cassandra, Couchbase)' },
  { id: 329, name: 'Data Warehousing' },
  { id: 330, name: 'Data Mining' },
  { id: 331, name: 'Machine Learning' },
  { id: 332, name: 'Deep Learning' },
  { id: 333, name: 'Computer Graphics' },
  { id: 334, name: 'Game Design' },
  { id: 335, name: 'Game Mechanics' },
  { id: 336, name: 'User Interface (UI) Design' },
  { id: 337, name: 'User Experience (UX) Design' },
  { id: 338, name: 'Human-Computer Interaction (HCI)' },
  { id: 339, name: 'Responsive Web Design' },
  { id: 340, name: 'Progressive Web Apps (PWA)' },
  { id: 341, name: 'WebAssembly' },
  { id: 342, name: 'Serverless Architecture' },
  { id: 343, name: 'Microservices Architecture' },
  { id: 344, name: 'GraphQL' },
  { id: 345, name: 'RESTful APIs' },
  { id: 346, name: 'SOAP' },
  { id: 347, name: 'JSON-RPC' },
  { id: 348, name: 'XML-RPC' },
  { id: 349, name: 'WebSockets' },
  { id: 350, name: 'OAuth' },
  { id: 351, name: 'JWT (JSON Web Tokens)' },
  { id: 352, name: 'GraphQL Subscriptions' },
  { id: 353, name: 'gRPC' },
  { id: 354, name: 'Apache Kafka' },
  { id: 355, name: 'RabbitMQ' },
  { id: 356, name: 'AWS SQS (Simple Queue Service)' },
  { id: 357, name: 'Docker Swarm' },
  { id: 358, name: 'Kubernetes' },
  { id: 359, name: 'Jenkins' },
  { id: 360, name: 'Travis CI' },
  { id: 361, name: 'GitLab CI/CD' },
  { id: 362, name: 'GitHub Actions' },
  { id: 363, name: 'Heroku' },
  { id: 364, name: 'Netlify' },
  { id: 365, name: 'Vercel' },
  { id: 366, name: 'Google Cloud Platform (GCP)' },
  { id: 367, name: 'Microsoft Azure' },
  { id: 368, name: 'IBM Cloud' },
  { id: 369, name: 'Alibaba Cloud' },
  { id: 370, name: 'DigitalOcean' },
  { id: 371, name: 'Firebase' },
  { id: 372, name: 'Nginx' },
  { id: 373, name: 'Apache HTTP Server' },
  { id: 374, name: 'Microsoft IIS' },
  { id: 375, name: 'HAProxy' },
  { id: 376, name: 'CDN (Content Delivery Network)' },
  { id: 377, name: 'Load Balancing' },
  { id: 378, name: 'Reverse Proxy' },
  { id: 379, name: 'Web Servers Configuration' },
  { id: 380, name: 'DevOps Practices' },
  { id: 381, name: 'Agile Project Management Tools (Jira, Trello, Asana)' },
  { id: 382, name: 'Version Control Systems (Git, SVN)' },
  { id: 383, name: 'Continuous Integration/Continuous Deployment (CI/CD)' },
  { id: 384, name: 'Infrastructure as Code (IaC)' },
  {
    id: 385,
    name: 'Monitoring and Logging Tools (Prometheus, Grafana, ELK Stack)',
  },
  { id: 386, name: 'Container Orchestration' },
  { id: 387, name: 'Site Reliability Engineering (SRE)' },
  { id: 388, name: 'Incident Response' },
  { id: 389, name: 'Disaster Recovery Planning' },
  { id: 390, name: 'Compliance and Governance' },
  { id: 391, name: 'IT Service Management (ITSM)' },
  { id: 393, name: 'Customer Relationship Management (CRM) Systems' },
  { id: 394, name: 'Salesforce' },
  { id: 395, name: 'HubSpot' },
  { id: 396, name: 'Zoho CRM' },
  { id: 397, name: 'Microsoft Dynamics CRM' },
  { id: 398, name: 'Customer Support Platforms (Zendesk, Freshdesk)' },
  { id: 399, name: 'E-commerce Platforms (Shopify, WooCommerce, Magento)' },
  { id: 400, name: 'Content Management Systems (WordPress, Drupal, Joomla)' },
  { id: 401, name: 'Learning Management Systems (LMS)' },
  {
    id: 402,
    name: 'E-learning Development Tools (Moodle, Articulate Storyline)',
  },
  { id: 403, name: 'Collaboration Tools (Slack, Microsoft Teams, Zoom)' },
  { id: 404, name: 'Productivity Suites (Microsoft 365, Google Workspace)' },
  { id: 405, name: 'Version Control Systems (Git, SVN)' },
  {
    id: 406,
    name: 'Code Review Tools (GitHub Pull Requests, Bitbucket Code Insights)',
  },
  { id: 407, name: 'Static Code Analysis Tools' },
  { id: 408, name: 'Automated Testing Tools (Selenium, JUnit, Jest)' },
  { id: 409, name: 'Performance Testing Tools (Apache JMeter, LoadRunner)' },
  { id: 410, name: 'Security Testing Tools (Burp Suite, OWASP ZAP)' },
  { id: 411, name: 'Continuous Monitoring Tools' },
  { id: 412, name: 'Log Management and Analysis' },
  { id: 413, name: 'Server and Network Monitoring' },
  { id: 414, name: 'Cloud Security' },
  { id: 415, name: 'Data Encryption' },
  { id: 416, name: 'Identity and Access Management (IAM)' },
  { id: 417, name: 'Multi-Factor Authentication (MFA)' },
  { id: 418, name: 'Security Information and Event Management (SIEM)' },
  { id: 419, name: 'Security Incident Response' },
  { id: 420, name: 'Endpoint Security' },
  { id: 421, name: 'Network Security Protocols (SSL/TLS, IPSec)' },
  { id: 422, name: 'Firewalls and Intrusion Detection Systems (IDS)' },
  { id: 423, name: 'Secure Software Development Lifecycle (SDLC) Practices' },
  { id: 424, name: 'Threat Modeling' },
  { id: 425, name: 'Secure Coding Guidelines' },
  { id: 426, name: 'Vulnerability Management' },
  { id: 427, name: 'Penetration Testing' },
  { id: 428, name: 'Ethical Hacking' },
  { id: 429, name: 'Security Awareness Training' },
  { id: 430, name: 'Regulatory Compliance (GDPR, HIPAA, PCI DSS)' },
] as const
