export const skillArray = [
  { id: 0, name: '.NET', normalized: '.NET' },
  { id: 1, name: 'AB Testing', normalized: 'ABTESTING' },
  { id: 2, name: 'API Development', normalized: 'APIDEVELOPMENT' },
  { id: 3, name: 'AR Design', normalized: 'ARDESIGN' },
  { id: 4, name: 'ASP.NET', normalized: 'ASP.NET' },
  { id: 5, name: 'AWS', normalized: 'AWS' },
  { id: 6, name: 'Academic Writing', normalized: 'ACADEMICWRITING' },
  { id: 7, name: 'Account Management', normalized: 'ACCOUNTMANAGEMENT' },
  { id: 8, name: 'Adobe XD', normalized: 'ADOBEXD' },
  { id: 9, name: 'Affiliate Marketing', normalized: 'AFFILIATEMARKETING' },
  { id: 10, name: 'Agile Methodologies', normalized: 'AGILEMETHODOLOGIES' },
  { id: 11, name: 'Android Development', normalized: 'ANDROIDDEVELOPMENT' },
  { id: 13, name: 'Animation', normalized: 'ANIMATION' },
  { id: 14, name: 'B2B Sales', normalized: 'B2BSALES' },
  { id: 15, name: 'B2C Sales', normalized: 'B2CSALES' },
  { id: 16, name: 'Bash/Shell', normalized: 'BASH/SHELL' },
  { id: 17, name: 'Blogging', normalized: 'BLOGGING' },
  { id: 18, name: 'Bootstrap', normalized: 'BOOTSTRAP' },
  { id: 19, name: 'Brand Management', normalized: 'BRANDMANAGEMENT' },
  { id: 20, name: 'Budgeting', normalized: 'BUDGETING' },
  { id: 21, name: 'Business Development', normalized: 'BUSINESSDEVELOPMENT' },
  { id: 22, name: 'Business Strategy', normalized: 'BUSINESSSTRATEGY' },
  { id: 23, name: 'C', normalized: 'C' },
  { id: 24, name: 'C#', normalized: 'C#' },
  { id: 25, name: 'C++', normalized: 'C++' },
  { id: 26, name: 'CRM', normalized: 'CRM' },
  { id: 27, name: 'CSS', normalized: 'CSS' },
  { id: 29, name: 'Change Management', normalized: 'CHANGEMANAGEMENT' },
  { id: 30, name: 'Channel Sales', normalized: 'CHANNELSALES' },
  { id: 31, name: 'Cold Calling', normalized: 'COLDCALLING' },
  { id: 32, name: 'Color Theory', normalized: 'COLORTHEORY' },
  { id: 33, name: 'Conflict Resolution', normalized: 'CONFLICTRESOLUTION' },
  { id: 34, name: 'Content Marketing', normalized: 'CONTENTMARKETING' },
  { id: 35, name: 'Content Writing', normalized: 'CONTENTWRITING' },
  {
    id: 36,
    name: 'Conversion Rate Optimization',
    normalized: 'CONVERSIONRATEOPTIMIZATION',
  },
  { id: 37, name: 'Copywriting', normalized: 'COPYWRITING' },
  { id: 38, name: 'Creative Writing', normalized: 'CREATIVEWRITING' },
  { id: 39, name: 'Data Analysis', normalized: 'DATAANALYSIS' },
  {
    id: 40,
    name: 'Data-driven Decision Making',
    normalized: 'DATADRIVENDECISIONMAKING',
  },
  { id: 41, name: 'Direct Sales', normalized: 'DIRECTSALES' },
  { id: 42, name: 'Django', normalized: 'DJANGO' },
  { id: 43, name: 'Docker', normalized: 'DOCKER' },
  { id: 44, name: 'Drupal', normalized: 'DRUPAL' },
  { id: 45, name: 'Editing', normalized: 'EDITING' },
  { id: 46, name: 'Email Marketing', normalized: 'EMAILMARKETING' },
  {
    id: 47,
    name: 'Emotional Intelligence',
    normalized: 'EMOTIONALINTELLIGENCE',
  },
  { id: 48, name: 'Enterprise Sales', normalized: 'ENTERPRISESALES' },
  { id: 49, name: 'Facebook Ads', normalized: 'FACEBOOKADS' },
  { id: 50, name: 'Figma', normalized: 'FIGMA' },
  { id: 51, name: 'Flutter', normalized: 'FLUTTER' },
  { id: 52, name: 'Frontend Development', normalized: 'FRONTENDDEVELOPMENT' },
  { id: 53, name: 'Go', normalized: 'GO' },
  { id: 54, name: 'Google Adwords', normalized: 'GOOGLEADWORDS' },
  { id: 55, name: 'Google Analytics', normalized: 'GOOGLEANALYTICS' },
  { id: 56, name: 'Google Tag Manager', normalized: 'GOOGLETAGMANAGER' },
  { id: 57, name: 'Grant Writing', normalized: 'GRANTWRITING' },
  { id: 58, name: 'Graphic Design', normalized: 'GRAPHICDESIGN' },
  { id: 59, name: 'HTML', normalized: 'HTML' },
  { id: 61, name: 'ITIL', normalized: 'ITIL' },
  { id: 62, name: 'Illustrator', normalized: 'ILLUSTRATOR' },
  { id: 63, name: 'InDesign', normalized: 'INDESIGN' },
  { id: 64, name: 'Inbound Sales', normalized: 'INBOUNDSALES' },
  { id: 65, name: 'Interaction Design', normalized: 'INTERACTIONDESIGN' },
  { id: 66, name: 'Java', normalized: 'JAVA' },
  { id: 67, name: 'JavaScript', normalized: 'JAVASCRIPT' },
  { id: 68, name: 'Kanban', normalized: 'KANBAN' },
  { id: 71, name: 'Leadership', normalized: 'LEADERSHIP' },
  { id: 72, name: 'Lean', normalized: 'LEAN' },
  { id: 73, name: 'Market Research', normalized: 'MARKETRESEARCH' },
  { id: 74, name: 'Marketing Automation', normalized: 'MARKETINGAUTOMATION' },
  { id: 75, name: 'Marketing Strategy', normalized: 'MARKETINGSTRATEGY' },
  { id: 76, name: 'Medical Writing', normalized: 'MEDICALWRITING' },
  { id: 77, name: 'Mobile Advertising', normalized: 'MOBILEADVERTISING' },
  { id: 78, name: 'MongoDB', normalized: 'MONGODB' },
  { id: 79, name: 'Motion Graphics', normalized: 'MOTIONGRAPHICS' },
  { id: 80, name: 'MySQL', normalized: 'MYSQL' },
  { id: 81, name: 'Negotiation', normalized: 'NEGOTIATION' },
  { id: 82, name: 'Newsletters', normalized: 'NEWSLETTERS' },
  { id: 83, name: 'Objective-C', normalized: 'OBJECTIVEC' },
  { id: 84, name: 'Outbound Sales', normalized: 'OUTBOUNDSALES' },
  { id: 85, name: 'PHP', normalized: 'PHP' },
  { id: 86, name: 'PPC', normalized: 'PPC' },
  {
    id: 87,
    name: 'Performance Management',
    normalized: 'PERFORMANCEMANAGEMENT',
  },
  { id: 88, name: 'Perl', normalized: 'PERL' },
  { id: 89, name: 'Photoshop', normalized: 'PHOTOSHOP' },
  { id: 90, name: 'Press Releases', normalized: 'PRESSRELEASES' },
  { id: 91, name: 'Prince2', normalized: 'PRINCE2' },
  { id: 92, name: 'Project Management', normalized: 'PROJECTMANAGEMENT' },
  { id: 93, name: 'Proofreading', normalized: 'PROOFREADING' },
  { id: 94, name: 'Prototyping', normalized: 'PROTOTYPING' },
  { id: 95, name: 'Public Relations', normalized: 'PUBLICRELATIONS' },
  { id: 96, name: 'Python', normalized: 'PYTHON' },
  { id: 97, name: 'Resource Management', normalized: 'RESOURCEMANAGEMENT' },
  { id: 98, name: 'Responsive Design', normalized: 'RESPONSIVEDESIGN' },
  { id: 99, name: 'Risk Management', normalized: 'RISKMANAGEMENT' },
  { id: 100, name: 'Ruby on Rails', normalized: 'RUBYONRAILS' },
  { id: 101, name: 'Ruby', normalized: 'RUBY' },
  { id: 102, name: 'Rust', normalized: 'RUST' },
  { id: 103, name: 'SEM', normalized: 'SEM' },
  { id: 104, name: 'SEO Writing', normalized: 'SEOWRITING' },
  { id: 105, name: 'SEO', normalized: 'SEO' },
  { id: 106, name: 'SQL', normalized: 'SQL' },
  {
    id: 107,
    name: 'SaaS Sales',
    normalized: 'SAASSALES',
  },
  {
    id: 108,
    name: 'Sales Analytics',
    normalized: 'SALESANALYTICS',
  },
  {
    id: 109,
    name: 'Sales Closing',
    normalized: 'SALESCLOSING',
  },
  {
    id: 110,
    name: 'Sales Enablement',
    normalized: 'SALESENABLEMENT',
  },
  {
    id: 111,
    name: 'Sales Forecasting',
    normalized: 'SALESFORECASTING',
  },
  {
    id: 112,
    name: 'Sales Management',
    normalized: 'SALESMANAGEMENT',
  },
  {
    id: 113,
    name: 'Sales Operations',
    normalized: 'SALESOPERATIONS',
  },
  {
    id: 114,
    name: 'Sales Process',
    normalized: 'SALESPROCESS',
  },
  {
    id: 115,
    name: 'Sales Strategy',
    normalized: 'SALESSTRATEGY',
  },
  {
    id: 116,
    name: 'Salesforce',
    normalized: 'SALESFORCE',
  },
  {
    id: 117,
    name: 'Scala',
    normalized: 'SCALA',
  },
  {
    id: 118,
    name: 'Scrum',
    normalized: 'SCRUM',
  },
  {
    id: 119,
    name: 'Sketch',
    normalized: 'SKETCH',
  },
  {
    id: 120,
    name: 'Social Media Marketing',
    normalized: 'SOCIALMEDIAMARKETING',
  },
  {
    id: 121,
    name: 'Strategic Planning',
    normalized: 'STRATEGICPLANNING',
  },
  { id: 122, name: 'Swift', normalized: 'SWIFT' },
  {
    id: 123,
    name: 'Team Building',
    normalized: 'TEAMBUILDING',
  },
  {
    id: 124,
    name: 'Technical Writing',
    normalized: 'TECHNICALWRITING',
  },
  {
    id: 125,
    name: 'Telesales',
    normalized: 'TELESALES',
  },
  { id: 126, name: 'TypeScript', normalized: 'TYPESCRIPT' },
  { id: 127, name: 'Typography', normalized: 'TYPOGRAPHY' },
  { id: 128, name: 'UI Design', normalized: 'UIDESIGN' },
  { id: 129, name: 'UX Design', normalized: 'UXDESIGN' },
  { id: 130, name: 'UX Research', normalized: 'UXRESEARCH' },
  { id: 131, name: 'Video Marketing', normalized: 'VIDEOMARKETING' },
  { id: 132, name: 'Viral Marketing', normalized: 'VIRALMARKETING' },
  { id: 133, name: 'Vue', normalized: 'VUE' },
  { id: 134, name: 'Waterfall', normalized: 'WATERFALL' },
  { id: 135, name: 'Web Analytics', normalized: 'WEBANALYTICS' },
  { id: 136, name: 'Web Content Writing', normalized: 'WEBCONTENTWRITING' },
  { id: 137, name: 'Web Design', normalized: 'WEBDESIGN' },
  { id: 138, name: 'Web Development', normalized: 'WEBDEVELOPMENT' },
  { id: 139, name: 'Whitepapers', normalized: 'WHITEPAPERS' },
  { id: 140, name: 'Wireframing', normalized: 'WIREFRAMING' },
  { id: 141, name: 'WordPress', normalized: 'WORDPRESS' },
  { id: 142, name: 'YouTube Marketing', normalized: 'YOUTUBEMARKETING' },
  { id: 143, name: 'iOS Development', normalized: 'IOSDEVELOPMENT' },
  { id: 144, name: 'Frontend', normalized: 'FRONTEND' },
  { id: 145, name: 'Backend', normalized: 'BACKEND' },
  { id: 146, name: 'React', normalized: 'REACT' },
  { id: 147, name: 'Angular', normalized: 'ANGULAR' },
  { id: 149, name: 'Astro.', normalized: 'ASTRO' },
  { id: 150, name: 'Svelte', normalized: 'SVELTE' },
  { id: 151, name: 'Ember', normalized: 'EMBER' },
  { id: 152, name: 'Next', normalized: 'NEXT' },
  { id: 153, name: 'Express', normalized: 'EXPRESS' },
  { id: 154, name: 'Meteor', normalized: 'METEOR' },
  { id: 155, name: 'Nest', normalized: 'NEST' },
  { id: 156, name: 'Aurelia', normalized: 'AURELIA' },
  { id: 157, name: 'Remix', normalized: 'REMIX' },
  { id: 161, name: 'Oracle JDK', normalized: 'ORACLEJDK' },
  { id: 162, name: 'OpenJDK', normalized: 'OPENJDK' },
  { id: 163, name: 'Eclipse IDE', normalized: 'ECLIPSEIDE' },
  { id: 164, name: 'IntelliJ IDEA', normalized: 'INTELLIJIDEA' },
  { id: 165, name: 'NetBeans IDE', normalized: 'NETBEANSIDE' },
  { id: 166, name: 'Apache Maven', normalized: 'APACHEMAVEN' },
  { id: 167, name: 'Apache Ant', normalized: 'APACHEANT' },
  { id: 168, name: 'Gradle', normalized: 'GRADLE' },
  { id: 169, name: 'Spring Framework', normalized: 'SPRING' },
  { id: 175, name: 'Hibernate ORM', normalized: 'HIBERNATEORM' },
  { id: 176, name: 'Struts Framework', normalized: 'STRUTSFRAMEWORK' },
  { id: 178, name: 'Play Framework', normalized: 'PLAYFRAMEWORK' },
  { id: 179, name: 'Grails Framework', normalized: 'GRAILSFRAMEWORK' },
  { id: 180, name: 'Apache Wicket', normalized: 'APACHEWICKET' },
  { id: 181, name: 'Servlets', normalized: 'SERVLETS' },
  { id: 183, name: 'WebSocket API', normalized: 'WEBSOCKETAPI' },
  { id: 184, name: 'JAX-RS', normalized: 'JAXRS' },
  { id: 185, name: 'JSON-B', normalized: 'JSONB' },
  { id: 187, name: 'Session Beans', normalized: 'SESSIONBEANS' },
  { id: 188, name: 'Message-Driven Beans', normalized: 'MESSAGEDRIVENBEANS' },
  { id: 189, name: 'Entity Beans', normalized: 'ENTITYBEANS' },
  { id: 192, name: 'JDBC', normalized: 'JDBC' },
  { id: 193, name: 'JUnit Testing', normalized: 'JUNITTESTING' },
  { id: 194, name: 'TestNG Testing', normalized: 'TESTNGTESTING' },
  { id: 195, name: 'SLF4J Logging', normalized: 'SLF4JLOGGING' },
  { id: 196, name: 'Log4j Logging', normalized: 'LOG4JLOGGING' },
  { id: 197, name: 'RMI', normalized: 'RMI' },
  { id: 200, name: 'Scala Language', normalized: 'SCALALANGUAGE' },
  { id: 206, name: 'Entity Framework', normalized: 'ENTITYFRAMEWORK' },
  { id: 207, name: 'Entity Framework Core', normalized: 'ENTITYFRAMEWORKCORE' },
  { id: 208, name: 'Blazor', normalized: 'BLAZOR' },
  { id: 209, name: 'Windows Forms', normalized: 'WINDOWSFORMS' },
  { id: 210, name: 'Xamarin', normalized: 'XAMARIN' },
  { id: 211, name: 'Unity3D', normalized: 'UNITY3D' },
  { id: 212, name: 'PowerShell', normalized: 'POWERSHELL' },
  { id: 213, name: 'LINQ', normalized: 'LINQ' },
  { id: 214, name: 'Kubernetes', normalized: 'KUBERNETES' },
  { id: 215, name: 'Amazon EC2', normalized: 'AMAZONEC2' },
  { id: 217, name: 'Amazon Lightsail', normalized: 'AMAZONLIGHTSAIL' },
  { id: 218, name: 'AWS Lambda', normalized: 'AWSLAMBDA' },
  { id: 219, name: 'Amazon S3', normalized: 'AMAZONS3' },
  { id: 220, name: 'Amazon EBS', normalized: 'AMAZONEBS' },
  { id: 221, name: 'Amazon Glacier', normalized: 'AMAZONGLACIER' },
  {
    id: 222,
    name: 'Amazon S3 Glacier Deep Archive',
    normalized: 'AMAZONS3GLACIERDEEPARCHIVE',
  },
  { id: 223, name: 'Amazon RDS', normalized: 'AMAZONRDS' },
  { id: 224, name: 'Amazon DynamoDB', normalized: 'AMAZONDYNAMODB' },
  { id: 225, name: 'Amazon Redshift', normalized: 'AMAZONREDSHIFT' },
  { id: 226, name: 'Amazon Aurora', normalized: 'AMAZONAURORA' },
  { id: 227, name: 'Amazon VPC', normalized: 'AMAZONVPC' },
  { id: 228, name: 'Amazon Route 53', normalized: 'AMAZONROUTE53' },
  { id: 229, name: 'AWS Direct Connect', normalized: 'AWSDIRECTCONNECT' },
  { id: 230, name: 'Amazon API Gateway', normalized: 'AMAZONAPIGATEWAY' },
  {
    id: 231,
    name: 'AWS Identity and Access Management (IAM)',
    normalized: 'AWSIDENTITYANDACCESSMANAGEMENTIAM',
  },
  {
    id: 232,
    name: 'AWS Key Management Service (KMS)',
    normalized: 'AWSKEYMANAGEMENTSERVICEKMS',
  },
  { id: 233, name: 'Amazon Cognito', normalized: 'AMAZONCOGNITO' },
  { id: 234, name: 'Amazon SageMaker', normalized: 'AMAZONSAGEMAKER' },
  { id: 235, name: 'AWS Comprehend', normalized: 'AWSCOMPREHEND' },
  { id: 236, name: 'AWS Rekognition', normalized: 'AWSREKOGNITION' },
  { id: 237, name: 'Amazon Polly', normalized: 'AMAZONPOLLY' },
  { id: 238, name: 'Amazon Lex', normalized: 'AMAZONLEX' },
  { id: 239, name: 'AWS CodePipeline', normalized: 'AWSCODEPIPELINE' },
  { id: 240, name: 'AWS CodeBuild', normalized: 'AWSCODEBUILD' },
  { id: 241, name: 'AWS CodeDeploy', normalized: 'AWSCODEDEPLOY' },
  { id: 242, name: 'AWS CodeCommit', normalized: 'AWSCODECOMMIT' },
  { id: 243, name: 'AWS Cloud9', normalized: 'AWSCLOUD9' },
  { id: 244, name: 'Amazon CloudWatch', normalized: 'AMAZONCLOUDWATCH' },
  { id: 245, name: 'AWS CloudTrail', normalized: 'AWSCLOUDTRAIL' },
  { id: 246, name: 'AWS Config', normalized: 'AWSCONFIG' },
  { id: 247, name: 'AWS Systems Manager', normalized: 'AWSSYSTEMSMANAGER' },
  { id: 248, name: 'AWS IoT Core', normalized: 'AWSIOTCORE' },
  { id: 249, name: 'AWS IoT Greengrass', normalized: 'AWSIOTGREENGRASS' },
  { id: 250, name: 'Amazon FreeRTOS', normalized: 'AMAZONFREERTOS' },
  { id: 251, name: 'Amazon ECS', normalized: 'AMAZONECS' },
  { id: 252, name: 'Amazon EKS', normalized: 'AMAZONEKS' },
  { id: 253, name: 'AWS Fargate', normalized: 'AWSFARGATE' },
  { id: 254, name: 'AWS Step Functions', normalized: 'AWSSTEPFUNCTIONS' },
  { id: 255, name: 'Amazon EventBridge', normalized: 'AMAZONEVENTBRIDGE' },
  { id: 256, name: 'Amazon Athena', normalized: 'AMAZONATHENA' },
  { id: 257, name: 'Amazon EMR', normalized: 'AMAZONEMR' },
  { id: 258, name: 'Amazon Kinesis', normalized: 'AMAZONKINESIS' },
  { id: 259, name: 'Amazon QuickSight', normalized: 'AMAZONQUICKSIGHT' },
  { id: 260, name: 'Amazon GameLift', normalized: 'AMAZONGAMELIFT' },
  {
    id: 261,
    name: 'Amazon Managed Blockchain',
    normalized: 'AMAZONMANAGEDBLOCKCHAIN',
  },
  { id: 262, name: 'Amazon Sumerian', normalized: 'AMAZONSUMERIAN' },
  { id: 263, name: 'Elixir', normalized: 'ELIXIR' },
  { id: 264, name: 'Phoenix Framework', normalized: 'PHOENIXFRAMEWORK' },
  { id: 265, name: 'Absinthe GraphQL', normalized: 'ABSINTHEGRAPHQL' },
  { id: 266, name: 'Nerves Framework', normalized: 'NERVESFRAMEWORK' },
  { id: 267, name: 'Mix Build Tool', normalized: 'MIXBUILDTOOL' },
  { id: 268, name: 'Erlang OTP', normalized: 'ERLANGOTP' },
  { id: 269, name: 'RabbitMQ', normalized: 'RABBITMQ' },
  { id: 270, name: 'Rebar3 Build Tool', normalized: 'REBAR3BUILDTOOL' },
  { id: 271, name: 'Erlang Web', normalized: 'ERLANGWEB' },
  {
    id: 272,
    name: 'LFE (Lisp Flavored Erlang)',
    normalized: 'LFELISPFLAVOREDERLANG',
  },
  { id: 274, name: 'Laravel', normalized: 'LARAVEL' },
  { id: 275, name: 'Symfony', normalized: 'SYMFONY' },
  { id: 276, name: 'CodeIgniter', normalized: 'CODEIGNITER' },
  { id: 277, name: 'Yii', normalized: 'YII' },
  { id: 278, name: 'Zend Framework', normalized: 'ZENDFRAMEWORK' },
  { id: 279, name: 'Phalcon', normalized: 'PHALCON' },
  { id: 280, name: 'Laminas', normalized: 'LAMINAS' },
  { id: 281, name: 'CakePHP', normalized: 'CAKEPHP' },
  { id: 282, name: 'Slim', normalized: 'SLIM' },
  { id: 283, name: 'WordPress (Plugin Development)', normalized: 'WORDPRESS' },
  { id: 284, name: 'Drupal (Module Development)', normalized: 'DRUPAL' },
  { id: 285, name: 'Joomla (Extension Development)', normalized: 'JOOMLA' },
  { id: 286, name: 'Rust', normalized: 'RUST' },
  { id: 287, name: 'Dart', normalized: 'DART' },
  { id: 288, name: 'Flutter', normalized: 'FLUTTER' },
  { id: 289, name: 'Swift', normalized: 'SWIFT' },
  { id: 290, name: 'Kotlin', normalized: 'KOTLIN' },
  { id: 291, name: 'Objective-C', normalized: 'OBJECTIVEC' },
  { id: 292, name: 'React Native', normalized: 'REACTNATIVE' },
  { id: 293, name: 'Ionic Framework', normalized: 'IONICFRAMEWORK' },
  { id: 294, name: 'Cordova', normalized: 'CORDOVA' },
  { id: 295, name: 'PhoneGap', normalized: 'PHONEGAP' },
  { id: 296, name: 'Xamarin', normalized: 'XAMARIN' },
  { id: 297, name: 'TensorFlow', normalized: 'TENSORFLOW' },
  { id: 298, name: 'PyTorch', normalized: 'PYTORCH' },
  { id: 299, name: 'Keras', normalized: 'KERAS' },
  {
    id: 300,
    name: 'Natural Language Processing (NLP)',
    normalized: 'NATURALLANGUAGEPROCESSING',
  },
  {
    id: 301,
    name: 'Reinforcement Learning',
    normalized: 'REINFORCEMENTLEARNING',
  },
  { id: 302, name: 'Unity3D', normalized: 'UNITY3D' },
  { id: 303, name: 'Unreal Engine', normalized: 'UNREALENGINE' },
  { id: 304, name: 'Game Development', normalized: 'GAMEDEVELOPMENT' },
  { id: 305, name: 'Virtual Reality (VR)', normalized: 'VIRTUALREALITY' },
  { id: 306, name: 'Augmented Reality (AR)', normalized: 'AUGMENTEDREALITY' },
  {
    id: 307,
    name: 'Blockchain Development',
    normalized: 'BLOCKCHAINDEVELOPMENT',
  },
  { id: 308, name: 'Smart Contracts', normalized: 'SMARTCONTRACTS' },
  { id: 309, name: 'Solidity', normalized: 'SOLIDITY' },
  { id: 310, name: 'Web3', normalized: 'WEB3' },
  { id: 311, name: 'Truffle Framework', normalized: 'TRUFFLEFRAMEWORK' },
  { id: 312, name: 'IPFS (InterPlanetary File System)', normalized: 'IPFS' },
  {
    id: 313,
    name: 'Decentralized Finance (DeFi)',
    normalized: 'DECENTRALIZEDFINANCE',
  },
  {
    id: 314,
    name: 'Non-Fungible Tokens (NFTs)',
    normalized: 'NONFUNGIBLETOKENS',
  },
  { id: 315, name: 'Cybersecurity', normalized: 'CYBERSECURITY' },
  { id: 316, name: 'Ethical Hacking', normalized: 'ETHICALHACKING' },
  { id: 317, name: 'Penetration Testing', normalized: 'PENETRATIONTESTING' },
  { id: 318, name: 'Cryptography', normalized: 'CRYPTOGRAPHY' },
  { id: 319, name: 'Network Security', normalized: 'NETWORKSECURITY' },
  { id: 320, name: 'OWASP Top Ten', normalized: 'OWASPTOPTEN' },
  {
    id: 321,
    name: 'Secure Coding Practices',
    normalized: 'SECURECODINGPRACTICES',
  },
  { id: 322, name: 'Computer Vision', normalized: 'COMPUTERVISION' },
  { id: 323, name: 'Internet of Things (IoT)', normalized: 'INTERNETOFTHINGS' },
  { id: 324, name: 'Edge Computing', normalized: 'EDGECOMPUTING' },
  { id: 325, name: 'Big Data', normalized: 'BIGDATA' },
  { id: 326, name: 'Hadoop', normalized: 'HADOOP' },
  { id: 327, name: 'Spark', normalized: 'SPARK' },
  {
    id: 328,
    name: 'NoSQL Databases (MongoDB, Cassandra, Couchbase)',
    normalized: 'NOSQLDATABASES',
  },
  { id: 329, name: 'Data Warehousing', normalized: 'DATAWAREHOUSING' },
  { id: 330, name: 'Data Mining', normalized: 'DATAMINING' },
  { id: 331, name: 'Machine Learning', normalized: 'MACHINELEARNING' },
  { id: 332, name: 'Deep Learning', normalized: 'DEEPLEARNING' },
  { id: 333, name: 'Computer Graphics', normalized: 'COMPUTERGRAPHICS' },
  { id: 334, name: 'Game Design', normalized: 'GAMEDESIGN' },
  { id: 335, name: 'Game Mechanics', normalized: 'GAMEMECHANICS' },
  {
    id: 336,
    name: 'User Interface (UI) Design',
    normalized: 'USERINTERFACEDESIGN',
  },
  {
    id: 337,
    name: 'User Experience (UX) Design',
    normalized: 'USEREXPERIENCEDESIGN',
  },
  {
    id: 338,
    name: 'Human-Computer Interaction (HCI)',
    normalized: 'HUMANCOMPUTERINTERACTION',
  },
  { id: 339, name: 'Responsive Web Design', normalized: 'RESPONSIVEWEBDESIGN' },
  {
    id: 340,
    name: 'Progressive Web Apps (PWA)',
    normalized: 'PROGRESSIVEWEBAPPS',
  },
  { id: 341, name: 'WebAssembly', normalized: 'WEBASSEMBLY' },
  {
    id: 342,
    name: 'Serverless Architecture',
    normalized: 'SERVERLESSARCHITECTURE',
  },
  {
    id: 343,
    name: 'Microservices Architecture',
    normalized: 'MICROSERVICESARCHITECTURE',
  },
  { id: 344, name: 'GraphQL', normalized: 'GRAPHQL' },
  { id: 345, name: 'RESTful APIs', normalized: 'RESTFULAPIS' },
  { id: 346, name: 'SOAP', normalized: 'SOAP' },
  { id: 347, name: 'JSON-RPC', normalized: 'JSONRPC' },
  { id: 348, name: 'XML-RPC', normalized: 'XMLRPC' },
  { id: 349, name: 'WebSockets', normalized: 'WEBSOCKETS' },
  { id: 350, name: 'OAuth', normalized: 'OAUTH' },
  { id: 351, name: 'JWT (JSON Web Tokens)', normalized: 'JWT' },
  {
    id: 352,
    name: 'GraphQL Subscriptions',
    normalized: 'GRAPHQLSUBSCRIPTIONS',
  },
  { id: 353, name: 'gRPC', normalized: 'GRPC' },
  { id: 354, name: 'Apache Kafka', normalized: 'APACHEKAFKA' },
  { id: 355, name: 'RabbitMQ', normalized: 'RABBITMQ' },
  { id: 356, name: 'AWS SQS (Simple Queue Service)', normalized: 'AWSSQS' },
  { id: 357, name: 'Docker Swarm', normalized: 'DOCKERSWARM' },
  { id: 358, name: 'Kubernetes', normalized: 'KUBERNETES' },
  { id: 359, name: 'Jenkins', normalized: 'JENKINS' },
  { id: 360, name: 'Travis CI', normalized: 'TRAVISCI' },
  { id: 361, name: 'GitLab CI/CD', normalized: 'GITLABCICD' },
  { id: 362, name: 'GitHub Actions', normalized: 'GITHUBACTIONS' },
  { id: 363, name: 'Heroku', normalized: 'HEROKU' },
  { id: 364, name: 'Netlify', normalized: 'NETLIFY' },
  { id: 365, name: 'Vercel', normalized: 'VERCEL' },
  {
    id: 366,
    name: 'Google Cloud Platform (GCP)',
    normalized: 'GOOGLECLOUDPLATFORM',
  },
  { id: 367, name: 'Microsoft Azure', normalized: 'MICROSOFTAZURE' },
  { id: 368, name: 'IBM Cloud', normalized: 'IBMCloud' },
  { id: 369, name: 'Alibaba Cloud', normalized: 'ALIBABACLOUD' },
  { id: 370, name: 'DigitalOcean', normalized: 'DIGITALOCEAN' },
  { id: 371, name: 'Firebase', normalized: 'FIREBASE' },
  { id: 372, name: 'Nginx', normalized: 'NGINX' },
  { id: 373, name: 'Apache HTTP Server', normalized: 'APACHEHTTPSERVER' },
  { id: 374, name: 'Microsoft IIS', normalized: 'MICROSOFTIIS' },
  { id: 375, name: 'HAProxy', normalized: 'HAPROXY' },
  { id: 376, name: 'CDN (Content Delivery Network)', normalized: 'CDN' },
  { id: 377, name: 'Load Balancing', normalized: 'LOADBALANCING' },
  { id: 378, name: 'Reverse Proxy', normalized: 'REVERSEPROXY' },
  {
    id: 379,
    name: 'Web Servers Configuration',
    normalized: 'WEBSERVERSCONFIGURATION',
  },
  { id: 380, name: 'DevOps Practices', normalized: 'DEVOPSPRACTICES' },
  {
    id: 381,
    name: 'Agile Project Management Tools (Jira, Trello, Asana)',
    normalized: 'AGILEPROJECTMANAGEMENTTOOLS',
  },
  {
    id: 382,
    name: 'Version Control Systems (Git, SVN)',
    normalized: 'VERSIONCONTROLSYSTEMS',
  },
  {
    id: 383,
    name: 'Continuous Integration/Continuous Deployment (CI/CD)',
    normalized: 'CONTINUOUSINTEGRATIONCONTINUOUSDEPLOYMENT',
  },
  {
    id: 384,
    name: 'Infrastructure as Code (IaC)',
    normalized: 'INFRASTRUCTUREASCODE',
  },
  {
    id: 385,
    name: 'Monitoring and Logging Tools (Prometheus, Grafana, ELK Stack)',
    normalized: 'MONITORINGANDLOGGINGTOOLS',
  },
  {
    id: 386,
    name: 'Container Orchestration',
    normalized: 'CONTAINERORCHESTRATION',
  },
  {
    id: 387,
    name: 'Site Reliability Engineering (SRE)',
    normalized: 'SITERELIABILITYENGINEERING',
  },
  { id: 388, name: 'Incident Response', normalized: 'INCIDENTRESPONSE' },
  {
    id: 389,
    name: 'Disaster Recovery Planning',
    normalized: 'DISASTERRECOVERYPLANNING',
  },
  {
    id: 390,
    name: 'Compliance and Governance',
    normalized: 'COMPLIANCEANDGOVERNANCE',
  },
  {
    id: 391,
    name: 'IT Service Management (ITSM)',
    normalized: 'ITSERVICEMANAGEMENT',
  },
  {
    id: 393,
    name: 'Customer Relationship Management (CRM) Systems',
    normalized: 'CUSTOMERRELATIONSHIPMANAGEMENTSYSTEMS',
  },
  { id: 394, name: 'Salesforce', normalized: 'SALESFORCE' },
  { id: 395, name: 'HubSpot', normalized: 'HUBSPOT' },
  { id: 396, name: 'Zoho CRM', normalized: 'ZOHOCRM' },
  {
    id: 397,
    name: 'Microsoft Dynamics CRM',
    normalized: 'MICROSOFTDYNAMICSCRM',
  },
  {
    id: 398,
    name: 'Customer Support Platforms (Zendesk, Freshdesk)',
    normalized: 'CUSTOMERSUPPORTPLATFORMS',
  },
  {
    id: 399,
    name: 'E-commerce Platforms (Shopify, WooCommerce, Magento)',
    normalized: 'ECOMMERCEPLATFORMS',
  },
  {
    id: 400,
    name: 'Content Management Systems (WordPress, Drupal, Joomla)',
    normalized: 'CONTENTMANAGEMENTSYSTEMS',
  },
  {
    id: 401,
    name: 'Learning Management Systems (LMS)',
    normalized: 'LEARNINGMANAGEMENTSYSTEMS',
  },
  {
    id: 402,
    name: 'E-learning Development Tools (Moodle, Articulate Storyline)',
    normalized: 'ELEARNINGDEVELOPMENTTOOLS',
  },
  {
    id: 403,
    name: 'Collaboration Tools (Slack, Microsoft Teams, Zoom)',
    normalized: 'COLLABORATIONTOOLS',
  },
  {
    id: 404,
    name: 'Productivity Suites (Microsoft 365, Google Workspace)',
    normalized: 'PRODUCTIVITYSUITES',
  },
  {
    id: 405,
    name: 'Version Control Systems (Git, SVN)',
    normalized: 'VERSIONCONTROLSYSTEMS',
  },
  {
    id: 406,
    name: 'Code Review Tools (GitHub Pull Requests, Bitbucket Code Insights)',
    normalized: 'CODEREVIEWTOOLS',
  },
  {
    id: 407,
    name: 'Static Code Analysis Tools',
    normalized: 'STATICCODEANALYSISTOOLS',
  },
  {
    id: 408,
    name: 'Automated Testing Tools (Selenium, JUnit, Jest)',
    normalized: 'AUTOMATEDTESTINGTOOLS',
  },
  {
    id: 409,
    name: 'Performance Testing Tools (Apache JMeter, LoadRunner)',
    normalized: 'PERFORMANCETESTINGTOOLS',
  },
  {
    id: 410,
    name: 'Security Testing Tools (Burp Suite, OWASP ZAP)',
    normalized: 'SECURITYTESTINGTOOLS',
  },
  {
    id: 411,
    name: 'Continuous Monitoring Tools',
    normalized: 'CONTINUOUSMONITORINGTOOLS',
  },
  {
    id: 412,
    name: 'Log Management and Analysis',
    normalized: 'LOGMANAGEMENTANDANALYSIS',
  },
  {
    id: 413,
    name: 'Server and Network Monitoring',
    normalized: 'SERVERANDNETWORKMONITORING',
  },
  { id: 414, name: 'Cloud Security', normalized: 'CLOUDSECURITY' },
  { id: 415, name: 'Data Encryption', normalized: 'DATAENCRYPTION' },
  {
    id: 416,
    name: 'Identity and Access Management (IAM)',
    normalized: 'IDENTITYANDACCESSMANAGEMENT',
  },
  {
    id: 417,
    name: 'Multi-Factor Authentication (MFA)',
    normalized: 'MULTIFACTORAUTHENTICATION',
  },
  {
    id: 418,
    name: 'Security Information and Event Management (SIEM)',
    normalized: 'SECURITYINFORMATIONANDEVENTMANAGEMENT',
  },
  {
    id: 419,
    name: 'Security Incident Response',
    normalized: 'SECURITYINCIDENTRESPONSE',
  },
  { id: 420, name: 'Endpoint Security', normalized: 'ENDPOINTSECURITY' },
  {
    id: 421,
    name: 'Network Security Protocols (SSL/TLS, IPSec)',
    normalized: 'NETWORKSECURITYPROTOCOLS',
  },
  {
    id: 422,
    name: 'Firewalls and Intrusion Detection Systems (IDS)',
    normalized: 'FIREWALLSANDINTRUSIONDETECTIONSYSTEMS',
  },
  {
    id: 423,
    name: 'Secure Software Development Lifecycle (SDLC) Practices',
    normalized: 'SECURESOFTWAREDEVELOPMENTLIFECYCLEPRACTICES',
  },
  { id: 424, name: 'Threat Modeling', normalized: 'THREATMODELING' },
  {
    id: 425,
    name: 'Secure Coding Guidelines',
    normalized: 'SECURECODINGGUIDELINES',
  },
  {
    id: 426,
    name: 'Vulnerability Management',
    normalized: 'VULNERABILITYMANAGEMENT',
  },
  { id: 427, name: 'Penetration Testing', normalized: 'PENETRATIONTESTING' },
  { id: 428, name: 'Ethical Hacking', normalized: 'ETHICALHACKING' },
  {
    id: 429,
    name: 'Security Awareness Training',
    normalized: 'SECURITYAWARENESSTRAINING',
  },
  {
    id: 430,
    name: 'Regulatory Compliance (GDPR, HIPAA, PCI DSS)',
    normalized: 'REGULATORYCOMPLIANCE',
  },
  { id: 431, name: 'VR Design', normalized: 'VRDESIGN' },
  {
    id: 432,
    name: 'MongoDB',
    normalized: 'MONGODB',
  },
  {
    id: 433,
    name: 'Cassandra',
    normalized: 'CASSANDRA',
  },
  {
    id: 434,
    name: 'Couchbas',
    normalized: 'COUCHBAS',
  },
  {
    id: 435,
    name: 'GitHub',
    normalized: 'GITHUB',
  },
  {
    id: 436,
    name: 'Tests',
    normalized: 'TESTS',
  },
  {
    id: 437,
    name: 'Tdd',
    normalized: 'TDD',
  },
  {
    id: 438,
    name: 'JQuery',
    normalized: 'JQUERY',
  },
  {
    id: 439,
    name: 'Jest',
    normalized: 'JEST',
  },
  {
    id: 440,
    name: 'Terraform',
    normalized: 'TERRAFORM',
  },
  {
    id: 441,
    name: 'SaaS',
    normalized: 'SAAS',
  },
  {
    id: 442,
    name: 'Webpack',
    normalized: 'WEBPACK',
  },
  {
    id: 443,
    name: 'Babel',
    normalized: 'BABEL',
  },
  {
    id: 444,
    name: 'Postgres',
    normalized: 'POSTGRES',
  },
  {
    id: 445,
    name: 'Web Scraping',
    normalized: 'WEBSCRAPING',
  },
  {
    id: 446,
    name: 'Playwright',
    normalized: 'PLAYWRIGHT',
  },
  {
    id: 447,
    name: 'Web3',
    normalized: 'WEB3',
  },
  {
    id: 448,
    name: 'Node',
    normalized: 'NODE',
  },
  {
    id: 449,
    name: 'CI',
    normalized: 'CI',
  },
  {
    id: 450,
    name: 'CD',
    normalized: 'CD',
  },
  {
    id: 451,
    name: 'Redis',
    normalized: 'REDIS',
  },
  {
    id: 452,
    name: 'Elasticsearch',
    normalized: 'ELASTICSEARCH',
  },
  {
    id: 453,
    name: 'DevOps',
    normalized: 'DEVOPS',
  },
  {
    id: 454,
    name: 'Linux',
    normalized: 'LINUX',
  },
  {
    id: 455,
    name: 'Postgres SQL',
    normalized: 'POSTGRESQL',
  },
  {
    id: 456,
    name: 'Spring Boot',
    normalized: 'SPRINGBOOT',
  },
  {
    id: 457,
    name: 'Oracle',
    normalized: 'ORACLE',
  },
  {
    id: 458,
    name: 'SQL Server',
    normalized: 'SQLSERVER',
  },
] as const
