import { Opening } from 'shared/src/email/openings-email/Opening'
import { Openings } from '../Openings'

const localOpenings: Opening[] = [
  {
    title: 'Pessoa Desenvolvedora Júnior (Kotlin)',
    company: 'DB1 Group',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Kotlin', 'SpringBoot', 'Postgresql', 'JUnit5', 'ReactJS'],
    headerInfo: 'Júnior', // nao achei tempo minimo
    url: 'https://db1group.pinpointhq.com/pt-BR/postings/3bfac84e-f557-4a4b-b5fb-f70d4ae9d4c2',
  },
  {
    company: 'OLX Brasil',
    title: 'Pessoa Desenvolvedora Frontend Júnior',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Javascript', 'Typescript', 'React', 'Git'],
    headerInfo: 'Vaga Afirmativa para Mulheres',
    url: 'https://jobs.lever.co/neon/50141241-0a84-4540-b4fd-38546fffe6c2',
  },
  {
    company: 'THE CODE',
    title: 'Dev Games Unity Pleno',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Unity', 'C#', 'Unity3D', 'Asset'],
    headerInfo: 'Pleno (R$15,000)',
    url: 'https://programathor.com.br/jobs/29137-dev-games-unity-pleno-100-remoto',
  },
  {
    company: 'Impulso',
    title: 'Desenvolvedor Fullstack Pleno (Ruby on Rails)',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['RubyOnRails', 'Golang', 'JavaScript', 'Node.js', 'DevOps'],
    headerInfo: 'Pleno (R$12,000 até R$12,800)',
    url: 'https://impulso.team/en/profissionais/oportunidade/1915-pleno-fullstack-ruby-on-rails',
  },
  {
    company: 'Telavita',
    title: 'Desenvolvedor(a) Backend Pleno (Python)',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Python', 'Flask', 'FastAPI', 'MySQL', 'Postgres'],
    headerInfo: 'Pleno (até R$12,000)',
    url: 'https://programathor.com.br/jobs/29145-desenvolvedor-a-backend-python',
  },
  {
    company: 'Impulso',
    title: 'Desenvolvedor Fullstack Pleno (Typescript)',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Node.js', 'React', 'AWS', 'ReactNative', 'Typescript'],
    headerInfo: 'Pleno (R$11,200 até R$12,000)',
    url: 'https://impulso.team/en/profissionais/oportunidade/1916-pleno-senior-nodejs-react',
  },
  {
    company: 'I9 Atividades de Internet',
    title: 'Desenvolvedor(a) Sênior (Node.js)',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Node.js', 'MongoDB', 'Git'],
    headerInfo: 'Sênior (até R$12,000)',
    url: 'https://programathor.com.br/jobs/28485-desenvolvedor-a-node-js-senior',
  },
  {
    company: 'Agência B-Young',
    title: 'Social Media Manager',
    location: 'Brasil',
    language: 'Inglês',
    currency: 'U$',
    skills: ['RedesSociais', 'Conteúdo', 'Análise', 'Comunicação', 'Inglês'],
    headerInfo: 'Pleno (até R$5,000)',
    url: 'https://trampos.co/oportunidades/753337-social-media-manager',
  },
  {
    company: 'Ondaweb Raise Ltda',
    title: 'Desenvolvedor(a) Pleno (PHP)',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['PHP', 'Arquitetura', 'Otimização', 'Manipulação', 'Resolução'],
    headerInfo: 'Pleno (até R$3,000)',
    url: 'https://programathor.com.br/jobs/29126-desenvolvedor-a-php-pleno-com-experiencia-em-integracoes-via-api',
  },
  {
    company: 'OLX Brasil',
    title: 'Analista de Dados Pleno',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['SQL', 'Tableau', 'PowerBI', 'Excel', 'Comunicação'],
    headerInfo: 'Vaga afirmativa para Mulheres',
    url: 'https://jobs.smartrecruiters.com/OLXBrasil/743999911725293-analista-de-dados-pleno-vaga-afirmativa-para-mulheres',
  },
  {
    company: 'Neon',
    title: 'Senior Software Engineer (DevEx)',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Escalabilidade', 'Comunicação', 'Colaboração'],
    headerInfo: 'Afirmativa para Mulheres',
    url: 'https://jobs.lever.co/neon/50141241-0a84-4540-b4fd-38546fffe6c2',
  },
  {
    company: 'Ondaweb Raise Ltda',
    title: 'Desenvolvedor(a) Frontend Pleno (Wordpress)',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Frontend', 'Wordpress', 'Elemmentor', 'CSS', 'PHP'],
    headerInfo: 'Pleno (até R$4,000)',
    url: 'https://programathor.com.br/jobs/29153-desenvolvedor-a-front-end-pleno-wordpress-com-elemmentor',
  },
  {
    company: 'DBC Company',
    title: 'Desenvolvimento iOS Pleno',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Swift', 'ViewCode', 'Xcode', 'Testes', 'MVVM'],
    headerInfo: 'Pleno',
    url: 'https://vagas.dbccompany.com.br/vagas/301950',
  },
  {
    company: 'FullStack Labs',
    title: 'Desenvolvedor(a) Pleno (PHP e Vue.js/React.js)',
    location: 'Brasil',
    language: 'Inglês',
    currency: 'R$',
    skills: ['PHP', 'Laravel', 'Vue.js', 'React.js'],
    headerInfo: 'Mínimo de 3 anos de XP',
    url: 'https://jobs.lever.co/fullstacklabs/dd16443c-1ae5-47eb-bc0e-dc5ab3fb1e97',
  },
  {
    title: 'Pessoa Desenvolvedora Pleno (Kotlin)',
    company: 'DB1 Group',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Kotlin', 'Postgresql', 'SpringBoot', 'Hibernate', 'JUnit5'],
    headerInfo: 'Pleno',
    url: 'https://db1group.pinpointhq.com/pt-BR/postings/afd0319c-c437-4b54-aad7-1d5b58cbb16c',
  },
  {
    company: 'Taggie',
    title: 'Desenvolvedor(a) Pleno Fullstack (.NET)',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['.NET', 'Vue.js', 'AWS'],
    headerInfo: 'Pleno',
    url: 'https://programathor.com.br/jobs/29143-desenvolvedor-a-full-stack-net-pleno',
  },
  {
    company: 'OLX Brasil',
    title: 'Pessoa Desenvolvedora de Software Backend Pleno',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Python', 'Go', 'Testes', 'Testes', 'CI/CD'],
    headerInfo: 'Pleno',
    url: 'https://jobs.smartrecruiters.com/OLXBrasil/743999910857843-pessoa-desenvolvedora-de-software-backend-pleno',
  },
  {
    company: 'OLX Brasil',
    title: 'Pessoa Desenvolvedora Backend Pleno',
    location: 'Brasil',
    currency: 'R$',
    language: 'Português',
    skills: ['Go', 'Testes', 'Versionamento', 'Padronização', 'CI/CD'],
    headerInfo: 'Pleno',
    url: 'https://jobs.smartrecruiters.com/OLXBrasil/743999910857843-pessoa-desenvolvedora-de-software-backend-pleno',
  },
  {
    title: 'React Software Developer',
    location: 'Brasil',
    language: 'Inglês',
    skills: ['Javascript', 'React', 'Gatsby', 'Webpack'],
    headerInfo: 'Mínimo de 3 anos de XP',
    url: 'https://jobs.lever.co/oowlish/dc8dce8d-732f-4d80-a0a8-547681081aa1?source=6',
    company: 'Oowlish',
    currency: 'R$',
  },
  {
    company: 'OLX Brasil',
    title: 'Pessoa Desenvolvedora Backend (Python e Go)',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Python', 'Go', 'Testes', 'CI/CD', 'Containers'],
    headerInfo: 'Pleno',
    url: 'https://jobs.smartrecruiters.com/OLXBrasil/743999910857843-pessoa-desenvolvedora-de-software-backend-pleno',
  },
  {
    company: 'Impulso',
    title: 'Desenvolvedor Fullstack Sênior',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['C#', '.NetCore', 'Angular', 'Typescript', 'CI/CD'],
    headerInfo: 'Sênior (R$13,760 até R$14,400)',
    url: 'https://impulso.team/pt/profissionais/oportunidade/1918',
  },
  {
    company: 'Visie Padrões Web',
    title: 'Tech Lead (React)',
    location: 'Brasil',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Frontend', 'React', 'SCRUM', 'DevOps', 'Cloud'],
    headerInfo: 'Sênior',
    url: 'https://trampos.co/oportunidades/753762-tech-lead-react?locale=pt-BR',
  },
  {
    company: 'Thebridge',
    title: 'Desenvolvedor(a) Backend Sênior (Nodejs)',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['NodeJS', 'React', 'CasJS', 'AWS', 'Kubernetes'],
    headerInfo: 'Sênior',
    url: 'https://www.thebridge.social/job-detail?id=gupy-5148622',
  },
]

const globalOpenings: Opening[] = [
  {
    company: 'Meteor Software',
    title: 'DevOps Engineer',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: [
      'AWS',
      'Kubernetes',
      'Terraform',
      'Observability',
      'ShellScripting',
    ],
    headerInfo: 'Pleno (até $3,500)',
    url: 'https://public.app.shortcut.com/62/meteor-software/docs/33M0mvrlVcqjX85UO74Hdl/devops-engineer',
  },
  {
    company: 'Strider',
    title: 'Mid-level Full-Stack Engineer (Angular.js e Python)',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Angular.js', 'POO', 'TypeScript', 'JavaScript'],
    headerInfo: 'Mínimo de 3 anos de XP',
    url: 'https://app.onstrider.com/r/trampar_de_casa?job=bWlkLXNlbmlvci1mdWxsLXN0YWNrLWVuZ2luZWVyLWFuZ3VsYXItcHl0aG9uLTg3NjYzOWU0P3JlZmVycmFsPXRyYW1wYXJfZGVfY2FzYQ==',
  },
  {
    company: 'Strider',
    title: 'Database Administrator (MSSQL e Azure SQL)',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['ETL', 'Desenvolvimento', 'SQL', 'MSSQL', 'AzureSQL'],
    headerInfo: 'Mínimo de 4 anos de XP',
    url: 'app.onstrider.com/r/trampar_de_casa?job=c2VuaW9yLWRiYS1tc3NxbC04NjM3MThkMz9yZWZlcnJhbD10cmFtcGFyX2RlX2Nhc2E=',
  },
  {
    company: 'Strider',
    title: 'Senior Backend Engineer (Java e Spring)',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Java', 'Spring', 'Java', 'Spring', 'Comunicação'],
    headerInfo: 'Mínimo de 5 anos de XP',
    url: 'app.onstrider.com/r/trampar_de_casa?job=c2VuaW9yLWJhY2stZW5kLWVuZ2luZWVyLWphdmEtc3ByaW5nLWQxM2I0YzU1P3JlZmVycmFsPXRyYW1wYXJfZGVfY2FzYQ==',
  },
  {
    company: 'Strider',
    title: 'Lead Frontend Engineer (React.js)',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: [
      'React.js',
      'Desenvolvimento',
      'React.js',
      'Liderança',
      'Comunicação',
    ],
    headerInfo: 'Mínimo de 6 anos de XP',
    url: 'app.onstrider.com/r/trampar_de_casa?job=bGVhZC1mcm9udC1lbmQtZW5naW5lZXItcmVhY3QuanMtMjMzMDJlNGM/cmVmZXJyYWw9dHJhbXBhcl9kZV9jYXNh',
  },
  {
    company: 'Strider',
    title: 'Lead Backend Engineer (Nest.js e Python)',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Nest.js', 'Python', 'Liderança', 'Startup', 'Comunicação'],
    headerInfo: 'Mínimo de 6 anos de XP',
    url: 'app.onstrider.com/r/trampar_de_casa?job=bGVhZC1iYWNrLWVuZC1lbmdpbmVlci1uZXN0LmpzLXB5dGhvbi0wYmUwOThiOD9yZWZlcnJhbD10cmFtcGFyX2RlX2Nhc2E=',
  },
  {
    company: 'Generally Intelligent',
    title: 'Machine Learning Engineer',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['DeepLearning', 'MachineLearning', 'Python', 'PyTorch'],
    headerInfo: 'Pleno',
    url: 'https://dynamitejobs.com/company/generallyintelligent/remote-job/machine-learning-engineer-1',
  },
  {
    company: 'MailerLite',
    title: 'Site Reliability Engineer (Database)',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Ansible', 'GoLang', 'Kubernetes', 'MySQL', 'Postgres'],
    headerInfo: 'Pleno ($4,166 até $6,250)',
    url: 'https://www.mailerlite.com/jobs/site-reliability-engineer-database',
  },
  {
    company: 'Proxify',
    title: 'Senior Frontend Developer',
    location: 'Inglaterra',
    language: 'Inglês',
    currency: 'U$',
    skills: ['React.js', 'Angular.js', 'CI/CD', 'Inglês', 'Comunicação'],
    headerInfo: 'Mínimo de 5 anos de XP ($4,166 até $5,833)',
    url: 'https://remotive.com/remote-jobs/software-dev/senior-frontend-developer-1383531',
  },
  {
    company: 'Proxify',
    title: 'Senior Laravel Developer',
    location: 'Inglaterra',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Laravel', 'Comunicação', 'Cooperação', 'Backend'],
    headerInfo: 'Mínimo de 5 anos de XP ($3,333 até $6,250)',
    url: 'https://remotive.com/remote-jobs/software-dev/senior-laravel-developer-1422554',
  },
  {
    company: 'WorkOS',
    title: 'Software Engineer',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Debugging', 'Empathy', 'TypeScript', 'React', 'Postgres'],
    headerInfo: 'Mínimo de 3 anos de XP',
    url: 'https://jobs.lever.co/workos/2333cdf9-5c71-4232-9dc8-4f18f6a1b719',
  },
  {
    company: 'Awesome Motive',
    title: 'WordPress Developer',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['JavaScript', 'MySQL', 'Webpack', 'WordPress', 'PHP'],
    headerInfo: 'Pleno',
    url: 'https://apply.workable.com/awesomemotive/j/198E2696EB/?utm_source=dynamitejobs',
  },
  {
    company: 'LetHub',
    title: 'Fullstack Software Developer',
    location: 'Canada',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Angular', 'NodeJs', 'Express', 'MySQL', 'Postgres'],
    headerInfo: 'Mínimo de 3 anos de XP',
    url: 'https://lethub.breezy.hr/p/5cdddc464f42-intermediate-full-stack-software-developer',
  },
  {
    company: 'Recruitment LatAm',
    title: 'Frontend Developer',
    location: 'LATAM',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Frontend', 'UX/UI', 'APIs', 'JavaScript', 'JQuery'],
    headerInfo: 'Mínimo de 4 anos de XP',
    url: 'https://remotive.com/remote-jobs/software-dev/frontend-developer-1749489',
  },
  {
    company: 'Stealth',
    title: 'Full Stack Developer (Javascript)',
    location: 'Ireland',
    language: 'Inglês',
    currency: 'U$',
    skills: [
      'ApolloGraphQL',
      'JavaScript',
      'Microservices',
      'Nest.js',
      'PostgreSQL',
    ],
    headerInfo: 'Mínimo de 5 anos de XP',
    url: 'https://dynamitejobs.com/company/stealth/remote-job/full-stack-developer-cyber-security-startup-ireland',
  },
]

export const openings20230809: Openings = {
  localOpenings,
  globalOpenings,
}
