import { Opening } from 'shared/src/email/openings-email/Opening'
import { Openings } from '../Openings'

const localOpenings: Opening[] = [
  {
    title: 'Pessoa Desenvolvedora Júnior (Kotlin)',
    company: 'DB1 Group',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Kotlin', 'SpringBoot', 'Postgresql', 'JUnit5', 'ReactJS'],
    headerInfo: 'Júnior',
    url: 'https://db1group.pinpointhq.com/pt-BR/postings/3bfac84e-f557-4a4b-b5fb-f70d4ae9d4c2',
  },
  {
    company: 'OLX Brasil',
    title: 'Pessoa Desenvolvedora Frontend Júnior',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Javascript', 'Typescript', 'React', 'Git'],
    headerInfo: 'Vaga Afirmativa para Mulheres',
    url: 'https://jobs.lever.co/neon/50141241-0a84-4540-b4fd-38546fffe6c2',
  },
  {
    company: 'THE CODE',
    title: 'Dev Games Unity Pleno',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Unity', 'C#', 'Unity3D', 'Asset'],
    headerInfo: 'Pleno (R$15,000)',
    url: 'https://programathor.com.br/jobs/29137-dev-games-unity-pleno-100-remoto',
  },
  {
    company: 'Telavita',
    title: 'Desenvolvedor(a) Backend Pleno (Python)',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Python', 'Flask', 'FastAPI', 'MySQL', 'Postgres'],
    headerInfo: 'Pleno (até R$12,000)',
    url: 'https://programathor.com.br/jobs/29145-desenvolvedor-a-backend-python',
  },
  {
    company: 'I9 Atividades de Internet',
    title: 'Desenvolvedor(a) Sênior (Node.js)',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Node.js', 'MongoDB', 'Git'],
    headerInfo: 'Sênior (até R$12,000)',
    url: 'https://programathor.com.br/jobs/28485-desenvolvedor-a-node-js-senior',
  },
  {
    company: 'Agência B-Young',
    title: 'Social Media Manager',
    location: 'Brasil',
    language: 'Inglês',
    currency: 'U$',
    skills: ['RedesSociais', 'Conteúdo', 'Análise', 'Comunicação', 'Inglês'],
    headerInfo: 'Pleno (até R$5,000)',
    url: 'https://trampos.co/oportunidades/753337-social-media-manager',
  },
  {
    company: 'Ondaweb Raise Ltda',
    title: 'Desenvolvedor(a) Pleno (PHP)',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['PHP', 'Arquitetura', 'Otimização', 'Manipulação', 'Resolução'],
    headerInfo: 'Pleno (até R$3,000)',
    url: 'https://programathor.com.br/jobs/29126-desenvolvedor-a-php-pleno-com-experiencia-em-integracoes-via-api',
  },
  {
    company: 'OLX Brasil',
    title: 'Analista de Dados Pleno',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['SQL', 'Tableau', 'PowerBI', 'Excel', 'Comunicação'],
    headerInfo: 'Vaga afirmativa para Mulheres',
    url: 'https://jobs.smartrecruiters.com/OLXBrasil/743999911725293-analista-de-dados-pleno-vaga-afirmativa-para-mulheres',
  },
  {
    company: 'Neon',
    title: 'Senior Software Engineer (DevEx)',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Escalabilidade', 'Comunicação', 'Colaboração'],
    headerInfo: 'Afirmativa para Mulheres',
    url: 'https://jobs.lever.co/neon/50141241-0a84-4540-b4fd-38546fffe6c2',
  },
  {
    company: 'Ondaweb Raise Ltda',
    title: 'Desenvolvedor(a) Frontend Pleno (Wordpress)',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Front-end', 'Wordpress', 'Elemmentor', 'CSS', 'PHP'],
    headerInfo: 'Pleno (até R$4,000)',
    url: 'https://programathor.com.br/jobs/29153-desenvolvedor-a-front-end-pleno-wordpress-com-elemmentor',
  },
  {
    company: 'DBC Company',
    title: 'Desenvolvimento iOS Pleno',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Swift', 'ViewCode', 'Xcode', 'Testes', 'MVVM'],
    headerInfo: 'Pleno',
    url: 'https://vagas.dbccompany.com.br/vagas/301950',
  },
  {
    company: 'FullStack Labs',
    title: 'Desenvolvedor(a) Pleno (PHP e Vue.js/React.js)',
    location: 'Brasil',
    language: 'Inglês',
    currency: 'R$',
    skills: ['PHP', 'Laravel', 'Vue.js', 'React.js'],
    headerInfo: 'Pleno',
    url: 'https://jobs.lever.co/fullstacklabs/dd16443c-1ae5-47eb-bc0e-dc5ab3fb1e97',
  },
  {
    title: 'Pessoa Desenvolvedora Pleno (Kotlin)',
    company: 'DB1 Group',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Kotlin', 'Postgresql', 'SpringBoot', 'Hibernate', 'JUnit5'],
    headerInfo: 'Pleno',
    url: 'https://db1group.pinpointhq.com/pt-BR/postings/afd0319c-c437-4b54-aad7-1d5b58cbb16c',
  },
  {
    company: 'Taggie',
    title: 'Desenvolvedor(a) Pleno Fullstack (.NET)',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['.NET', 'Vue.js', 'AWS'],
    headerInfo: 'Pleno',
    url: 'https://programathor.com.br/jobs/29143-desenvolvedor-a-full-stack-net-pleno',
  },
  {
    company: 'OLX Brasil',
    title: 'Pessoa Desenvolvedora de Software Backend Pleno',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Python', 'Go', 'Testes', 'Testes', 'CI/CD'],
    headerInfo: 'Pleno',
    url: 'https://jobs.smartrecruiters.com/OLXBrasil/743999910857843-pessoa-desenvolvedora-de-software-backend-pleno',
  },
  {
    company: 'OLX Brasil',
    title: 'Pessoa Desenvolvedora Backend Pleno',
    location: 'Brasil',
    currency: 'R$',
    language: 'Português',
    skills: ['Go', 'Testes', 'Versionamento', 'Padronização', 'CI/CD'],
    headerInfo: 'Pleno',
    url: 'https://jobs.smartrecruiters.com/OLXBrasil/743999910857843-pessoa-desenvolvedora-de-software-backend-pleno',
  },
  {
    title: 'React Software Developer',
    location: 'Brasil',
    language: 'Inglês',
    skills: ['Javascript', 'React', 'Gatsby', 'Webpack'],
    headerInfo: 'Pleno',
    url: 'https://jobs.lever.co/oowlish/dc8dce8d-732f-4d80-a0a8-547681081aa1?source=6',
    company: 'Oowlish',
    currency: 'R$',
  },
  {
    company: 'OLX Brasil',
    title: 'Pessoa Desenvolvedora Backend (Python e Go)',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Python', 'Go', 'Testes', 'CI/CD', 'Containers'],
    headerInfo: 'Pleno',
    url: 'https://jobs.smartrecruiters.com/OLXBrasil/743999910857843-pessoa-desenvolvedora-de-software-backend-pleno',
  },
  {
    company: 'Visie Padrões Web',
    title: 'Tech Lead (React)',
    location: 'Brasil',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Frontend', 'React', 'SCRUM', 'DevOps', 'Cloud'],
    headerInfo: 'Sênior',
    url: 'https://trampos.co/oportunidades/753762-tech-lead-react?locale=pt-BR',
  },
  {
    company: 'Thebridge',
    title: 'Desenvolvedor(a) Backend Sênior (Nodejs)',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['NodeJS', 'React', 'CasJS', 'AWS', 'Kubernetes'],
    headerInfo: 'Sênior',
    url: 'https://www.thebridge.social/job-detail?id=gupy-5148622',
  },
]

const globalOpenings: Opening[] = [
  {
    company: 'Meteor Software',
    title: 'DevOps Engineer',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: [
      'AWS',
      'Kubernetes',
      'Terraform',
      'Observability',
      'ShellScripting',
    ],
    headerInfo: 'Pleno (até $3,500)',
    url: 'https://public.app.shortcut.com/62/meteor-software/docs/33M0mvrlVcqjX85UO74Hdl/devops-engineer',
  },
  {
    company: 'Strider',
    title: 'Mid-level Full-Stack Engineer (Angular.js e Python)',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Angular.js', 'POO', 'TypeScript', 'JavaScript'],
    headerInfo: 'Mínimo de 3 anos de XP',
    url: 'https://app.onstrider.com/r/trampar_de_casa?job=bWlkLXNlbmlvci1mdWxsLXN0YWNrLWVuZ2luZWVyLWFuZ3VsYXItcHl0aG9uLTg3NjYzOWU0P3JlZmVycmFsPXRyYW1wYXJfZGVfY2FzYQ==',
  },
  {
    company: 'Strider',
    title: 'Database Administrator (MSSQL e Azure SQL)',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['ETL', 'Desenvolvimento', 'SQL', 'ConsultasSQL', 'Comunicação'],
    headerInfo: 'Mínimo de 4 anos de XP',
    url: 'app.onstrider.com/r/trampar_de_casa?job=c2VuaW9yLWRiYS1tc3NxbC04NjM3MThkMz9yZWZlcnJhbD10cmFtcGFyX2RlX2Nhc2E=',
  },
  {
    company: 'Strider',
    title: 'Senior Back-end Engineer (Java e Spring)',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Java', 'Spring', 'Java/Spring', 'Startup', 'Comunicação'],
    headerInfo: 'Mínimo de 5 anos de XP',
    url: 'app.onstrider.com/r/trampar_de_casa?job=c2VuaW9yLWJhY2stZW5kLWVuZ2luZWVyLWphdmEtc3ByaW5nLWQxM2I0YzU1P3JlZmVycmFsPXRyYW1wYXJfZGVfY2FzYQ==',
  },
  {
    company: 'Strider',
    title: 'Lead Front-end Engineer (React.js)',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: [
      'React.js',
      'Desenvolvimento',
      'React.js',
      'Liderança',
      'Comunicação',
    ],
    headerInfo: 'Mínimo de 6 anos de XP',
    url: 'app.onstrider.com/r/trampar_de_casa?job=bGVhZC1mcm9udC1lbmQtZW5naW5lZXItcmVhY3QuanMtMjMzMDJlNGM/cmVmZXJyYWw9dHJhbXBhcl9kZV9jYXNh',
  },
  {
    company: 'Strider',
    title: 'Lead Back-end Engineer (Nest.js e Python)',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Nest.js', 'Python', 'Liderança', 'Startup', 'Comunicação'],
    headerInfo: 'Mínimo de 6 anos de XP',
    url: 'app.onstrider.com/r/trampar_de_casa?job=bGVhZC1iYWNrLWVuZC1lbmdpbmVlci1uZXN0LmpzLXB5dGhvbi0wYmUwOThiOD9yZWZlcnJhbD10cmFtcGFyX2RlX2Nhc2E=',
  },
  {
    company: 'Tembo',
    title: 'Senior Postgres DBA',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: [
      'Automation',
      'DataEngineering',
      'DatabaseAdministration',
      'Postgres',
    ],
    headerInfo: 'Sênior (até $14,583)',
    url: 'https://dynamitejobs.com/company/tembo/remote-job/senior-postgres-dba',
  },
  {
    company: 'StackCommerce',
    title: 'Senior Full Stack Engineer (Search and Performance Focus)',
    location: 'United States',
    language: 'Inglês',
    currency: 'U$',
    skills: ['ElasticSearch', 'Fullstack', 'RubyOnRails', 'React.js'],
    headerInfo: 'Sênior (até $14,491)',
    url: 'https://dynamitejobs.com/company/stackcommerce/remote-job/senior-full-stack-engineer-search-and-performance-focus',
  },
  {
    company: 'Vital',
    title: 'Frontend Engineer',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['CSS', 'Design', 'ReactNative', 'React.js', 'TypeScript'],
    headerInfo: 'Pleno (até $10,000)',
    url: 'https://dynamitejobs.com/company/vital/remote-job/frontend-engineer',
  },
  {
    company: 'Generally Intelligent',
    title: 'Machine Learning Engineer',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['DeepLearning', 'MachineLearning', 'Python', 'PyTorch'],
    headerInfo: 'Pleno',
    url: 'https://dynamitejobs.com/company/generallyintelligent/remote-job/machine-learning-engineer-1',
  },
  {
    company: 'Octopus Deploy',
    title: 'Web Developer',
    location: 'Europa',
    language: 'Inglês',
    currency: 'EUR',
    skills: ['CSS', 'HTML', 'JavaScript', 'SEO', 'WebDesign'],
    headerInfo: 'Pleno',
    url: 'https://dynamitejobs.com/company/octopusdeploy/remote-job/web-developer',
  },
  {
    company: 'Localcoin',
    title: 'Java Backend Developer',
    location: 'Canada',
    language: 'Inglês',
    currency: 'U$',
    skills: ['BackendDevelopment', 'Java', 'Maven', 'RestfulAPI', 'SQL'],
    headerInfo: 'Pleno',
    url: 'https://dynamitejobs.com/company/localcoin/remote-job/java-backend-developer',
  },
  {
    company: 'Stealth',
    title: 'Full Stack Developer (Javascript)',
    location: 'Ireland',
    language: 'Inglês',
    currency: 'U$',
    skills: [
      'ApolloGraphQL',
      'JavaScript',
      'Microservices',
      'Nest.js',
      'PostgreSQL',
    ],
    headerInfo: 'Pleno',
    url: 'https://dynamitejobs.com/company/stealth/remote-job/full-stack-developer-cyber-security-startup-ireland',
  },
  {
    company: 'Uplift',
    title: 'Senior DevOps Engineer',
    location: 'Canada',
    language: 'Inglês',
    currency: 'U$',
    skills: ['DevOps', 'GitHub', 'Java', 'Node.JS', 'Python'],
    headerInfo: 'Sênior',
    url: 'https://dynamitejobs.com/company/uplift/remote-job/senior-devops-engineer',
  },
  {
    company: 'VRChat',
    title: 'DevOps Engineer',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['DevOps', 'GoogleCloud', 'Kubernetes', 'Node.JS', 'Terraform'],
    headerInfo: 'Pleno',
    url: 'https://dynamitejobs.com/company/vrchat/remote-job/devops-engineer-1',
  },
]

export const openings20230809: Openings = {
  localOpenings,
  globalOpenings,
}
