services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${TO_POSTGRES_URL}"]
      interval: 5s
      timeout: 5s
      retries: 5
      # volumes:
      #   - postgres-data:/var/lib/postgresql/data
      #   - ./backups:/backups
    networks:
      - postgres-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

networks:
  postgres-network:
    driver: bridge

    #   volumes:
    #     postgres-data:
    #       driver: local 
