services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${TO_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TO_POSTGRES_PASSWORD}
      POSTGRES_DB: ${TO_POSTGRES_DB}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TO_POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: 