name: auto email sender 

on:
  push:
    paths: 
      - apps/auto-email-sender/**
      - packages/**

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20.5.1

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: |
          node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      run: yarn install

    - name: Build
      run: yarn build:auto-email-sender

    - name: Run tests
      run: yarn test:silent
