name: Build and push router app 

on:
  push:
    branches:
      - 'main'
    paths:
      - 'apps/router/**/*'
      - 'apps/router/*'
  workflow_dispatch:
    inputs:
      use_custom_registry:
        description: 'Use custom registry instead of Oracle Cloud'
        required: false
        default: true
        type: boolean

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ inputs.use_custom_registry == 'true' && 'amd64' || 'arm64,arm,amd64' }}

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.use_custom_registry == 'true' && secrets.DOCKER_REGISTRY_HOST || 'gru.ocir.io' }}
          username: ${{ inputs.use_custom_registry == 'true' && secrets.DOCKER_REGISTRY_USER || secrets.OCI_REPOSITORY_USER }}
          password: ${{ inputs.use_custom_registry == 'true' && secrets.DOCKER_REGISTRY_PASS || secrets.OCI_REPOSITORY_PASS }}

      - name: Build Docker image
        run: |
          REGISTRY=${{ inputs.use_custom_registry == 'true' && secrets.DOCKER_REGISTRY_HOST || 'gru.ocir.io' }}
          REPO=${{ inputs.use_custom_registry == 'true' && 'router-app' || 'gricbxnlp2kb/router-app' }}
          PLATFORMS=${{ inputs.use_custom_registry == 'true' && 'linux/amd64' || 'linux/arm64,linux/amd64' }}
          
          cd apps/router
          docker buildx build . --platform $PLATFORMS -t "$REGISTRY/$REPO:latest" --push
