name: Build and push auto email sender 

on:
  push:
    branches:
      - main
    paths:
      - 'apps/auto-email-sender/**/*'
      - 'packages/**/*'
      - 'Dockerfile.auto'
  workflow_dispatch:
    inputs:
      platform:
        description: 'Build platform (amd64 or arm64)'
        required: false
        default: 'amd64'
        type: string

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.5.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ inputs.platform || 'amd64' }}

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_HOST }}
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASS }}

      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install

      - name: Build Docker image
        run: |
          REGISTRY=${{ secrets.DOCKER_REGISTRY_HOST }}
          REPO='auto-email-sender'
          PLATFORM='linux/${{ inputs.platform || 'amd64' }}'
          
          docker buildx build . --platform $PLATFORM --file ./Dockerfile.auto -t "$REGISTRY/$REPO:latest" \
          --push \
          --build-arg SECRET_KEY="${{ secrets.SECRET_KEY }}" \
          --build-arg RESEND_KEY="${{ secrets.RESEND_KEY }}" \
          --build-arg POSTGRES_URL="${{ secrets.POSTGRES_URL }}" \
          --build-arg MONGO_ADDRESS="${{ secrets.MONGO_ADDRESS }}" \
          --build-arg MONGO_PASSWORD="${{ secrets.MONGO_PASSWORD }}" \
          --build-arg MONGO_USERNAME="${{ secrets.MONGO_USERNAME }}" \
          --build-arg RABBITMQ_ADDRESS="${{ secrets.RABBITMQ_ADDRESS }}"

