name: Build and push bluesky-job-poster

on:
  push:
    branches:
      - main
    paths:
      - 'apps/bluesky-job-poster/**/*'
      - 'packages/**/*'

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.5.1

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Login to OCIR
        uses: docker/login-action@v2
        with:
          registry: gru.ocir.io
          username: ${{ secrets.OCI_REPOSITORY_USER }}
          password: ${{ secrets.OCI_REPOSITORY_PASS }}

      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install

      - name: Build Bluesky Docker image
        run: |
          docker buildx build . --platform linux/arm64 --file ./apps/bluesky-job-poster/Dockerfile -t "gru.ocir.io/gricbxnlp2kb/bluesky-job-poster:latest" \
          --push \
          --build-arg BSKY_EMAIL="${{ secrets.BSKY_EMAIL }}" \
          --build-arg BSKY_PASSWORD="${{ secrets.BSKY_PASSWORD }}" \
          --build-arg SUPABASE_URL="${{ secrets.SUPABASE_URL }}" \
          --build-arg SUPABASE_SERVICE_ROLE="${{ secrets.SUPABASE_SERVICE_ROLE }}"