name: Build and push bluesky-job-poster

on:
  push:
    branches:
      - main
    paths:
      - 'apps/bluesky-job-poster/**/*'
      - 'packages/**/*'
  workflow_dispatch:
    inputs:
      use_custom_registry:
        description: 'Use custom registry instead of Oracle Cloud'
        required: false
        default: true 
        type: boolean

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.5.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ inputs.use_custom_registry == 'true' && 'amd64' || 'arm64,arm,amd64' }}

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.use_custom_registry == 'true' && secrets.DOCKER_REGISTRY_HOST || 'gru.ocir.io' }}
          username: ${{ inputs.use_custom_registry == 'true' && secrets.DOCKER_REGISTRY_USER || secrets.OCI_REPOSITORY_USER }}
          password: ${{ inputs.use_custom_registry == 'true' && secrets.DOCKER_REGISTRY_PASS || secrets.OCI_REPOSITORY_PASS }}

      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install

      - name: Build Bluesky Docker image
        run: |
          REGISTRY=${{ inputs.use_custom_registry == 'true' && secrets.DOCKER_REGISTRY_HOST || 'gru.ocir.io' }}
          REPO=${{ inputs.use_custom_registry == 'true' && 'bluesky-job-poster' || 'gricbxnlp2kb/bluesky-job-poster' }}
          PLATFORMS=${{ inputs.use_custom_registry == 'true' && 'linux/amd64' || 'linux/arm64,linux/amd64' }}
          
          docker buildx build . --platform $PLATFORMS --file ./apps/bluesky-job-poster/Dockerfile -t "$REGISTRY/$REPO:latest" \
          --push \
          --build-arg BSKY_EMAIL="${{ secrets.BSKY_EMAIL }}" \
          --build-arg BSKY_PASSWORD="${{ secrets.BSKY_PASSWORD }}" \
          --build-arg SUPABASE_URL="${{ secrets.SUPABASE_URL }}" \
          --build-arg SUPABASE_SERVICE_ROLE="${{ secrets.SUPABASE_SERVICE_ROLE }}"