name: Build and push router app 

on:
  push:
    branches:
      - 'main'
    paths:
      - 'apps/router/**/*'
      - 'apps/router/*'
  workflow_dispatch:  # Allows manual triggering

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64,arm'

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Login to OCIR
        uses: docker/login-action@v2
        with:
          registry: gru.ocir.io
          username: ${{ secrets.OCI_REPOSITORY_USER }}
          password: ${{ secrets.OCI_REPOSITORY_PASS }}

      - name: Build Docker image
        run: |
          cd apps/router
          docker buildx build . --platform linux/arm64 -t "gru.ocir.io/gricbxnlp2kb/router-app:latest" --push
