name: Build web app

on:
  push:
    branches:
      - '**'
      - '!main'
    paths:
      - 'apps/web/**/*'
      - 'packages/**/*'
      - 'Dockerfile'
  workflow_dispatch:
    inputs:
      platform:
        description: 'Build platform (amd64 or arm64)'
        required: false
        default: 'amd64'
        type: string

jobs:
  Build:
    runs-on: ubuntu-latest
    environment: 
      name: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
            
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Ping homelab
        run: apt update && apt install -y iputils-ping && ping -c 4 compose

      - name: Build Docker image
        run: |
          docker buildx build --platform linux/${{ inputs.platform || 'amd64' }} --load -t local-image:local . \
          --build-arg POSTGRES_URL="${{ secrets.POSTGRES_URL }}" \
          --build-arg REDIS_URL="${{ secrets.REDIS_URL }}" \
          --build-arg EMAIL_KEY="${{ secrets.EMAIL_KEY }}" \
          --build-arg EMAIL_PASS="${{ secrets.EMAIL_PASS }}" \
          --build-arg CRYPT_SECRET="${{ secrets.CRYPT_SECRET }}" \
          --build-arg RESEND_KEY="${{ secrets.RESEND_KEY }}" \
          --build-arg RESEND_WEBHOOK_SECRET="${{ secrets.RESEND_WEBHOOK_SECRET }}" \
          --build-arg OWNER_EMAIL="${{ secrets.OWNER_EMAIL }}" \
          --build-arg NEXT_PUBLIC_MIXPANEL_KEY="${{ secrets.NEXT_PUBLIC_MIXPANEL_KEY }}" \
          --build-arg CRON_SECRET="${{ secrets.CRON_SECRET }}" \
          --network host
