name: Build bluesky job poster

on:
  push:
    paths:
      - apps/bluesky-job-poster/**
      - packages/**

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.5.1

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install

      - name: Build Docker Image
        run: |
          docker buildx build . --platform linux/arm64 --file ./apps/bluesky-job-poster/Dockerfile \
          --build-arg BSKY_EMAIL="${{ secrets.BSKY_EMAIL }}" \
          --build-arg BSKY_PASSWORD="${{ secrets.BSKY_PASSWORD }}" \
          --build-arg SUPABASE_URL="${{ secrets.SUPABASE_URL }}" \
          --build-arg SUPABASE_SERVICE_ROLE="${{ secrets.SUPABASE_SERVICE_ROLE }}"