name: Verify build auto email sender new

on:
  push:
    paths:
      - apps/auto-email-sender-new/**
      - packages/**

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.5.1

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install

      - name: Build Docker Image
        run: |
          docker buildx build . --platform linux/arm64 --file ./Dockerfile.auto \
          --build-arg SECRET_KEY="${{ secrets.SECRET_KEY }}" \
          --build-arg RESEND_KEY="${{ secrets.RESEND_KEY }}" \
          --build-arg SUPABASE_URL="${{ secrets.SUPABASE_URL }}" \
          --build-arg SUPABASE_SERVICE_ROLE="${{ secrets.SUPABASE_SERVICE_ROLE }}" \
          --build-arg MONGO_ADDRESS="${{ secrets.MONGO_ADDRESS }}" \
          --build-arg MONGO_PASSWORD="${{ secrets.MONGO_PASSWORD }}" \
          --build-arg MONGO_USERNAME="${{ secrets.MONGO_USERNAME }}" \
          --build-arg RABBITMQ_ADDRESS="${{ secrets.RABBITMQ_ADDRESS }}"