import { Opening } from 'shared/src/email/openings-email/Opening'
import { Openings } from '../Openings'

const localOpenings: Opening[] = [
  {
    company: 'Impulso',
    title: 'Engenheiro de Software Pleno (Java | Kotlin)',
    location: 'Localização da Empresa',
    language: 'Português',
    currency: 'R$',
    skills: ['Java', 'AWS', 'Kotlin', 'Microsserviços', 'CI/CD'],
    headerInfo: 'Pleno (R$12,000 até R$12,800)',
    url: 'https://impulso.team/pt/profissionais/oportunidade/1938',
  },
  {
    company: 'Impulso',
    title: 'Desenvolvedor(a) Mobile Pleno React Native',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['React Native', 'Android', 'iOS', 'JavaScript'],
    headerInfo: 'Pleno (R$12,000 até R$12,800)',
    url: 'https://impulso.team/pt/profissionais/oportunidade/1939',
  },
  {
    company: 'Mindbe',
    title: 'Desenvolvedor(a) Front-end + Javascript',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: [
      'Vue.js',
      'JavaScript',
      'TypeScript',
      'Nuxt',
      'Testes Automatizados',
    ],
    headerInfo: 'Pleno (até R$8,000)',
    url: 'https://programathor.com.br/jobs/29386-desenvolvedor-a-front-end-javascript',
  },
  {
    company: 'Xgrow',
    title: 'Desenvolvedor(a) Full Stack - Pleno',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['CSS', 'Vue.js', 'HTML', 'JavaScript', 'PHP'],
    headerInfo: 'Pleno (até R$8,000)',
    url: 'https://programathor.com.br/jobs/29271-desenvolvedor-a-full-stack-pleno',
  },
  {
    company: 'Jaya Tech',
    title: 'Pessoa Desenvolvedora Java Pleno',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Google Cloud', 'Java', 'Spring Boot'],
    headerInfo: 'Pleno (até R$7,000)',
    url: 'https://programathor.com.br/jobs/29219-pessoa-desenvolvedora-java-pleno',
  },
  {
    company: 'Gesuas',
    title: 'Desenvolvedor(a) Front-end Pleno',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['CSS', 'Docker', 'HTML', 'JavaScript', 'Vue.js'],
    headerInfo: 'Pleno (até R$5,000)',
    url: 'https://programathor.com.br/jobs/29263-desenvolvedor-a-front-end-pleno',
  },
  {
    company: 'PicPay',
    title: 'Desenvolvedor Java Especialista',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['OOP', 'Java', 'SpringBoot', 'Testes'],
    headerInfo: 'Pleno',
    url: 'https://picpay.com/oportunidades-de-emprego-e-carreiras/central-de-vagas/4286393005',
  },
  {
    company: 'Going2',
    title: 'Dev. Back-end Pleno (WEB)',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Express', 'NestJS', 'TypeORM', 'MySQL', 'Testes'],
    headerInfo: 'Pleno',
    url: 'https://going2.vagas.solides.com.br/vaga/297065',
  },
  {
    company: 'Panda Video',
    title: 'Desenvolvedor(a) Full-Stack Pleno',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Git', 'JavaScript', 'Node.js', 'Vue.js'],
    headerInfo: 'Pleno',
    url: 'https://programathor.com.br/jobs/29373-desenvolvedor-a-full-stack-pleno-para-plataforma-de-streaming-de-video',
  },
  {
    company: 'Going2',
    title: 'Desenvolvedor Front-end Pleno (WEB)',
    location: 'Brasil',
    language: 'Português',
    currency: 'U$',
    skills: ['Bugs', 'Javascript', 'NextJS', 'API', 'CI/CD'],
    headerInfo: 'Pleno',
    url: 'https://going2.vagas.solides.com.br/vaga/297951',
  },
  {
    company: 'Impulso',
    title: 'Sênior Java Kotlin',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Java', 'Kotlin', 'Python', 'RabbitMQ', 'Spring'],
    headerInfo: 'Sênior (R$13,600 até R$15,200)',
    url: 'https://impulso.team/pt/profissionais/oportunidade/1943-senior-java-kotlin',
  },
  {
    company: 'Boavista Tecnologia',
    title: 'Pessoa Desenvolvedora Java Sênior - Tech Lead',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['Java', 'JavaScript', 'Linux', 'POO', 'PostgreSQL'],
    headerInfo: 'Sênior (até R$15,000)',
    url: 'https://programathor.com.br/jobs/29294-pessoa-desenvolvedora-java-senior-tech-lead',
  },
  {
    company: 'Bukly',
    title: 'Desenvolvedor(a) PHP Sênior',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['CakePHP', 'Git', 'MySQL', 'Laravel'],
    headerInfo: 'Sênior (até R$15,000)',
    url: 'https://programathor.com.br/jobs/29265-desenvolvedor-a-php-senior-remoto',
  },
  {
    company: 'Clickbus',
    title: 'Pessoa Desenvolvedora Back-end Sênior',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: [
      'Estruturas de cache de dados',
      'Banco de dados',
      'JVM',
      'Java',
      'Kotlin',
    ],
    headerInfo: 'Sênior',
    url: 'https://clickbus.inhire.app/vagas/359d0e9a-e786-4b68-bde9-553d372c8f65/pessoa-desenvolvedora-back-end-senior',
  },
  {
    company: 'PicPay',
    title: 'Analista Segurança da Informação Sênior',
    location: 'Brasil',
    language: 'Português',
    currency: 'R$',
    skills: ['API', 'Cloud', 'AWS', 'Azure', 'Pentest'],
    headerInfo: 'Sênior',
    url: 'https://picpay.com/oportunidades-de-emprego-e-carreiras/central-de-vagas/4294122005',
  },
]

const globalOpenings: Opening[] = [
  {
    company: 'Big Time Studios',
    title: 'DevOps Engineer',
    location: 'Global',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Docker', 'AWS', 'Azure', 'Redis', 'DevOps'],
    headerInfo: 'Pleno',
    url: 'https://jobs.lever.co/bigtime/e7e281bc-d23b-4658-91c9-f12a28fafe06',
  },
  {
    company: 'Cultured Code',
    title: 'Cloud Platform Engineer',
    location: 'Global',
    language: 'Inglês',
    currency: 'U$',
    skills: ['AWS', 'Terraform', 'Kubernetes', 'Databases', 'Security'],
    headerInfo: 'Pleno',
    url: 'https://cultured-code.breezy.hr/p/8fad23a257eb01-cloud-platform-engineer',
  },
  {
    company: 'Strider',
    title: 'Mid-level Back-end Engineer - Node.js',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Node.js', 'JavaScript', 'PostgreSQL', 'Heroku', 'TypeScript'],
    headerInfo: 'Mínimo de 2 anos de XP($10,000 até $15,000)',
    url: 'app.onstrider.com/r/trampar_de_casa?job=bWlkLWxldmVsLWJhY2stZW5kLWVuZ2luZWVyLW5vZGUuanMtc3RyaWRlci04NzY5ODAyOD9yZWZlcnJhbD10cmFtcGFyX2RlX2Nhc2E=',
  },
  {
    company: 'FullStack Labs',
    title: 'AI Machine Learning Engineer',
    location: 'Costa Rica',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Python', 'R', 'Java', 'TensorFlow', 'PyTorch'],
    headerInfo: 'Mínimo de 3 anos de XP',
    url: 'https://jobs.lever.co/fullstacklabs/7c7999e2-3125-4292-ad34-360f66b23b8c',
  },
  {
    company: 'PopSQL',
    title: 'Developer Relations',
    location: 'Global',
    language: 'Inglês',
    currency: 'U$',
    skills: [
      'SQL',
      'Data Ecosystem',
      'Content Creation',
      'Technical Presentations',
    ],
    headerInfo: 'Mínimo de 3 anos de XP($10,000 até $15,000)',
    url: 'https://jobs.ashbyhq.com/popsql/e3d66b05-866a-4a34-83e2-7b0e937d963c',
  },
  {
    company: 'Just Appraised',
    title: 'Backend Developer',
    location: 'Brasil',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Java', 'AWS', 'Postgres', 'SQL', 'Git'],
    headerInfo: 'Mínimo de 5 anos de XP',
    url: 'https://ats.rippling.com/just-appraised-jobs/jobs/13e2fed4-6e7c-4ec5-912e-3b990ac5b17c',
  },
  {
    company: 'PopSQL',
    title: 'Senior Software Engineer',
    location: 'Global',
    language: 'Inglês',
    currency: 'U$',
    skills: ['JavaScript', 'React', 'Ruby', 'Rails', 'Fullstack'],
    headerInfo: 'Sênior ($10,833 até $16,666)',
    url: 'https://jobs.ashbyhq.com/popsql/9b30c9ba-183d-462d-aab5-e2fbe26764b4',
  },
  {
    company: 'SecurityScorecard',
    title: 'Senior Full Stack Software Engineer',
    location: 'Global',
    language: 'Inglês',
    currency: 'U$',
    skills: ['NodeJS', 'Typescript', 'React', 'Docker', 'Jenkins'],
    headerInfo: 'Mínimo de 5 anos de XP',
    url: 'https://securityscorecard.com/company/careers-list/?gh_jid=5354640',
  },
  {
    company: 'Strider',
    title: 'Senior Embedded Engineer',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['IoT', 'Robotics', 'RTOS', 'C/C++', 'Comunicação'],
    headerInfo: 'Mínimo de 5 anos de XP',
    url: 'app.onstrider.com/r/trampar_de_casa?job=c2VuaW9yLWVtYmVkZGVkLWVuZ2luZWVyLTFmNTY5Nzc3P3JlZmVycmFsPXRyYW1wYXJfZGVfY2FzYQ==',
  },
  {
    company: 'Strider',
    title: 'Senior Back-end Engineer - Node.js',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: [
      'Node.js',
      'Desenvolvimento de Software',
      'Revisão de Código',
      'Comunicação',
    ],
    headerInfo: 'Mínimo de 5 anos de XP',
    url: 'app.onstrider.com/r/trampar_de_casa?job=c2VuaW9yLWJhY2stZW5kLWVuZ2luZWVyLW5vZGUuanMtMGQ3NjQzODI/cmVmZXJyYWw9dHJhbXBhcl9kZV9jYXNh',
  },
  {
    company: 'Strider',
    title: 'Senior Data Engineer',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Data Engineering', 'Python', 'PySpark', 'Azure', 'Databricks'],
    headerInfo: 'Mínimo de 5 anos de XP',
    url: 'app.onstrider.com/r/trampar_de_casa?job=c2VuaW9yLWRhdGEtZW5naW5lZXItNWM0YzQ2YjQ/cmVmZXJyYWw9dHJhbXBhcl9kZV9jYXNh',
  },
  {
    company: 'Strider',
    title: 'Senior iOS Developer',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Swift', 'iOS', 'RESTful APIs', 'Comunicação'],
    headerInfo: 'Mínimo de 5 anos de XP',
    url: 'app.onstrider.com/r/trampar_de_casa?job=c2VuaW9yLWlvcy1kZXZlbG9wZXItc3dpZnQtYWIyNGVmOTc/cmVmZXJyYWw9dHJhbXBhcl9kZV9jYXNh',
  },
  {
    company: 'Strider',
    title: 'Lead Data Scientist',
    location: 'Estados Unidos',
    language: 'Inglês',
    currency: 'U$',
    skills: [
      'Data Science',
      'Generative AI',
      'Liderança Técnica',
      'Comunicação',
    ],
    headerInfo: 'Mínimo de 6 anos de XP',
    url: 'app.onstrider.com/r/trampar_de_casa?job=bGVhZC1kYXRhLXNjaWVudGlzdC1kOGViNmJjYT9yZWZlcnJhbD10cmFtcGFyX2RlX2Nhc2E=',
  },
  {
    company: 'Outliant',
    title: 'Lead React-Node Full Stack Engineer',
    location: 'Global',
    language: 'Inglês',
    currency: 'U$',
    skills: ['JavaScript', 'React.js', 'Node.js', 'AWS', 'Communication'],
    headerInfo: 'Mínimo de 6 anos de XP',
    url: 'https://jobs.ashbyhq.com/outliant/a60ebdca-562f-4126-99e2-03ea07043aff',
  },
  {
    company: 'Deepset',
    title: 'Senior DevSecOps Engineer',
    location: 'Global',
    language: 'Inglês',
    currency: 'U$',
    skills: ['Performance', 'Scalability', 'AWS', 'GitOps', 'Azure'],
    headerInfo: 'Mínimo de 7 anos de XP',
    url: 'https://deepset.jobs.personio.de/job/1182225?display=en',
  },
]

export const openings20230920: Openings = {
  localOpenings,
  globalOpenings,
}
